---
title: "我的性别陈述"
author:
  - 张正源
documentclass: ctexart
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
---

性别是我们每个人从出生起就会获得的一种属性，而这个词对我来说也有着特殊的意义，下面我来讲述性别是如何影响我的成长与生活的。

作为一个被指派为男性的孩子，我从小却是在一个在传统意义上更女性化的环境中长大的。因为父亲长期在外地工作，我是在我母亲与祖母的陪伴下度过的童年，也因此，造成了我小时候的性格更偏向于传统意义上的女性，比如我很少会与他人发生争吵，以及相比于户外体育运动，我更喜欢自己呆在房间里看书。而在我上小学时，我和母亲被父亲接去他工作的城市，也是从这时起，这个之前一直缺位的父亲角色才终于出现在我的成长过程中。而他为对我的陪伴过少感到羞愧，因此急于弥补之前亏欠的所谓父爱与父教。我的父亲是传统意义上的男性大家长，他心里对传统的男性气质也十分认同，因此在他看来，小时候的我非常缺乏男孩子应有的阳刚之气。他对我最多的教育就是“男孩要有男孩的样子”，认为我应该多进行体育锻炼，性格上也要大大咧咧而不是“像个小女生一样”。尤其令他反感的是我小时候很爱哭，每次我开始哭的时候他都会罚我在门口跪到不哭了为止，认为这样就能让我认同他“男儿有泪不轻弹”的观点，变成一个符合他期望的“男子汉”。而我自然对他这种教育非常反感，也是因此，我开始对传统意义上的男性身份产生了一种抗拒。

后来，在我上五年级时，因为我父亲工作上的不顺利，以及他参与赌博欠了一大笔钱，我们家为了躲债又回到了家乡的城市。也是从这时起，我父亲开始经常酗酒，回到家时往往带着一身烟味与酒气，而我非常不喜欢他身上的味道，也因此越发抗拒他抱我以及其他对我表示亲近的举动。而他喝醉酒回家后，又经常与我母亲发生争吵，甚至有时会动手家暴我母亲，这更让我对父亲角色的印象跌入的谷底。在那时的我看来，所谓的阳刚之气更多的代表着一种暴力与野蛮。而随着我上初中，我家庭的经济条件逐渐改善，这时我父亲又在长久的争吵后，逼迫我母亲放弃了自己的职业回归家庭。而这时的我也开始对婚姻与性别有了更多的认识与思考。如今回想起来，其中一个意义非凡的事是当时我的一个朋友送了我一本伍尔芙的《一间属于自己的房间》，伍尔芙也成为了我当时最喜欢也对我影响最大的作家。可以说伍尔芙是我对女性主义思想的启蒙者，她强调一种独特的女性意识，宣扬女性独特的价值，要求女性“成为自己”。而我在看到我母亲从放弃工作开始，是如何一步步丧失自己的独立性的观察，也让我对她提出的“独立女性应该有闲暇时间，有一笔由她自己支配的钱，和一个属于她自己的房间。”观点非常认同，她写下的那句“伟大的灵魂都是雌雄同体”也成为了我很久一段时间里的座右铭。伍尔芙对我的影响也并不止于女性主义启蒙和让我更加理解我母亲面对的境遇，她还让我真正开始思考关于自我与存在的问题。而沿着伍尔芙的思想，我在初三时第一次读到了加缪与萨特，也因此了解到第二个对我有重大意义的学者——波伏娃。我至今仍记得第一次读到《第二性》时的震撼，虽然我当时对社会还没有一个整体而系统的认识，但也开始理解到女性是后天而非先天被造就的。而这也与我的成长经历相符合，波伏娃让我开始认识到自己的性格与观念与我成长的环境与所受的教育关系非常大，我甚至受此启发开始认识到班级中的女生理科成绩不如男生其实是她们被老师教育“女生不擅长理科”的果而不是因，如今回想起来，这可能算是我第一次用批判性的思维思考的问题。

后来在我上高中时，参加了隔壁班同学组织的校刊编辑小组。而在第一次讨论栏目的会议上，我认识了一个在国际部上学的学姐。因为当时的我留长发，装束上也偏中性化，她问了我一句：“你是酷儿吗？”而这也是我第一次听到酷儿这个词。在我反问她酷儿是什么后，她给我普及了很多关于性少数群体如跨性别者与非二元性别者的相关知识，后来还送了我一本关于酷儿理论的书。这本叫《性别麻烦》的书也让我认识了第三位对我性别意识养成极为重要，并引导我后来成为酷儿的学者——朱迪斯巴特勒。在那位学姐的推动下，我们在校刊上开了一个关于性别研究的专栏，刊登一些关于女性主义，性少数群体及酷儿理论的文章，也是受此影响，我开始大量阅读关于性别研究的书籍，并开始关注性少数群体。我加入了好几个性少数论坛与群组，认识了一群性少数朋友，在这个过程中我也第一次认识到原来在性别与性向上偏离所谓的主流的人群有这么多，同时我也真正开始思考性别到底是什么，它对我有什么影响和意义。我开始问自己，当我说自己的性别认同是男性时，这个我认同的男性身份的含义到底是什么。朱迪斯巴特勒告诉我，我们应该打破身心二元论，也就是并不存在一个独立于生理性别之外的心理性别（也就是性别认同），我们其实只是在认同一个社会建构的性别，并按照这个社会性别角色进行一种表演。而打破这种性别对人的束缚的方法就是消解性别，让自我认同代替性别认同，而理解到这一点也是我选择成为一名酷儿的开始。

后来终于在我高三的时候，因为我父亲出轨并有了私生子，我母亲忍无可忍选择了起诉离婚。一审当然没有叛离，而我的祖父祖母们也以不能影响我高考为由，劝我母亲放弃起诉。在这个过程中，我感受到了我母亲面临的巨大压力，同时也深刻意识到了婚姻制度对女性的束缚。在闹了一年后，最终我父母还是离了婚，而讽刺的是，促成这个结果的竟然是我父亲的一句“我有追求我自己幸福的权利”。而几乎同年，我姑姑和我高中时最好的朋友的父母的婚姻也都以离婚告终，这更加深了我内心对婚姻制度的不信任，也让我开始对当代婚姻制度的本质产生了疑问。后来在大学里，我在选修的袁长庚老师的身体与情感的课上，了解到其实婚姻从历史上从来都是一种社会与经济关系，我们从小认为“理所应当”的以爱情为基础的婚姻其实是在上个世纪中才逐渐的成为主流，而如今全世界居高不下的理论率，也说明仅仅几十年的时间这种以爱情为基础的婚姻模式就已遭遇巨大的困境和危机。而在选修了政治经济学课程，以及阅读了上野千鹤子的《父权制与女性主义》后，我又得以能够从经济学角度审视当代的婚姻制度，我更意识到当代尤其是东亚的婚姻制度，其实本质上是一种父权制的体现。而我的家庭恰巧印证了这点，我的家庭是一个非常传统的东亚大家庭，权力关系完全由我祖父和我父亲主导，也因此某种程度上必然地造就了我母亲这个结构性受害者。而经过思想和观念上的不断成熟，我对我母亲的理解和认同也在不断加深，我开始认识到当代观念推崇的女性解放思想与所谓的独立女性形象其实是有漏洞的，我认为真正的女性主义思想应该让人们认识到一直以来被忽略的家务劳动的价值而不是将从事家务劳动看成是一种耻辱。

然后我想谈一下性别理论对我关于亲密关系的观念的影响。高中时在《断背山》与《阿黛尔的生活》等同性题材电影以及我的同性恋朋友们的影响下，我认识到真正的爱情应该是无关性别的。我们爱一个人不应该是因为ta的性别，而是因为ta这个人本身值得我们去爱。而在阅读了福柯的《性经验史》后，我又理解到在后现代语境下，性已经完全脱离了原始的生殖含义，而成为一种权力关系，这也与我对婚姻的思考联系在了一起。我在看到我父母的这种父权制下的婚姻的破产后，开始思考是否有更合理的亲密关系模式，由此想到会不会同性关系中会有更平衡的模式。但当我了解了很多同性关系模式之后，我发现很多同性恋情侣实际上也是在扮演异性恋，比如女同性恋中的“T”和“P”就是一种对异性恋中男性角色与女性角色的翻版，而造成这点的是异性恋霸权造成的社会语境。因此如果想追求平衡平等的亲密关系，首先要打破异性恋霸权，其次，我认识在不带有权力色彩的亲密关系中，我们不应该对我们的伴侣产生占有和支配，而应该把ta当作是一个自由独立的个体。而造成如“处女情结”这类对伴侣的占有与支配思想的一个重要因素，是一种由“一夫一妻制”衍生出的专偶制，因此打破专偶制思想也是追求平衡平等的亲密关系的重要前提与必须的过程。

综上所述，可以看出关于性别的思考几乎贯穿了我的成长过程，影响了我关于自我认同，婚姻制度，性向与亲密关系等各种事物的看法，甚至我如今的批判性思维方式与对生命与存在的意义的观念也是在我对性别问题的不断追问中形成的。最后，虽然我的个人经验可能不具有普遍性（如我和绝大多数的性少数群体不同，我大概不算是被社会建构为现在的样子，而是经过不断的阅读以及对性别这个问题的长期思考后，自己主动选择成为了一名酷儿，泛性恋以及开放式关系实践者），但希望这些经验能对其他对性别问题尚存疑问的人们有一些启发。
