# Option Pricing

## BSM model

The value of a delta hedge portfolio is $C-\Delta S_t$. The return is
$$
R =\frac{1}{2} \sigma^2 S^2\Gamma + \theta + r(\Delta S_t -C)
$$
If $\sigma=\sigma_{imp}$, $R=0$ with the absence of arbitrage. Thus if $\sigma$ is significantly differ with $\sigma_{imp}$, the return is
$$
R=\frac{1}{2} S^2 \Gamma(\sigma^2-\sigma^2_{imp})
$$
or we define $\nu=\frac{\partial C}{\partial  \sigma}=\sigma TS^2 \Gamma$, then
$$
R=\nu(\sigma-\sigma_{imp})
$$
thus
$$
R=\frac{\nu}{2\sigma T} (\sigma^2-\sigma^2_{imp})
$$

## Measure and predict volatility

As Jensen's inequality, square root of the unbiased estimator of $\sigma^2$ isnt unbiased on $\sigma$, to make use of the usual estimator $s^2=\frac{1}{N-1}\sum_{}^{}x_i^2$, we should fix it by dividing a term 
$$
b(N)=\sqrt{\frac{2}{N}} \frac{\Gamma\left( \frac{N}{2} \right)}{\Gamma \left( \frac{N-1}{2} \right)} \approx \sqrt{\frac{N-1}{N}}\left( 1-\frac{1}{4(N-1)} \right)
$$
where we use the truth:
$$
\frac{\Gamma \left( k+\frac{1}{2} \right)}{\Gamma (k)} = \sqrt{k} \left( 1-\frac{1}{8k}+\dots \right)
$$

Which slowly converge to $1$ as $N \to \infty$. Then
$$
\mathop{{}\mathbb{E}}_{}s=b(N)\sigma
$$
thus its variance is given by
$$
\mathop{\text{Var}}s=\mathop{{}\mathbb{E}}_{}s^2-\mathop{{}\mathbb{E}}_{}^2s=\frac{N-1}{N}\sigma^2-b(N)^2\sigma^2
$$
Apply the approximation of gamma function then omit second order term, we have
$$
b^2(N) \approx 1-\frac{3}{2N}
$$
Thus the variance of this estimator is approximately $\mathop{\text{Var}}s \approx \frac{\sigma^2}{2N}$.

Another estimator is under the log normal assumption
$$
\mathop{{}\mathbb{E}}_{}\left| R_t \right|=\sqrt{\frac{2}{\pi}}\sigma
$$

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

As Jensen's inequality, the unbiased estimator of $\sigma^2$ isnt unbiased on $\sigma$, and we should fix it by dividing a term 
$$
b(N)=\sqrt{\frac{2}{N}} \frac{\Gamma\left( \frac{N}{2} \right)}{\Gamma \left( \frac{N-1}{2} \right)}
$$
which converge to $1$ as $N \to \infty$.

