\newpage

## Notations


::: {.latex}

\begin{tabular}{p{7cm}p{10cm}}
$\mathbb{R}$ & $(-\infty,\infty)$ \\
$\overline{\mathbb{R}}$ & $[-\infty,\infty]$ \\
$\mathbb{R}_+$ & $[0,\infty)$\\
$\overline{A}$ & Closure of set $A$\\
$A^\circ$ & Interior of set $A$\\
$(x_n)\subset A$ & A sequence taking value in $A$\\
$2^A$ & The power set of $A$\\
$\mathcal{A}$ & A collection of subsets in $A$, i.e., $\mathcal{A}\subset 2^A$\\
$\ker \mathcal{A}$ & $\bigcap_{A\in \mathcal{A}} A$\\
$x_n \nearrow x$ & $(x_n)$ is increasing and converges to $x$.\\
$\sigma(\mathcal{A})$ & $\sigma$-algebra generated by $\mathcal{A}$. \\
$\mathcal{A}_+$ & Nonnegative function in $\mathcal{A}$ \\
$\mu \ll \nu$ & $\mu$ is absolutely continuous w.r.t. $\nu$.\\
$\mu f=\int f d\mu=\int f(x) \mu(dx)$ & integral\\

$f:X\to Y$ & $x$ is a function from $X$ to $Y$.\\

$f=x \mapsto 5x$ & $f(x)=5x$\\

$f:X \hookrightarrow Y$ & $f$ is an embedding from $X$ to $Y$.\\

$f(x)=O(g(x))   \iff g(x)=\Omega(f(x))$ & $f$ is bounded above by $g$ asymptotically \\& $\limsup_{x \to \infty} \frac{f(x)}{g(x)}<\infty$. \\

$f(x)=\Theta (g(x))$ & $f$ is bounded by $g$ \\& asymptotically both above and below .  \\

$f(x)=o(g(x)) \iff g(x)=\omega(f(x))$ & $f$ is dominated by $g$ asymptotically, i.e.,\\& $\lim_{x \to \infty} \frac{|f(x)|}{g(x)}=0$.  \\

$f(x) \sim g(x)$ & $f$ is equal to $g$ asymptotically i.e. \\& $\lim_{x \to \infty} \frac{f(x)}{g(x)}=1$. \\

$i_{\epsilon}$ & $\bm{\mathbf{1}}_{(\epsilon,\infty)}$\\






s.t. & such that\\
w.r.t. & with respect to\\
r.v. & random variable\\

\end{tabular}

:::

