## Kernels and Product spaces

::: {.definition name="transition kernel"}

Let $(E,\mathcal{E})$ and $(F,\mathcal{F})$ be measurable spaces. Let $K:E\times \mathcal{F}\to \overline{\mathbb{R}}_+$. Then, $K$ is called a transition kernel from $(E,\mathcal{E})$ into $(F,\mathcal{F})$ if:

- the mapping $x\mapsto K(x,B)$ is $\mathcal{E}$-measurable for every set $B\in \mathcal{F}$ 
- the mapping $B\mapsto K(x,B)$ is a measure on $(F,\mathcal{F})$ for every $x\in E$

:::


::: {.example  name=""}

If $\nu$ is a finite measure on $(F,\mathcal{F})$, and $k$ is a positive function on $E\times F$ that is $\mathcal{E\times F}$-measurable, then 
$$
K(x,B)=\int_B k(x,y) d\nu
$$
when fix $x\in E$, $K(x,B)=\nu(k(x,y)\bm{1}_{B})=\mu (B)$ for some $\mu$ which is the measure on $(F,\mathcal{F})$;  
when fix $B\in \mathcal{F}$, $f(x)=K(x,B)$ is measurable follows from theorem \@ref(thm:simple-approx).

:::

### Measure-kernel-function


::: {.theorem #kernel-op name=""}

Let $K$ be a transition kernel from $(E,\mathcal{E})$ into $(F,\mathcal{F})$. Then
$$
Kf(x)=\int_F K(x,dy)f(y)
$$
defines a function $Kf\in \mathcal{E_+}$ for every $f\in \mathcal{F_+}$;
$$
\mu K(B)=\int_E \mu (dx)K(x,B)
$$
defines a measure $\mu K$ on $(F,\mathcal{F})$ for each measure $\mu$ on $(E,\mathcal{E})$; and
$$
(\mu K)f=\mu (Kf)=\int_E \mu (dx)\int_F K(x,dy)f(y)
$$
for every measure $\mu$ on $(E,\mathcal{E})$ and function $f$ in $\mathcal{F_+}$.

:::

::: {.proof}

$Kf$ is well-defined and measurable follows form theorem \@ref(thm:simple-approx).

Define $L:\mathcal{F}_+ \to \overline{\mathbb{R}}_+=f \mapsto  \mu(Kf)$. Check

- $f(0)\xRightarrow{} L(f)=0$
- If $f,g\in \mathcal{F}_+$ and $a,b\in \overline{\mathbb{R}}_+$, then: 
    $$
    \begin{aligned}
    L(af+bg)&=\mu(K(af+bg))
    \\ & \xlongequal{Linearity}\mu(aKf + bKg)
    \\ &\xlongequal{linearity} a\mu(Kf)+b\mu(Kg)
    \\ &= aL(f)+bL(g)
    \end{aligned}
    $$
- Suppose $(f_{n})\subset \mathcal{F}_+$ and $f_n \nearrow f$, then
    $$
    L(f_n)=\mu(Kf_n)\nearrow \mu(Kf)=L(f)
    $$
    as MCT.

Hence, there exists a measure $\nu$ s.t. $L(f)=\mu(Kf)=\nu f$ as theorem \@ref(thm:characterization-integral). Then it suffices to show $\nu=\mu K$. Taking $f=\bm{1}_B$, we have $\nu(B)=\nu(\bm{1}_B)=\mu(K \bm{1}_B)$, it follows that
$$
\mu(K \bm{1}_B)=\int_E \mu(dx) \int_F K(x,dy) \bm{1}_B(y)=\int_E \mu(dx) K(x,B)=\mu K(B)
$$
:::


::: {.corollary #characterization-kernel name=""}

A mapping $f\mapsto Kf:\mathcal{F_+}\to \mathcal{E}_+$ specifies a transition kernel $K$ iff

- $K 0=0$
- $K(af+bg)=aKf+bKg$ for $f,g \in \mathcal{F}_+$ and $a,b \in \overline{\mathbb{R}}_+$
- $Kf_n \nearrow Kf$ for every $(f_{n}) \nearrow f\subset \mathcal{F}_+$.

:::

### Products of kernels

::: {.definition  name=""}

Let $K$ be a transition kernel from $(E,\mathcal{E})$ into $(F,\mathcal{F})$ and let $L$ be a transition kernel from $(F,\mathcal{F})$ into $(G,\mathcal{G})$. Then their **product** is the transition kernel $KL$ from $(E,\mathcal{E})$ into $(G,\mathcal{G})$ defined by
$$
(KL)f=K(Lf)
$$

:::

::: {.remark}

We can check $KL$ is a transition kernel indeed by corollary \@ref(cor:characterization-kernel). Obviously
$$
KL(x,B)=\int_F K(x,dy)L(y,B)
$$

:::

### Markov kernel

::: {.definition name=""}

Let $K$ be a transition kernel from $(\Omega,\mathcal{A})$ into $(\Omega',\mathcal{A}')$, it's called simply a transition kernel on $(\Omega,\mathcal{A})$ if $\mathcal{A}'=\mathcal{A}$, moreover, it's called a **Markov kernel** if $K(x,\Omega)=1,\forall x\in \Omega$ and a **sub-Markov kernel** if $K(x,\Omega)\le 1, \forall x\in \Omega$.

:::

If $K$ is a transition kernel on $(\Omega,\mathcal{A})$, similarly with product kernel, we can define its **power** by $K^n=KK^{n-1}$ and $K^0=I$ where $I$ is the identity kernel on $(\Omega,\mathcal{A})$: $I(x,A)=\bm{1}_A(x)$. To see why it's called "identity", check
$$
\begin{aligned}
    If(x)&=\int_{\Omega} I(x,dx)f(x)=\int_{\{x\}} f(x)=f(x)
    \\
    \mu I(A)&=\int_{\Omega} \mu(dx) I(x,A)=\int_A \mu(dx)=\mu(A)
\end{aligned}
$$
and thus $IK=KI=K$. It follows that if $K$ is Markov, so is $K^n$:
$$
\begin{aligned}
    KK(x,\Omega)&=\int_\Omega K(x,dy) K(y,\Omega)
    \\ &= \int_\Omega K(x,dy)
    \\ &= K(x,\Omega)=1
\end{aligned}
$$

### finite and bounded kernels

::: {.definition  name=""}

Let $K$ be a transition kernel from $(E,\mathcal{E})$ into $(F,\mathcal{F})$. In analogy with measures, it's called $\sigma$ finite and finite if $B \mapsto K(x,B)$ is so for each $x \in E$ 

It's called bounded if $x \mapsto K(x,F)$ is bounded and $\sigma$ bounded if there exists  a partition $(F_{n})\subset \mathcal{F}$ s.t. $x \mapsto K(x,F_n)$ is bounded for each $n$. 

It's said to be s-finite if there exists countable finite $(K_{n})$ s.t. $K=\sum_{}^{} K_i$ and s-bounded if those $(K_{n})$ can be bounded.

If $K(x,\mathcal{F})=1$ for all $x$, the kernel is said to be a **transition probability kernel**.

:::


::: {.remark}


$$
\begin{matrix} 
\text{bounded} & \implies & \sigma \text{-bounded} & \implies & s \text{-bounded}\\
\Downarrow &&\Downarrow&&\Downarrow\\
\text{finite} & \implies & \sigma \text{-finite} & \implies & s \text{-finite}\\
\end{matrix}
$$


:::


### Functions on product spaces

Sections of a measurable function are measurable:


::: {.proposition #selection-measurable name=""}

Let $f \in  \mathcal{X \times Y}$, then it's selection, $x \mapsto f(x,y)$ and $y \mapsto f(x,y)$ are measurable for each $x$ and $y$.

:::

Then we can generalize theorem \@ref(thm:kernel-op) to functions on product spaces:


::: {.lemma #generalize-kernel-op name=""}

Let $K$ be a s-finite kernel from $(X,\mathcal{X})$ into $(X,\mathcal{Y})$, then, $\forall f \in \left( \mathcal{X\times Y} \right)_+$, define
$$
Tf(x)=\int_F f(x,y) K(x,dy) \in \mathcal{X}_+
$$
moreover, $T:(\mathcal{X \times Y}) \to \mathcal{X}_+$ is linear and continuous from below:

- $T(af+bg)=aTf+bTg$ for $f,g \in (\mathcal{X \times Y})_+$ and $a,b \in \mathbb{R}_+$
- If $(f_n)\subset \mathcal{X\times Y} \nearrow f$, then $Tf_n \nearrow Tf$.


:::


::: {.proof}

By proposition \@ref(prp:selection-measurable), $f_x: y \mapsto f(x,y)$ is measurable in $\mathcal{F}_+$ and thus $Tf(x)=Kf_x(x)$, hence

-   Linearity:
    $$
    \begin{aligned}
        T(af+bg)(x) &= K(af_x+bg_x)(x)
        \\ &= aKf_x(x)+bKg_x(x)
        \\ &= aTf(x)+bTg(x)
        \\ &= (aTf+bTg)(x)
    \end{aligned}
    $$
-   Continuity from below 
    $$
    f_n \nearrow f \implies K{f_n}_x(x)\nearrow Kf_x(x)\implies Tf_n(x) \nearrow Tf(x)
    $$

Then it's remain to show $Tf \in \mathcal{X}_+$, assume $K$ is bounded, suppose 
$$
\mathcal{M}=\{f\in \left( \mathcal{X \times Y} \right)_+ \cup  \left( \mathcal{X \times Y} \right)_b: Tf \in \mathcal{X}\}
$$
it's easy to check it's a monotone class and include all indicator of measurable rectangle $A\times B$. By theorem \@ref(thm:MCT-function), we have $\mathcal{M}=\left( \mathcal{X \times Y} \right)_+ \cup  \left( \mathcal{X \times Y} \right)_b$.


:::

### Measures on the product space

::: {.theorem #product-measure-construction name=""}

Let $\mu$ be a measure on $(X,\mathcal{X})$ and $K$ be a s-finite kernel from $(X,\mathcal{X})$ to $(Y,\mathcal{Y})$, then for any $f\in (\mathcal{X\times Y})_+$
$$
\pi f=\int_{X}  \int_{Y} f(x,y) K(x,dy) d\mu 
$$
define a measure $\pi$ on the product space. Moreover, if $\mu$ if $\sigma$-finite and $K$ is $\sigma$ bounded, then $\pi$ is $\sigma$ finite and unique that satisfying:
$$
\pi(A\times B)=\int_{A} K(x,B) d\mu
$$

:::


::: {.proof}

To see $\pi f$ define a measure, check theorem \@ref(thm:characterization-integral), which follows from $\pi f=\mu(Tf)$ and similar properties enjoyed by $T$ from lemma \@ref(lem:generalize-kernel-op).

And the unique follows from theorem \@ref(thm:measure-agree) by noting that all measurable rectangles is a $\pi$-system.

:::

### Product measures and Fubini

::: {.definition #label name=""}

If $K(x,B)=\nu(B)$, i.e., independent to $x$, for some s-finite measure $\nu$ on $(Y,\mathcal{Y})$, then such $\pi$ is called **product** of $\mu$ and $\nu$.

:::

::: {.theorem #fubini name="Fubini's theorem"}

Let $\mu$ and $\nu$ be s-finite measures on $(X,\mathcal{X})$ and $(F,\mathcal{F})$, respectively. 

-   There exists a unique s-finite measure $\pi$ on $(X\times Y,\mathcal{X \times Y})$ s.t. $\forall f \in (X \times Y)_+$: 
    $$
    \pi f= \int_{X} \int_{Y} f(x,y) d\nu d\mu=\int_{Y}\int_{X} f(x,y) d\mu d\nu   
    $$
-   If $f\in \mathcal{X \times Y}$ and $\pi f < \infty$, then $y \mapsto f(x,y)$ is $\nu$ integrable $\mu$ a.e. for every $y$, $x \mapsto f(x,y)$ is $\mu$ integrable $\nu$ a.e. for every $x$.

:::


::: {.remark}

For $A\in \mathcal{X}$ and $B \in \mathcal{Y}$, we have
$$
\begin{aligned}
    \pi(A\times B)&=\pi \bm{1}_{A\times B}
    \\ &= 
    \int_{X} \int_{Y} \bm{1}_{A\times B}(x,y) d\nu d\mu
    \\ &= 
    \int_{X} \int_{Y} \bm{1}_{A}(x) \bm{1}_B(y) d\nu d\mu
    \\ &= \mu(A)\nu(B)
\end{aligned}
$$
and this is the reason we call $\pi$ the product and write $\pi=\mu \times \nu$.

:::


::: {.remark}

By theorem \@ref(thm:product-measure-construction), only if both $\mu$ and $\nu$ are $\sigma$-finite the $\pi$ is the unique product

:::

### Finite products

Now we can extend previous results to finitely many spaces' product. Similarly to product topology, $\prod_{i \in I} \mathcal{A_i}$ is generated by all measurable rectangles $\prod_{i \in I} A_i$ where $I$ is finite.

Let $(\mu_{n})$ be s-finite measures, their product measure is defined by analogy with theorem \@ref(thm:fubini), $\forall f\in \prod_{i \in I} \mathcal{A_i}$,
$$
\pi f=\int_{} \dots \int_{} f d\mu_n \dots d\mu_1 
$$

### Infinite products

Similar again with product topology, $\prod_{i \in I} \mathcal{A_i}$ is generated by all measurable rectangles $\prod_{i \in I} A_i$ where $A_i=\Omega_i$ with finite exception. In analogy with topology product, we have:


::: {.proposition #factor-measurable name=""}

Suppose there is $f_i:(X,\mathcal{F})\to (\Omega_i,\mathcal{A_i})$ for $i \in I$ and define $f(x)=(f_i(x))_{i \in I}$, then $f$ is measurable iff each $f_i$ is measurable.

:::



