# Convergence

## Convergence of Real Sequences

Suppose $(x_{i})_{i \in \mathbb{N}^*} \subset \mathbb{R}$, then $(x_i)\to x$ iff $\left|x_i-x\right|\to 0$ and the classical statement for convergence is the same as
$$
\sum_{i=1}^{\infty} i_{\epsilon}(\left|x_i-x\right|) < \infty \iff \limsup_{n \to \infty} i_{\epsilon}(\left|x_i-x\right|)=0 \iff i_{\epsilon}(\left|x_i-x\right|)\to 0
$$
holds for all $\epsilon > 0$.

### Cauchy criterion

Following are useful for determining convergence.

::: {.proposition #cauchy name="Cauchy criterion"}

Sequence $(x_n)$ converges iff
$$
\lim_{m,n \to \infty} |x_m-x_n|=0
$$

:::


::: {.proposition #epsilon-sequence name=""}

If there exists a positive sequence $(\epsilon_n)$ s.t.
$$
\sum_{n}^{} \epsilon_n <\infty, \sum_{n}^{} i_{\epsilon_n}(|x_{n+1}-x_n|)< \infty
$$
then $(x_{n})$ is convergent.

:::

### Subsequence

::: {.definition  name=""}

Let $(x_{i})_{i \in \mathbb{N}^*}$ be a sequence. Then $(x_{k_i})_{i \in \mathbb{N}^*}$ is a subsequence of $(x_{i})_{i \in \mathbb{N}^*}$ if $(k_{i})_{i \in \mathbb{N}^*}\subset \mathbb{N}$ if it's increasing with $\lim_{i \to \infty}k_i=\infty$. Regarding $\mathbb{N}$ as a sequence then $(k_{i})_{i \in \mathbb{N}^*}$ is a subsequence of $\mathbb{N}$. Denoted $(k_{i})_{i \in \mathbb{N}^*}$ as $N$, we can write $(x_{i})_{i \in N}$ for $(x_{k_i})_{i \in \mathbb{N}^*}$ and we say $(x_{i})_{i \in \mathbb{N}^*}$ converges along $N$ to $x$ if $\lim_{i \to \infty} x_{k_i}=x$.

:::


::: {.proposition  name=""}

Subsequence converges to $\limsup_{n \to \infty} x_n$ as a maximum and $\liminf_{n \to \infty} x_n$ as a minimum

:::

Following is useful for future studies.

::: {.lemma #sequence-mean name=""}

Let $(x_{i})_{i \in \mathbb{N}^*}\subset  \overline{\mathbb{R}}_+$ and put $\overline{x}_n=\frac{\sum_{i=1}^{n}x_i}{n}$. Let $N=(n_k)$ is a subsequence of $\mathbb{N}$ with $\lim_{k \to \infty}\frac{n_{k+1}}{n_k}=r>1$. If the sequence $(x_i)$ converges along $N$ to $x$, then
$$
\frac{x}{r} \le \liminf_{n \to \infty} \overline{x}_n \le \limsup_{n \to \infty} \overline{x}_n\le rx
$$

:::


::: {.proof}

For $n_k \le n <n_{k+1}$, note that
$$
\frac{n_k}{n_{k+1}}\overline{x}_{n_k}=\frac{\sum_{n_k}^{} x_i}{n_{k+1}} \le  \overline{x}_{n} \le  \frac{\sum_{n_{k+1}}^{} x_i}{n_{k}} = \frac{n_{k+1}}{n_k} \overline{x}_{n_{k+1}}
$$
Take limit each side we have result desired.

:::

### Diagonal method

::: {.lemma #diagonal-method  name=""}

Suppose there is a countable family of bounded sequence $\{S_i:i \in \mathbb{N}\}$, then there exists a subsequence $N$ of $\mathbb{N}$ s.t. each of them converges along $N$.

:::

::: {.proof}

As each $S_i$ is bounded, we can pick $N_1$ s.t. $S_1$ converges along $N_1$, then consider $S_2$ along $N_1$ as a new sequence there exists $N_2\subset N_1$ s.t. which converges along $N_2$. Thus for each $m < \infty$, we have $S_i$ converges along $N_m$ for $i\le m$.

Now let $n_m$ be the $m$th entry of $N_m$ and define $N=(n_1,n_2,\dots)$, one can check it's tail is a subsequence of each $N_i$ and thus $S_i$ converges along $N$ for each $i$.


:::


::: {.remark}

If the sequence $(N_{i})_{i \in \mathbb{N}^*}$ is written as
$$
\begin{bmatrix}
    N_1\\
    N_2\\
    \vdots
\end{bmatrix}
$$
then $N$ is precisely the diagonal of above matrix, and that's why it called diagonal method.

:::

Following is an application of some importance.

### Helly's Theorem


::: {.theorem #helly name="Helly's theorem"}

Suppose $(c_{i})_{i \in \mathbb{N}^*}$ is a sequence of d.f.'s, then there exists a subsequence $(b_{i})_{i \in \mathbb{N}^*}$ and a d.f. $c$ s.t. $\lim_{i \to \infty} b_i(t) = c(t)$ at which $t$ is continuous.

:::


::: {.proof}

Treat $(c_{i}(r))_{i \in \mathbb{N}^*}$ as a sequence and $r$ is taken as an enumeration of $\mathbb{Q}$. Consider the subsequence $N\subset \mathbb{N}$ from lemma \@ref(lem:diagonal-method), we claim that $(c_i)_{i \in N}$ is exactly $(b_{i})_{i \in \mathbb{N}^*}$, recall that $b(r)=\lim_{n \to \infty}b_n(r)$ exists for each $r\in \mathbb{Q}$.

For each $t\in \mathbb{R}$, define
$$
c(t)=\inf \{b(r):r\in \mathbb{Q}\text{ and }r>t\}
$$
One can check $c$ is a d.f. Then suppose $c$ is continuous at $t$, for any $\epsilon > 0$ there is a $s<t$ s.t. $c(s) > c(t)-\epsilon$ and there is a rational $r > t$ s.t. $b(r)<c(t)+\epsilon$ by definition. Pick rational $q$ s.t. $s < q < t < r$, we have
$$
c(t)-\epsilon < c(s) \le  b(q) \le  b(r)  <c(t)+\epsilon
$$
note:
$$
\begin{aligned}
    &\liminf_{n \to \infty} b_n(t) \ge \liminf_{n \to \infty} b_n(q)=b(q) 
    \\
    &\limsup_{n \to \infty} b_n(t) \le \limsup_{n \to \infty} b_n(r)=b(r) 
\end{aligned}
$$
thus they are sandwiched by $c(t)-\epsilon$ and $c(T)+\epsilon$ and thus agree at $c(t)$ and it follows that $\lim_{n \to \infty}b_n(t)=c(t)$.

:::

### Kronecker's Lemma

Following relates convergence of averages and convergence.


::: {.lemma  name=""}

Suppose $(x_{i})_{i \in \mathbb{N}^*}\subset \mathbb{R}$ and $(a_{i})_{i \in \mathbb{N}^*} \nearrow \infty$ be strictly positive. Put $y_n=\sum_{i=1}^{n}\frac{x_i}{a_i}$. If $(y_{i})_{i \in \mathbb{N}^*}$ converges, then
$$
\lim_{n \to \infty} \frac{\sum_{i=1}^{n} x_i}{a_n}=0
$$

:::


::: {.proof}

Put $a_0=y_0=0$. Note $x_i=(y_i-y_{i-1})a_i$ and
$$
\sum_{i=1}^{n} x_i=\sum_{i=0}^{n-1}(a_{i+1}-a_i)(y_n-y_i)
$$
By Cauchy criterion \@ref(prp:cauchy), there exists $k$ for any $\epsilon$ s.t. $|y_n-y_m|\le \epsilon$ for all $n,m\ge k$ and thus
$$
\begin{aligned}
    \left|\sum_{i=1}^{n}x_i\right|&=\left|\sum_{i=0}^{n-1}(a_{i+1}-a_i)(y_n-y_i)\right|
    \\ & \le 
\left|\sum_{i=k}^{n-1}(a_{i+1}-a_i)|y_n-y_i|\right|+
\left|\sum_{i=0}^{k-1}(a_{i+1}-a_i)|y_n-y_i|\right|
    \\ & \le 
    (a_n-a_k)\epsilon+\left|\sum_{i=0}^{k-1}(a_{i+1}-a_i)|y_n-y_i|\right|
    \\&\le 
    a_n\epsilon+\left|\sum_{i=0}^{k-1}(a_{i+1}-a_i)|y_n-y_i|\right|
\end{aligned}
$$
where the second term is finite and thus dominated by $a_n$, that implies $\lim_{n \to \infty}\frac{\left|\sum_{i=1}^{n}x_i\right|}{a_n}\to 0$ and then claim follows.

:::

## Almost Sure Convergence

Sequence of r.v.'s $(X_{i})_{i \in \mathbb{N}^*}$ is said to be converges if $(X_{i}(\omega))_{i \in \mathbb{N}^*}$ is so for all $\omega \in \Omega$.

As $\liminf_{n \to \infty} X_n$ and $\limsup_{n \to \infty}  X_n$ are r.v.'s, the set
$$
\Omega_0=\{\omega:\liminf_{n \to \infty} X_n=\limsup_{n \to \infty} X_n\}
$$
is an event. Then $(X_{i})_{i \in \mathbb{N}^*}$ is converges a.s. iff $\mathop{{}\mathbb{P}}(\Omega_0)=1$. 


### Borel-Cantelli lemmas

::: {.definition #io-ult name=""}

Suppose $(A_{i})_{i \in \mathbb{N}^*}$ is sequence of events, then **infinite often(i.o.)** and **ultimately(ult.)** are defined by:
$$
\begin{aligned}
     \{A_n,\ i.o.\}&=\limsup_n A_n=\bigcap_{n=1}^\infty \bigcup_{m=n}^\infty A_m=\lim_{n\to\infty}\sup\{ A_{n:\infty}\}=\lim_{n\to\infty}\bigcup_{m=n}^\infty A_m
     \\   \{A_n,\ ult.\}&=\liminf_n A_n=\bigcup_{n=1}^\infty \bigcap_{m=n}^\infty A_m=\lim_{n\to\infty}\inf\{ A_{n:\infty}\}=\lim_{n\to\infty}\bigcap_{m=n}^\infty A_m
\end{aligned}
$$

:::


::: {.remark}

By intuition, we have:

1. $\{A_n \text{ ult.}\}^c=\{A_n^c \text{ i.o.}\}$
2. $\bm{\mathbf{1}}_{\{A_n \text{ i.o.}\}}=\{\bm{\mathbf{1}}_{A_n} \text{ i.o.}\}$, $\bm{\mathbf{1}}_{\{A_n \text{ ult.}\}}=\{\bm{\mathbf{1}}_{A_n} \text{ ult.}\}$
3. $\{A_n \text{ i.o.}\}=\{\omega:\sum_{n=1}^{\infty} \bm{\mathbf{1}}_{A_n}=\infty\}$, $\{A_n \text{ ult.}\}=\{\omega:\sum_{n=1}^{\infty} \bm{\mathbf{1}}_{A_n^c}<\infty\}$
4. $\{A_n \text{ i.o.}\} \subset \{A_n \text{ ult.}\}$
5. $\mathop{{}\mathbb{P}}(\liminf_{n \to \infty} A_n)\le \liminf_{n \to \infty} \mathop{{}\mathbb{P}}(A_n)\le \limsup_{n \to \infty} (A_n)\le \mathop{{}\mathbb{P}}(\limsup_{n \to \infty} A_n)$

:::

Borel-Cantelli lemma implies some sufficient conditions for a.s. convergence.

::: {.lemma #borel-cantelli name="Borel-Cantelli lemma"}

Let $(A_{i})_{i \in \mathbb{N}^*}$ be a sequence of events. Then
$$
\sum_{i=1}^{\infty} \mathop{{}\mathbb{P}}(A_i) < \infty \implies \sum_{i=1}^{\infty} \bm{\mathbf{1}}_{A_i} < \infty \text{ a.s.} \iff \mathop{{}\mathbb{P}}\{A_n \text{ i.o.}\}=0
$$
If $(A_i)$ are independent, then
$$
\sum_{i=1}^{\infty} \mathop{{}\mathbb{P}}(A_i)=\infty \implies \sum_{1=1}^{\infty} \bm{\mathbf{1}}_{A_i}=\infty \text{ a.s.} \iff \mathop{{}\mathbb{P}} \{A_n \text{ i.o.}\}=1
$$

:::

::: {.proof}

By the MCT \@ref(thm:MCT),
$$
\mathop{{}\mathbb{E}} \sum_{i=1}^{\infty} \bm{\mathbf{1}}_{A_i}=\sum_{i=1}^{\infty}\mathop{{}\mathbb{E}}1_{A_i}=\sum_{i=1}^{\infty}\mathop{{}\mathbb{P}}(A_i)<\infty
$$
and the claim follows as remark 2 in [**Properties of expectation**][Properties of expectation].

If $(A_i)$ are independent, noting $1-x \le e^{-x}$ for all $x\in \mathbb{R}$, it's sufficient to show that $0\le 1-\mathop{{}\mathbb{P}}\{A_n \text{ i.o.}\}\le 0$:
$$
\begin{aligned}
    0 & \le  
    1-\mathop{{}\mathbb{P}}\{A_n \text{ i.o.}\}=\mathop{{}\mathbb{P}}\{A_n^c \text{ ult.}\}
    \\ &= 
    \mathop{{}\mathbb{P}}(\liminf_{n \to \infty} A_n^c)=\lim_{n \to \infty} \mathop{{}\mathbb{P}}(\inf_{m \ge n}A_m^c)
    \\ &=
    \lim_{n \to \infty}\mathop{{}\mathbb{P}}(\bigcap_{m=n}^{\infty} A_m^c)=
    \lim_{n \to \infty}\lim_{r \to \infty}\mathop{{}\mathbb{P}}(\bigcap_{m=n}^{r}A_m^c)
    \\ &= 
    \lim_{n \to \infty}\lim_{r \to \infty} \prod_{m=n} ^{r} [1-\mathop{{}\mathbb{P}}(A_m)] \text{ (by independence)}
    \\ & \le 
    \lim_{n \to \infty}\lim_{r \to \infty} \prod_{m=n} ^{r} [e^{-\mathop{{}\mathbb{P}}(A_i)}]
    \le 
    \lim_{n \to \infty}\lim_{r \to \infty} \prod_{m=n} ^{r} [e^{-\sum_{m=n}^{r}\mathop{{}\mathbb{P}}(A_m)}]
    \\ &= 
    \lim_{n \to \infty} e ^{-\sum_{m=n}^{\infty}\mathop{{}\mathbb{P}}(A_m)}=\lim_{n \to \infty}0=0
\end{aligned}
$$


:::


### Convergence a.s. theorem

::: {.theorem #convergence-as name=""}

Suppose $(X_{i})_{i \in \mathbb{N}^*}$ is sequence of r.v.'s, let
$$
Y_n=\sup_{i,j \ge n}\left|X_i-X_j\right|,Z_n=\sup_k \left|X_{n+k}-X_n\right|
$$ 
TFAE:

1.  $X_n \to X$ a.s.
2.  For every $\epsilon > 0$,
    $$
    \sum_{i=1}^{\infty} i_{\epsilon}\circ \left|X_n-X\right| <\infty \text{ a.s.}
    $$
3.  For every $\epsilon>0$,
    $$
    \mathop{{}\mathbb{P}}(\left|X_n-X\right|\ge \epsilon \text{ i.o.})=0
    $$
4. $Y_n \to 0$ a.s.
5. $Z_n \to 0$ a.s.

:::


::: {.proof}

$1 \iff 2$ follows from the equivalent statement of convergence stated at the [beginning][Almost Sure Convergence].

$2 \iff 3$ follows from remark 1 and 3 in definition \@ref(def:io-ult).

$1\iff 4 \iff 5$ is clearly follows from 2.


:::



::: {.proposition  name=""}

The follows are sufficient for convergence a.s.:

1.  For every $\epsilon > 0$
    $$
    \sum_{n \to  \infty}^{} \mathop{{}\mathbb{P}}\{\left|X_n-X\right|>\epsilon\}<\infty
    $$
2.  There exist a sequence $(\epsilon_{i})_{i \in \mathbb{N}^*} \searrow 0$ s.t.
    $$
    \sum_{n \to  \infty}^{} \mathop{{}\mathbb{P}}\{\left|X_n-X\right|>\epsilon\}<\infty
    $$
3.  There exist a sequence $(\epsilon_{i})_{i \in \mathbb{N}^*} > 0$ s.t. 
    $$
    \sum_{n \to  \infty}^{} \epsilon_n < \infty,  \sum_{n \to  \infty}^{} \mathop{{}\mathbb{P}} \{ \left|X_{n+1}-X_n\right|>\epsilon_n\} < \infty
    $$
4.  For every $\epsilon > 0$, 
    $$
    \liminf_{n \to \infty}\lim_{m \to \infty} \mathop{{}\mathbb{P}}\{\sup_{k\le m}\left|X_{n+k}-X_n\right|>\epsilon\}=0
    $$

:::


::: {.proof}

1.  By Borel-Cantelli lemma \@ref(lem:borel-cantelli), that implies statement $2$ in theorem \@ref(thm:convergence-as) and thus implies $X_n \to X$ a.s..
2.  As $\epsilon_n \to 0$, the equality also holds for all $\epsilon$ as one can always find a less $\epsilon$ from $(\epsilon_{i})_{i \in \mathbb{N}^*}$ and thus $2\implies 1$.
3.  By Borel-Cantelli lemma and proposition \@ref(prp:epsilon-sequence).
4.  Write $Z_n$ for $\sup_{k \ge 1}\left|X_{n+k}-X_n\right|$, by remark 5 in definition \@ref(def:io-ult):
    $$
    \begin{aligned}
        0=\liminf_{n \to \infty} \mathop{{}\mathbb{P}}\{Z_n > \epsilon\}
        &\ge  
        \mathop{{}\mathbb{P}}(\liminf_{n \to \infty} 
    \{Z_n > \epsilon\}
    )=0
    \end{aligned}
    $$
    thus $\{Z_n>\epsilon \text{ ult.}\}$ has probability $0$ and thus $\{Z_n>\epsilon \text{ i.o.}\}$ is so, then $(Z_n)$ is converges and so is $(X_n)$ as theorem \@ref(thm:convergence-as).3,5.

:::

## Convergence in Probability











<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>



