## Martingale

A process $X=(X_{i})_{t \in T}$ is called a submartingale of $\mathbb{F}$ if it's adapted to $\mathbb{F}$ with integrable $X_t$ and
$$
\mathop{{}\mathbb{E}}_{s}(X_t-X_s)=\mathop{{}\mathbb{E}}_{s}X_t-X_s\ge 0
$$
whenever $s<t$. It's a supmartingale if $-X$ is submartingale and it's a martingale if it's both submartingale and supmartingale.


::: {.remark}

1.	
    Let $X$ be submartingale in $\mathbb{F}$, for $p<s<t \in T$,
    $$
    \mathop{{}\mathbb{E}}_{p} (X_t-X_s)=\mathop{{}\mathbb{E}}_{p}\mathop{{}\mathbb{E}}_{s}(X_t-X_s)\ge \mathop{{}\mathbb{E}}_{s}0=0
    $$

1. When $T$ is discrete, for instance, $T=\mathbb{N}$, then  the it's sufficient to check the cases when $s$ and $t$ are next to each other. 

2.	
    Note $\mathop{{}\mathbb{E}}_{s}(X_t-X_s)$ is positive given $X$ is a submartingale in $\mathbb{F}$, then it's zero $a.s.$ iff
    $$
    \mathop{{}\mathbb{E}}_{}\mathop{{}\mathbb{E}}_{s}(X_t-X_s)=\mathop{{}\mathbb{E}}_{}X_t-\mathop{{}\mathbb{E}}_{}X_s=0
    $$
    that hold for all martingale $X$.
3.  All the martingale is a vector space.
4.  If $X$ and $Y$ are submartingale, then so is $X \lor Y$, if they are both supmartingale, so is $X \land Y$.
5.  Let $f$ be a convex function and $X$ be martingale, if $f\circ X_t$ is integrable for all $t$, then $f \circ X$ is submartingale by Jensen's inequality:
    $$
    \mathop{{}\mathbb{E}}_{s} f \circ X_t \ge f\circ \mathop{{}\mathbb{E}}_{s}X_t = f\circ X_s
    $$
    In particular, if $X$ is martingale, $X^+$, $X^-$ and $\left| X \right|$ are submartingale, and so is $\left| X \right|^{p}$ if $X \subset L^p$.
6.  The condition of submartingale can be replaced by 
    $$
    \mathop{{}\mathbb{E}}_{}(X_t-X_s) \bm{1}_{F}=\mathop{{}\mathbb{E}}_{}\mathop{{}\mathbb{E}}_{s}(X_t-X_s)\bm{1}_{F} \ge 0
    $$
    for all $F \in \mathcal{F}_s$ since integral of positive function is positive in any measurable set.
7.  Let $X$ be an $\mathbb{F}$-submartingale, and $\mathcal{G}$ the filtration generated by $X$, $i.e.$, $\mathcal{G}_T=\sigma(X_t:t\le T)$, then
    $$
    \mathop{{}\mathbb{E}}_{\mathcal{G}_s}(X_t-X_s)=\mathop{{}\mathbb{E}}_{\mathcal{G}_s}\mathop{{}\mathbb{E}}_{s}(X_t-X_s) \ge \mathop{{}\mathbb{E}}_{\mathcal{G}_s}0=0
    $$
    that shows that $X$ is also a submartingale in $\mathcal{G}$.

:::

### Uniformly integrable martingale

Suppose $Z$ is $r.v.$, then $\left\{ \mathop{{}\mathbb{E}}_{t}Z \right\}_{t\in T}$ generate a martingale, and it's uniformly integrable from the following:

::: {.lemma  name=""}

Suppose $Z$ be integrable $r.v.$, then
$$
\mathcal{K}=\left\{ X:X=\mathop{{}\mathbb{E}}_{\mathcal{G}}Z \text{ for some } \mathcal{G}\subset \mathcal{F}  \right\}
$$

:::


:::: {.proof}

Recall $\mathcal{K}$ is uniformly integrable if $f\circ\left| \mathcal{K} \right|$ is integrable for some convex and increasing $f\gg x$. To this end, take $f\ s.t.\ f\circ \left| Z \right|$ is integrable, then employ Jensen's inequality twice:
$$
f\circ \left| X \right| = f \circ \left| \mathop{{}\mathbb{E}}_{\mathcal{G}} Z \right|\le f \circ \mathop{{}\mathbb{E}}_{\mathcal{G}} \left| Z \right| \le \mathop{{}\mathbb{E}}_{\mathcal{G}} f\circ \left| Z \right|
$$
Now claim follows from taking expectations both sides.

::::

### Markov chains


::: {.definition  name=""}

The (discrete)process $X$ is called a Markov chain with transition kernel $P$ $\it{ w.r.t }$ $\mathbb{F}$ if $X$ is adapted to $\mathbb{F}$ and
$$
\mathop{{}\mathbb{E}}_{t} f\circ X_{t+1}=(Pf)\circ X_t
$$
for every $f \in \mathcal{E}_{+}$ and $t \in \mathbb{N}$.

:::

The following connect martingale and Markov chain:


::: {.theorem  name=""}

Suppose $X$ adapted to $\mathcal{F}$, then $X$ is a Markov chain with transition kernel $P \text{ w.r.t } \mathbb{F}$ iff
$$
M_n=f\circ X_n-\sum_{i=0}^{n-1}(Pf-f) \circ X_i
$$
is a martingale $\text{ w.r.t } \mathbb{F}$ for every $f \in \mathcal{E}_{+} \cap \mathcal{E}_{b}$. 

:::

:::: {.proof}

Note that $M_{n+1}-M_n=f\circ X_{n+1}-(Pf)\circ X_n$.

::::

### Wiener Process


::: {.definition  name=""}

Process $W=(W_{i})_{i \in \mathbb{R}^+}$ adapted to $\mathbb{F}$ taking values in $\mathbb{R}$ with starting point $W_{0}=0$ is Winner process if
$$
\mathop{{}\mathbb{E}}_{s}f(W_{s+t}-W_{s})=\mathop{{}\mathbb{E}}_{}f\circ \mathcal{N}(0,t)   
$$
for all $s$ and $t$ in $\mathbb{R}_{+}$ and all $f \in \mathcal{B}_{+}$.

:::


::: {.theorem  name=""}

TFAE:

1. The process $W$ is a winner process $\text{ w.r.t }\mathbb{F}$, 

2. $\exp \left\{ rW_{t}-\frac{1}{2}r^2t \right\}$ is an $\mathbb{F}$ martingale.

3. $W$ is an $\mathbb{F}$ martingale and $W_{t}^2-t$ is an $\mathbb{F}$ martingale.

:::

### Poisson martingale


::: {.definition  name=""}

The counting process $N$ adapted $\mathbb{F}$ is said to be a Poisson process with rate $c$ $\text{ w.r.t }\mathbb{F}$ if
$$
\mathop{{}\mathbb{E}}_{s}f(N_{s+t}-N_{s})=\mathop{{}\mathbb{E}}_{}f\circ \mathfrak{P}_{ct}
$$

:::

The definition is equivalent to $N_{t}-ct$ is a martingale adapted to $\mathbb{F}$.





































<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

