## Martingale Transformation

This section contains results for discrete time.

### Doob's decomposition

::: {.definition  name=""}

A process $\left\{ X_{t} \right\}_{t \in \mathbb{N}}$ is said to be $\mathbb{F}$-predictable if $X_0 \in \mathcal{F}_0$ and $X_{n+1}\in \mathcal{F}_{n}$ for every $n \in \mathbb{N}$.

:::


::: {.theorem #doob-decomposition name="Doob's decomposition theorem"}

Let $X$ be integrable and adapted, then it can be decomposed as
$$
X_n=X_0+M_n+A_n
$$
where $M$ is a martingale while $A$ is a martingale, both starting at $0$.

:::

### Integration in discrete time

Suppose $M$ and $F$ are real-valued stochastic process and define:
$$
X_n=M_0F_0+\sum_{n\ge 1}^{}(M_n-M_{n-1})F_n
$$
that is the integral of $F \text{ w.r.t }$ to $M$ and write $X=\int FdM$


::: {.theorem  name="You can't beat the system"}

Let $F$ be a bounded predictable process, $X=\int FdM$ is a supermartingale if so is $M$ and $F\ge 0$, it's a martingale if so is $M$.


:::


::: {.proposition  name=""}

Suppose $S$ and $T$ are stopping time of $\mathbb{F}$ with $S\le T$, for any $V \in \mathcal{F}_{S}$, then
$$
V \bm{1}_{(S,T]},V \bm{1}_{(s,\infty]},\bm{1}_{(S,T]},\bm{1}_{[0,S]}
$$
are all predictable. 

:::

:::: {.proof}

Let $F=V \bm{1}_{(S,\infty]}$, note
$$
F_{n+1}=V \bm{1}_{(s,\infty]}(n+1)=V \bm{1}_{S\le n}\in \mathcal{F}_{n}
$$
thus $V \bm{1}_{(S,\infty]}$ is predictable and $V \bm{1}_{(S,T]}$ is predictable by noting it is difference between $V \bm{1}_{(T,\infty]}$ and $V \bm{1}_{(S,\infty]}$. Finally, let $V=1$ yields the other two.

::::

Let $F=\bm{1}_{[0,T]}$ in preceding theorem, we have the stopped supermartingale $\left\{ X^{T}_{n}=X_{\tau \land  n} \right\}$, is a supermartingale if so is $X$. 

### Doob's Optional-Stopping Theorem

Here the time set is still $\mathbb{N}$.

::: {.theorem  name=""}

Let $M$ adapted to $\mathbb{F}$, TFAE:

1. $M$ is a submartingale.
2. 
    For bounded stopping time $S\le T$,
    $$
    \mathop{{}\mathbb{E}}_{s}(M_{T}-M_{S})\ge 0   
    $$
    and both are integrable.
3. 
    For bounded stopping time $S\le T$,
    $$
    \mathop{{}\mathbb{E}}_{}(M_{T}-M_{S})\ge 0   
    $$
    and both are integrable.

:::




::: {.theorem  name=""}

Let $\tau$ be a stopping time, let $X$ be a supermartingale. Then $X_\tau$ is integral and $\mathop{{}\mathbb{E}}_{}X_{\tau}\le \mathop{{}\mathbb{E}}_{}X_0$ if one of flowing holds:

1.  $\tau$ is bounded.
2.  $X$ is bounded and $\tau$ is $a.s.$ bounded.
3.  $\mathop{{}\mathbb{E}}_{}\tau<\infty$ and $\left| X_n-X_{n-1} \right|$ is bounded for any $n$.

:::

Apply this to both $X$ and $-X$, we have $\mathop{{}\mathbb{E}}_{}X_{\tau}=\mathop{{}\mathbb{E}}_{}X_0$ and $X$ is integral under the same situations.


::: {.corollary  name=""}

Suppose $X$ is a martingale with increments $X_{n}-X_{n-1}$ is bounded and $C$ is bounded previsible processes, $\mathop{{}\mathbb{E}}_{}\tau<\infty$, then
$$
\mathop{{}\mathbb{E}}_{}(CX)_{\tau}=0
$$

:::

::: {.corollary  name=""}

If $X\ge 0$ is supermartingale and $\tau$ is $a.s.$ finite, then $\mathop{{}\mathbb{E}}_{}X_{\tau}\le \mathop{{}\mathbb{E}}_{}X_0$.

:::

:::: {.proof}
$$
\mathop{{}\mathbb{E}}_{}X_{\tau}=\mathop{{}\mathbb{E}}_{}\liminf_n X_{\tau \land n}\le \liminf_n \mathop{{}\mathbb{E}}_{}X_{\tau \land n} \le \mathop{{}\mathbb{E}}_{}X_0
$$

::::

### Maxima and Minimum

Suppose $X$ is a discrete marginal adapted to $\mathbb{F}$, for $n \in \mathbb{N}$, define
$$
M_n=\max _{k\le n}X_{k}, m_n=\min _{k\le n} X_{k}   
$$


::: {.theorem  name=""}

Suppose $X$ is a submartingale, then for $b>0$,
$$
\begin{aligned}
    b\mathop{{}\mathbb{P}}\left\{ M_n>b \right\}&\le \mathop{{}\mathbb{E}}_{}M_n^{+}\\
    b \mathop{{}\mathbb{P}}\left\{ m_n\le -b \right\}&\le \mathop{{}\mathbb{E}}_{}M_n^{+}-\mathop{{}\mathbb{E}}_{}M_0
\end{aligned}
$$

:::


:::: {.proof}

Let $\tau$ and $\sigma$ be the stopping time $\text{ s.t. }$
$$
\tau=\inf_{\mathbb{N}} \left\{ X_n\ge b \right\},\sigma=\inf _{\mathbb{N}}\left\{ X_n\le -b \right\}
$$
then $\left\{ M_n\ge b \right\}=\left\{ T\le n \right\}$, "untaking" expectation each side, we have
$$
b \bm{1}_{\tau\le n}\le X_{\tau \land n} \bm{1}_{\tau\le n} \le \mathop{{}\mathbb{E}}_{\tau \land n} X_n \bm{1}_{\tau \le  n} 
$$
for the minimum, note
$$
M_{\sigma \land n} = M_{\sigma}\bm{1}_{\sigma\le n}+M_{n}\bm{1}_{\sigma>n}\le -b \bm{1}_{\sigma\le n}+M_n \bm{1}_{\sigma >n}    
$$

::::

When $M$ is a martingale, $\left| M \right|^{p}$ is a submartingale provided $M \subset L^p$.
$$
\mathop{{}\mathbb{E}}_{}\left( \left| M_{t} \right|^{p}-\left| M_{s} \right|^{p} \right)\ge \mathop{{}\mathbb{E}}_{} \left| M_{t}-M_{s} \right|^{p} \ge (\mathop{{}\mathbb{E}}_{}\left| M_{t}-M_{s} \right|)^{p}=0
$$

### Awaiting the almost inevitable

::: {.lemma  name=""}

Suppose that $\tau$ is a stopping time $s.t.$ for some $N\in \mathbb{N}$ and $\varepsilon>0$, we have $\forall n \in \mathbb{N}$:
$$
\mathop{{}\mathbb{P}}_{\mathcal{F}_n}\left\{ \tau\le n+N \right\}>\varepsilon
$$
$a.s.$, then $\mathop{{}\mathbb{E}}_{}\tau<\infty$.


:::

### Upcrossings

Under the general setting for $X,C,Y$ and numbers $a<b$, where we play stake $C=1$ when $X< a$ and stop if $X> b$, namely, for $n\ge 2$
$$
C_n:=\bm{1}_{C_{n-1}=1}\bm{1}_{X_{n-1}\le b}+\bm{1}_{C_{n-1}=0}\bm{1}_{X_{n-1}<a}
$$
Then we denoted $U_N[a,b]$ as times of upcrossings from $a$ to $b$ by time $N$. Clearly, we have
$$
Y_{N} \ge (b-1)U_{N}[a,b]-(X_N-a)^{-}
$$

::: {.lemma #doob-upcrossings name="Doob's Upcrossing Lemma"}

Let $X$ be a supermartingale, then
$$
(b-a) \mathop{{}\mathbb{E}}_{}U_N[a,b]\le \mathop{{}\mathbb{E}}_{}(X_N-a)^{-}
$$

:::


:::: {.proof}

From $Y_N$ is a supermartingale.

::::


::: {.corollary  name=""}

Let $X$ be a supermartingale bounded in $L^{1}$, $i.e.$, $\sup_n \mathop{{}\mathbb{E}}_{}\left| X_n \right|<\infty$, then with $U_{N}[a,b] \nearrow U_{\infty}[a,b]$,
$$
(b-a)\mathop{{}\mathbb{E}}_{}U_{\infty}[a,b]\le \left| a \right|+\sup _n \mathop{{}\mathbb{E}}_{}\left| X_n \right|<\infty
$$
and thus $\mathop{{}\mathbb{P}}\left\{ U_{\infty}[a,b]=\infty \right\}=0$.

:::


:::: {.proof}

By \@ref(lem:doob-upcrossings), we have
$$
(b-a)\mathop{{}\mathbb{E}}_{}U_{N}[a,b]\le \left| a \right|+\mathop{{}\mathbb{E}}_{}\left| X_n \right|\le \left| a \right|+\sup _n \mathop{{}\mathbb{E}}_{}\left| X_n \right|
$$
for arbitrary $N$, then claim follows by taking $N \nearrow \infty$.

::::

### Doob's Forward Convergence Theorem


::: {.theorem #doob-convergence name=""}

Let $X$ be supermartingale bounded in $L^{1}$ then it's converges to some finite $X_{\infty}$ $a.s.$. 

:::

:::: {.proof}

For $\omega\in \Omega$, divergence of $X_n(\omega)$ is equivalent to $X$ upcross some $[a,b]$ infinite times, take $[a,b]$ from $\mathbb{Q}$, that should be countable, thus $X_{\infty}$ exists $a.s.$. And finiteness comes from
$$
\mathop{{}\mathbb{E}}_{}\left| X_{\infty} \right|=\mathop{{}\mathbb{E}}_{}\liminf \left| X_n \right|\le \liminf \mathop{{}\mathbb{E}}_{} \left| X_n \right|\le \sup \mathop{{}\mathbb{E}}_{}\left| X_n \right|<\infty
$$

::::

::: {.corollary  name=""}

If $X\ge 0$ is supermartingale, then $X_{\infty}$ exists $a.s.$.

:::


:::: {.proof}

$X$ is bounded since it's supermartingale: $\mathop{{}\mathbb{E}}_{}\left| X_n \right|=\mathop{{}\mathbb{E}}_{}X_n\le \mathop{{}\mathbb{E}}_{}X_0$.

::::

## Martingale bounded in $L^2$

### Martingale in $L^2$ 

Suppose martingale $M\subset L^2$. Then for $s<t<u<v\in \mathbb{N}^{+}$, we have
$$
\mathop{{}\mathbb{E}}_{u}M_v=M_u
$$
that's, $M_u$ is projection of $M_v$ in $L^2(\mathcal{F}_u)$ and thus
$$
\left\langle M_t-M_s,M_v-M_u \right\rangle= 0
$$
hence
$$
\mathop{{}\mathbb{E}}_{}M_n^2=\mathop{{}\mathbb{E}}_{}M_0^2 + \sum_{k=1}^{n}\mathop{{}\mathbb{E}}_{} (M_k-M_{k-1})^2
$$


::: {.theorem  name=""}

Let $M\subset L^2$ be a martingale, then it's bounded in $L^2$ iff
$$
\sum_{}^{}\mathop{{}\mathbb{E}}_{}(M_{k}-M_{k-1})^2<\infty
$$
and when this obtains, $M_n\xrightarrow{a.s.}M_{\infty}$ and $M_n \xrightarrow{L^2}M_{\infty}$.

:::


:::: {.proof}

Equivalence of boundedness of $M$ and boundedness of this series is immediately. When this obtains, theorem \@ref(thm:doob-convergence) implies $M_n\xrightarrow{a.s.}M_{\infty}$ from boundedness and $M_n \xrightarrow{L^2}M_{\infty}$ since it's cauchy in $L^2$ from the conditions.

::::

### Sums of zero-mean independent variables in $L^2$    

The following is just restatement of theorem \@ref(thm:variance-series-convergence) and its converse.

::: {.theorem name=""}

Suppose $(X_{i})_{i \in \mathbb{N}}$ is a sequence of independent $r.v.$ with zero mean and finite variance. Then

1.  $\sum_{}^{}\sigma_i^2<\infty \implies \sum_{}^{}X_i$ converges $a.s.$.
2.  If $(X_n)$ is uniformly bounded, then $\sum_{}^{}\sigma_i^2 \iff \sum_{}^{}X_i$ converges $a.s.$.

:::





























































 


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>








