# Measure and integrations

## Measurable space

### $\sigma$ algebra



::: {.definition  name=""}

A nonempty system of subset of $\Omega$ is an algebra on $\Omega$ if it's

1. Closed under complement: $A^c \in \mathcal{A} \iff A\in \mathcal{A}$
2. Closed under finite union: $\cup_i A_i \in \mathcal{A} \impliedby \forall i,  A_i\in\mathcal{A}$

it's an $\sigma$ algebra on $\Omega$ if it's also closed under countable union.

:::


::: {.remark}

$\mathcal{A}$ is an algebra auto implies $\emptyset\in \mathcal{A}$ and $\Omega \in \mathcal{A}$. So $\{\emptyset,\Omega\}$ is the minimum algebra on $\Omega$ and thus minimum $\sigma$ algebra while the discrete algebra $2^{\Omega}$ is maximum.

:::


Let $\left\{ \mathcal { A } _{ \gamma } : \gamma \in \Gamma \right\}$ is a collection of  $\sigma$ algebra, then we have $\mathcal { A } = \cap_ { \gamma \in \Gamma } \mathcal { A } _ { \gamma }$ is also  a $\sigma$ algebra. Hence we can define the smallest $\sigma$ algebra as intersection of all $\sigma$ algebras contains $\mathcal{A}$, that called the $\sigma$ algebra **generated** by $\mathcal{A}$ and denoted by $\sigma(\mathcal{A})$.

The smallest $\sigma-$algebra generated by the system of all open sets in a topological space $(\Omega,\tau)$ is called **Borel $\sigma$ algebra** on $\Omega$ and denoted by $\mathcal{B(\Omega)}$, its elements are called **Borel sets**.

### $\pi,\lambda,m$ systems

A collection of subsets $\mathcal{A}$ is called.

1. **m-system** if closed under monotone series, that is if $(A_n)\subset \mathcal{A}$ and $A_n \nearrow A$, then $A\in \mathcal{A}$.
2. **$\pi-$system** is closed under finite intersection
3. **$\lambda-$ system** if

	1. $\Omega \in \mathcal{A}$

	2. closed under proper difference:

	   $$
	   A-B \in \mathcal{A} \impliedby B\subset A \text{ and } B,A\in \mathcal{A}
	   $$

	3. is an m-system.


::: {.theorem  name=""}

Let $\mathcal{A}$ be a collection of subsets of $\Omega$ iff it's both a $\pi$ system and $\lambda$ system.

:::


Which can be proved as follows:

- $\implies:$
  1. $\Omega \in \mathcal{A}$
  2. $A-B=A\cap B^c\in \mathcal{A}$
  3. is an m-system
- $\impliedby:$
  1. $A^c=\Omega-A\in \mathcal{A}$
  2. $A \cup B =(A^c \cap B^c)^c \in \mathcal{A}$
  3. hence $\mathcal{A}$ is an algebra and $\mathcal{A}$ is a m-system.

Similarly, for $m,\pi,\lambda$ -system, they also has a minimum system generated by some collection $\mathcal{C}$.


::: {.lemma  name=""}

Let $\mathcal{A}$ be an algebra, then

1. $m(\mathcal{A})=\sigma(\mathcal{A})$
2. if $\mathcal{B}$ is an $m$ class and $\mathcal{A}\subset \mathcal{B}$, then $\sigma(\mathcal{A})=m(\mathcal{A})\subset \mathcal{B}$

Similarly, let $\mathcal{A}$ be a $\pi$ class, then $\lambda(\mathcal{A})=\sigma(\mathcal{A})$

:::


Then we have **Monotone class theorem**:


::: {.theorem  name=""}

$\forall \mathcal{A} \subset  \mathcal{B} \subset  \mathcal{P}(\Omega),s.t.$:

1. If $\mathcal{A}$ is a $\pi$-class, $\mathcal{B}$ is a $\lambda-$class, then $\sigma(\mathcal{A})\subset \mathcal{B}$
2. If $\mathcal{A}$ is an algebra, $\mathcal{B}$ is a $m-$class, then $\sigma(\mathcal{A})\subset \mathcal{B}$


:::

### Graphical illustration of different classes

$$ 
\begin{matrix}
\sigma\text{ algebra} & \xLeftrightarrow{}& \lambda \text{ system} &+&\pi \text{ system}\\
\Downarrow & & \Downarrow & &\\
\text{algebra} & & m\text{ system} &&\\
\Downarrow\\
\text{semialgebra}\\
\Downarrow \\
\pi \text{ system}
\end{matrix}
$$

### Measurable spaces

::: {.definition  name="Measurable Space"}

Pair $(\Omega,\mathcal{A})$ where $\mathcal{A}$ is a $\sigma$-Algebra on $\Omega$.

:::


::: {.definition  name="Products of measurable spaces"}

Let $(E,\mathcal{E}), (F,\mathcal{F})$ be two measurable spaces. For $A\subset E,B\subset F$, $A\times B$ is the set of all pairs $(x,y):x\in A,y\in B$. Note that $\mathcal{E\times F}$ is also a $\sigma$-Algebra with all $A\times B$ where $A\in \mathcal{E}, B\in \mathcal{F}$ which is called  *the product $\sigma$-Algebra*.

:::



## Measurable function

### Mappings

Let $f : \Omega _{ 1 } \rightarrow \Omega_ { 2 }$ be a mapping, $\forall B\subset \Omega_2$ and $\mathcal{G} \subset \mathcal{P(\Omega_2)}$, the **inverse image** of 

- $B$ is $f ^ { - 1 } ( B ) = \left\{ \omega :\omega \in \Omega _ { 1 } , f ( \omega ) \in B\right\} : = \{ f \in B \}$

- $\mathcal{G}$ is $f ^ { - 1 } ( \mathcal { G } ) = \left\{ f ^ { - 1 } ( B ) : B \in \mathcal { G } \right\}$

There is some properties:

1. $f ^ { - 1 } \left( \Omega _ { 2 } \right) = \Omega _ { 1 } , f ^ { - 1 } ( \emptyset ) = \emptyset$
2. $f ^ { - 1 } \left( B ^ { c } \right) = \left[ f ^ { - 1 } ( B ) \right] ^ { c }$
3.
     $$ \begin{array} { l } f ^ { - 1 } \left( \cup _ { \gamma \in \Gamma } B _ { \gamma } \right) = \cup _ { \gamma \in \Gamma } f ^ { - 1 } \left( B _ { \gamma } \right) \text { for } B _ { \gamma } \subset \Omega _ { 2 } , \gamma \in \Gamma \\ f ^ { - 1 } \left( \cap _ { \gamma \in \Gamma } B _ { \gamma } \right) = \cap _ { \gamma \in \Gamma } f ^ { - 1 } \left( B _ { \gamma } \right) \text { for } B _ { \gamma } \subset \Omega _ { 2 } , \gamma \in \Gamma \end{array} $$
     
     where $\Gamma$ may not countable.
4. $f ^ { - 1 } \left( B _ { 1 } - B _ { 2 } \right) = f ^ { - 1 } \left( B _ { 1 } \right) - f ^ { - 1 } \left( B _ { 2 } \right) \forall B _ { 1 } , B _ { 2 } \subset \Omega _ { 2 }$
5. $B_1\subset B_2 \subset \Omega_2 \implies f^{-1}(B_1) \subset f^{-1}(B_2)$
6. If $\mathcal{B}$ is a $\sigma-$algebra, $f^{-1}(\mathcal{B})$ is also a $\sigma-$algebra.
It's easy to check $f^{-1}(\mathcal{B})$ is closed under complement and countable union. (From properties 2 and 3)

7. If $\mathcal{C}$ is nonempty, $f ^ { - 1 } ( \sigma ( \mathcal { C } ) ) = \sigma \left( f ^ { - 1 } ( \mathcal { C } ) \right)$

**Remarks** $f^{-1}$ preserves all the set operations on $\Omega$.

### Measurable functions


::: {.definition  name=""}

For two measurable spaces $(\Omega_1,\mathcal{A})$, $(\Omega_1,\mathcal{B})$, $f : \Omega _ { 1 } \rightarrow \Omega _ { 2 }$ is a **measurable mapping** if $f ^ { - 1 } ( \mathcal{B} ) \subset \mathcal { A }$, where
$$ 
f^{-1}(\mathcal{B})=\{f^{-1}(B):B\in \mathcal{B}\}
$$

It is a **measurable function** if $\left( \Omega _ { 2 } , \mathcal { B } \right) = \left( \mathcal { R } ^ { n } , \mathcal { B } \left( \mathcal { R } ^ { n } \right) \right)$, moreover, a **Borel function** if $\left( \Omega _ { 1 } , \mathcal { A } \right) = \left( \mathcal { R } ^ { m } , \mathcal { B } \left( \mathcal { R } ^ { m } \right) \right)$


:::




::: {.remark}

If $\mathcal{B=\sigma(C)}$, the definition can be reduced to $f^{-1}(\mathcal{C})\subset \mathcal{A}$
since
$$ f ^ { - 1 } ( \mathcal { B } ) = f ^ { - 1 } ( \sigma ( \mathcal { C } ) ) = \sigma \left( f ^ { - 1 } ( \mathcal { C } ) \right) \subset \sigma ( \mathcal { A } ) = \mathcal { A } $$


:::


::: {.lemma #composite-measurable name=""}

Suppose $f:\mathcal{E\to F}$ and $g:\mathcal{F\to G}$ are measurable, then so is $f\circ g$.

:::


::: {.proof}

The same as how we proved composition of continuous function is continuous.

:::

## Random Variable

A r.v. $X$ is a measurable function from $(\Omega_1,\mathcal{A})$ to $(\mathcal{R},\mathcal{B})$. It denoted by $X$ is $\mathcal{A}$-measurable or $X \in \mathcal{A}$

**(Another definition)**: A r.v. $X$ is a measurable mapping from $(\Omega,\mathcal{A},P)$ to $(\mathcal{R},\mathcal{B})$ such that
$$ P ( | X | = \infty ) = P ( \{ \omega : | X ( \omega ) | = \infty \} ) = 0 $$



::: {.lemma  name=""}

$X$ is a r.v. from $(\Omega,\mathcal{A})$ to $(\mathbb{R},\mathcal{B})$ 
$$ 
\begin{aligned}
\iff {X\le x}=X^{-1}([-\infty],x)\in \mathcal{A} \quad \forall x\in \mathbb{R} \\ \iff {X\le x}=X^{-1}([-\infty],x)\in \mathcal{A} \quad \forall x\in D
\end{aligned}
$$
where $D$ is a dense subset of $\mathbb{R}$, e.g. $\mathbb{Q}$. $\{X \le x\}$ above can be replaced by
$$ \{ X \leq x \} , \quad \{ X \geq x \} , \quad \{ X < x \} , \quad \{ X > x \} , \quad \{ x < X < y \} $$

:::




### Construction of random variables


::: {.lemma  name=""}

$\mathbf{X}=(X_1,\cdots,X_n)$ is a random vectors if $X_k$ is a r.v. $\forall k$ iff $\mathbf{X}$ is a measurable function from $(\Omega,\mathcal{A})$ to $(\mathcal{R^n},\mathcal{B(R^n)})$.

:::


::: {.proof}

Note that

$$ \{\mathbf{X}\in \prod I_n\}=\bigcap\{X_n \in I_n\}\in \mathcal{A} $$

where $I_k=(a_k,b_k],-\infty\le a_k\le b_k\le \infty$ and follows from $\sigma(\{\prod I_n\})=\mathcal{B(R^n)}$. For the other direction, note

$$
\{X_k\le t\}=\{\mathbf{X}\in \prod_{i< k} \mathbb{R}  \times \{-\infty,t\}\times \prod_{i > k} \mathbb{R}\} \in \mathcal{A}
$$

:::

Recall lemma \@ref(lem:composite-measurable) we have:


::: {.theorem  name=""}

$\forall$ random $n$ vectors $X=(X_{1:n})$ and Borel function $f$ from $\mathcal{R^n\to R^m}$, then $f(X)$ is a random $m$ vectors.

:::



::: {.remark}

Note that continuous function are borel measurable since continuity leads to inverse image of an open set is still open. So if $X_{1:n}$ are r.v.'s, so are $\sum X_n$, $\sin(x)$, $e^X$, $\text{Poly}(X),\cdots$. That implies:

$\forall X, Y\in \mathcal{A}$, so are $aX+bY,X \vee Y = \max \{ X , Y \} , X \wedge Y = \min \{ X , Y \},X^2,XY,X/Y,X^+=\max(x,0),X^-=-\min(x,0),|X|=X^++X^-$


:::


### Limiting opts

Let $(X_n)$ are r.v. on $(\Omega,\mathcal{A})$, then $\sup_{n\to \infty} X_n,\inf_{n\to \infty} X_n,\limsup_{n\to \infty} X_n,\liminf_{n\to \infty} X_n$ are r.v.'s. Moreover, if it exists, $\lim_{n \to \infty} X_n$ is r.v..


::: {.proof}

First two follows from, $\forall t\in \mathbb{R}$:

$$ \begin{aligned}
  \{\sup_{n\to \infty} X_n \le t\}&=\bigcap_{n=1}^\infty \{X_n \le t\} \in \mathcal{A}
  \\ \{\inf_{n\to \infty} X_n \ge t \}&=\bigcap_{n=1}^\infty \{X_n \ge t\} \in \mathcal{A}
\end{aligned}$$

and the last two follows from $\limsup_{n\to \inf}=\inf_{k\to \infty} \sup_{m\ge k} X_m$ and $\liminf_{n\to \inf}=\sup_{k\to \infty} \inf_{m\ge k} X_m$. 


:::

That implies

::: {.lemma  name=""}

If $S=\sum_1^\infty X_n$ exists everywhere, then $S$ is a r.v.

:::



::: {.proof}

Note $\sum_1^\infty X=\lim_{n\to \infty}\sum_n X_n$ is a r.v. 

:::



If $X=\lim_{n\to \infty} X_n$ holds **almost** everywhere, i.e., define $\Omega_0$ is the set of all $\omega$, such that $\lim_n X_n(\omega)$ exists, then $P(\Omega_0)=1$, we say that $X_n$ converges a.s. and write:

$$ X_n \to X \quad a.s. $$

For a measurable function $f$, we may modify it at a null set into $f'$ and it remain measurable since for any open set $G$, $f'^{-1}(G)$ differ $f^{-1}(G)$ a at most null set, by the completion of Lebesgue measure space, $f'{-1}(G)$ is measurable and thus $f^{-1}$ measurable. Hence, for $f_n \to f$ a.s., we may ignore a null set and then $f_n\to f$ everywhere and thus $f$ measurable.



### Approximations of r.v. by simple r.v.'s


::: {.definition  name=""}

If $A\in \mathcal{A}$, the indicator function $\bm{\mathbf{1}}_A$ is a r.v. If $\Omega=\sum_1^n{A_i}$, where $A_i \in \mathcal{A}$, then $X=\sum_1^n a_i \bm{\mathbf{1}}_{A_i}$ is a r.v. and called **simple r.v.**

:::


Any r.v. can be approximated by simple ones:


::: {.theorem  name=""}

$\forall X \in \mathcal{A}$, $\exists 0\le X_1\le X_2 \cdots X_n$ s.t. $X _ { n } ( \omega ) \nearrow X ( \omega )$ everywhere.

:::



::: {.proof}

Suppose

$$ X_n(\omega)=\sup\{\frac{j}{2^n}:j\in \mathbb{Z},\frac{j}{2^n}\le \min(X(\omega),2^n)\}  $$

One can check $X_n$ is simple r.v. and $X_n(\omega) \nearrow X(\omega)$ for all $\omega \in \Omega$.

:::


###  $\sigma$ algebra generated by r.v.

Let $\left\{ X _ { \lambda } , \lambda \in \Lambda \right\}$ is r.v.s on $(\Omega,\mathcal{A})$. Define
$$ \sigma \left( X _ { \lambda } , \lambda \in \Lambda \right) : = \sigma \left( X _ { \lambda } \in B , B \in \mathcal { B } , \lambda \in \Lambda \right) = \sigma \left( X _ { \lambda } ^ { - 1 } ( \mathcal { B } ) , \lambda \in \Lambda \right) = \sigma \left( \cup _ { \lambda \in \Lambda } X _ { \lambda } ^ { - 1 } ( \mathcal { B } ) \right) $$
which is called  $\sigma$ algebra generated by $\left\{ X _ { \lambda } , \lambda \in \Lambda \right\}$, where $\Lambda$ is a index set which can be uncountable. 

For $\Lambda=\mathbb{N^+}$:

1. 
   $$ \begin{aligned} \sigma \left( X _ { i } \right) & = \sigma \left( X _ { i } ^ { - 1 } ( \mathcal { B } ) \right) = X _ { i } ^ { - 1 } ( \mathcal { B } ) = \left\{ X _ { i } \in \mathcal { B } \right\} \\ \sigma \left( X _ { 1 } , \ldots , X _ { n } \right) & = \sigma \left( \cup _ { i = 1 } ^ { n } X _ { i } ^ { - 1 } ( \mathcal { B } ) \right) = \sigma \left( \cup _ { i = 1 } ^ { n } \sigma \left( X _ { i } \right) \right) \end{aligned} $$
2. 
   $$ \begin{array} { c } \sigma \left( X _ { 1 } \right) \subset \sigma \left( X _ { 1 } , X _ { 2 } \right) \subset \ldots \ldots \subset \sigma \left( X _ { 1 } , \ldots , X _ { n } \right) \\ \sigma \left( X _ { 1 } , X _ { 2 } , \ldots . . \right) \supset \sigma \left( X _ { 2 } , X _ { 3 } , \ldots . . \right) \supset \ldots \ldots \supset \sigma \left( X _ { n } , X _ { n + 1 } , \ldots . . \right) \end{array} $$

3. $\bigcap_1^\infty \sigma(X_n,X_{n+1},\cdots)$ is the tail $\sigma$ algebra of $X_{1:}$

If $A_{1:n}$ are not mutually exclusive to each other, then we have

$$ |\sigma(A_{1:n})|=2^{2^n} $$

Which follows from for a partition $A_{1:n}$,

$$ \sigma(A_1,\cdots,A_n)=\{\bigcup_{i\in J} A_i\} $$ 

where $J$ is any subset of $\mathbb{N}\le n$ and $A_0=\emptyset$. Hence for discrete r.v. $Y$, $\sigma(Y)$ can be generated from $A_i=\{Y=y_i\}$ forall $y_i$'s. For continuous case, it's generated by all intervals.

### Monotone classes of function

::: {.definition  name="monotone class"}

$\mathcal{M}$ is called a monotone class if:
- $1\in \mathcal{M}$ 
- $f,g\in \mathcal{M_b}$ and $a,b\in \R\implies af+bg\in \mathcal{M}$ 
- $(f_n)\subset M_+, f_n\uparrow f\implies f\in \mathcal{M}$ 

where $\mathcal{M_+}$ is a subcollection consisting of positive functions in $\mathcal{M}$, and $\mathcal{M_b}$ for the bounded function in $\mathcal{M}.$

:::


::: {.theorem  name="Monotone class theorem for functions"}

Let $\mathcal{M}$ be a monotone class of functions on $E$. Suppose for some p-system $\mathcal{C}$ generating $\mathcal{E}$ and $1_A\in \mathcal{M}$ for every $A\in \mathcal{C}$. Then $\mathcal{M}$ includes all positive $\mathcal{E}$-measurable functions and all bounded $\mathcal{E}$-measurable functions.

:::


::: {.proof}

First we need to show that $1_A\in \mathcal{M}$ for every $A\in \mathcal{E}$. Let $\mathcal{D}=\{A\in \mathcal{E}:1_A\in \mathcal{M}\}$. Now we check that $\mathcal{D}$ is a d-system:
- $1_E=1$, so $E \in \mathcal{D}$.
- $B\subset A,\ A,B\in \mathcal{D}$. $1_{A-B}=1_A-1_B\in \mathcal{D}$ 
- $(A_n)\subset \mathcal{D}$ and $A_n\uparrow  A$, then $1_{A_n}\uparrow 1_A$, so $1_A\in \mathcal{M}$, then  $A\in \mathcal{D}$ 

By assumption, $\mathcal{C\subset D}$, and $\sigma(\mathcal{C})$ is the smallest d-system by the theorem above, so  $\mathcal{E\subset D}$, so $1_A\in \mathcal{M}$ for every $A\in \mathcal{E}$.  
As $1_A\in \mathcal{M}$ for every $A\in \mathcal{E}$, we can easily prove that all of the positive simple function is generated by the linear combination of $1_A$ s. And all positive $\mathcal{E}$-measurable functions is generated by a sequence of positive simple functions. Then for general bounded $\mathcal{E}$-measurable function $f$, using $f=f^{+}-f^{-}$ where $f^{+},f^{-}\in \mathcal{M}$.

:::


::: {.definition  name=""}

Let $(E,\mathcal{E}),(F,\mathcal{F})$ be two measurable spaces and $f$ is a bijection $E\to F$. Then $f$ is said to be a isomorphism of $(E,\mathcal{E})$ and  $(F,\mathcal{F})$ if $f$ is $\mathcal{E}$-measurable and $f^{-1}$ is $\mathcal{F}$-measurable. These two spaces are called isomorphic if there exists an isomorphisms between them.  

:::


::: {.definition name=""}

A measurable space $(\Omega,\mathcal{A})$ is said to be *standard* if it there exist an embedding $f: (\Omega,\mathcal{A}) \hookrightarrow (\mathbb{R},\mathcal{B})$.

:::


::: {.remark}

Clearly, $([0,1],\mathcal{B}([0,1]))$, $(\mathbb{N}\le n,2^{N\le n})$ and $(\mathbb{N},2^{\mathbb{N}})$ are all standard. In fact, every standard measurable space is isomorphic to one of them.

:::





## Measure


Let $\Omega$ be a space and $\mathcal{A}$ a class, then function $\mu : \mathcal { A } \rightarrow R = [ - \infty , \infty ]$ is a **set function**.

It's

- 1.  **finite** if $\forall A\in \mathcal{A},\quad |\mu(A)|<\infty$
  2. **$\sigma$-finite** if $\exists A_n \subset \mathcal{A},\quad s.t.\quad\cup_ { i = 1 } ^ { \infty } A _{ i } = \Omega\quad \forall n \quad |\mu(A_n)|<\infty$
  3. **s finite** if there exist countable finite $(\mu_n)$ s.t. $\mu=\sum_{n} \mu_n$.

- 1.  **additive** $\iff \mu \left( \sum _{ i = 1 } ^ { n } A_ { i } \right) = \sum _{ i = 1 } ^ { n } \mu \left( A_ { i } \right)$
  2. **$\sigma-$additive**$\Longleftrightarrow \mu \left( \sum _{ i = 1 } ^ { \infty } A_ { i } \right) = \sum _{ i = 1 } ^ { \infty } \mu \left( A_ { i } \right)$

::: {.remark}

Finite implies $\sigma$ finite and $\sigma$ finite implies $\Sigma$ finite.

:::


$\mu$ is a **measure** on $\mathcal{A}$ if

1. $\forall A \in \mathcal { A } : \mu ( A ) \geq 0$ 
2. It's $\sigma$ additive.

the triplet $(\Omega,\mathcal{A},\mu)$ is a **measure space** when $\mu$ is a measure and $(\Omega,\mathcal{A})$ is  a measurable space.  Whose sets are called **measurable sets** or **$\mathcal{A}$-measurable**.A measure space is a **probability space** if $P(\Omega)=1$.

Assume that $A_{1:n}\in\mathcal{A}$ and $A\in \mathcal{A}$ and $\mu$ is a measure.

1. $\mu$ is continues from above, if $A _{ n } \searrow A \implies \mu(A_n)\to\mu(A)$
2. $\mu$ is continues from below, if $A _{ n } \nearrow A \implies \mu(A_n)\to\mu(A)$
3. $\mu$ is continues at $A$, if $A _{ n } \to A \implies \mu(A_n)\to\mu(A)$

$\forall$ Measure $\mu$ is continues from below and may not continues from above. It will be continues from above if $\exists m<\infty,\mu(A_m)<\infty$.So finite measure $\mu$ are always continues.

### Properties of measure

#### Semialgebras

Let $\mu$ be a nonnegative additive set function on a semialgebra $\mathcal{A}$. $\forall A,B\in \mathcal{A}$ and $\{A_n,B_n,n\ge 1\} \in \mathcal{A}$

1. (**Monotonicity**): $A\subset B\implies \mu(A)\le\mu(B)$ 

2. (**$\sigma$-subadditivity**):

    1. $\sum _{ 1 } ^ { \infty } A_ { n } \subset A , \quad \Longrightarrow \quad \sum _{ 1 } ^ { \infty } \mu \left( A_ { n } \right) \leq \mu ( A )$
    2. Moreover, if $\mu$ is a measure, then

$$ B \subset \sum _{ n = 1 } ^ { \infty } B_ { n } \implies\mu ( B ) \leq \sum _{ n = 1 } ^ { \infty } \mu \left( B_ { n } \right) $$

We can assert a nonnegative set function $\mu$ is a measure by:

1. $\mu$ is additive
2. $\mu$ is $\sigma$ subadditive on $\mathcal{S}$

#### Algebras

Algebras enjoy all the properties of semialgebra, also, we have


::: {.theorem  name="$\sigma$ subadditivity"}

Let $\mu$ be a measure on an algebra $\mathcal{A}$ 
$$ A \subset \cup _{ 1 } ^ { \infty } A_ { n } \implies \mu ( A ) \leq \sum _{ 1 } ^ { \infty } \mu \left( A_ { n } \right) $$

:::



::: {.proof}

Note $A=A\cap(\cup A_n)=\cup(A\cap A_n)$, hence we can write $A$ as union in $\mathcal{A}$ by take $B_n=A\cap A_n \in \mathcal{A}$.

$$ A=\cup_1^\infty B_n $$

and then we can take $C_n=B_n-\cup_1^{n-1} B_i \in \mathcal{A}$ to write $A$ as disjoint union:

$$ A=\sum C_n $$

Then 

$$ \mu(\mathcal{A})=\mu(\sum C_n)=\sum \mu(C_n)\le \sum \mu(B_n)\le \sum\mu(A_n) $$

as $C_n \subset B_n \subset A_n$. 

:::


#### $\sigma$ algebras

Let $\mu$ be a measure on an $\sigma$ algebra $\mathcal{A}$ 

1. Monotonicity
2. Boole's inequality(Countable Sub-Additivity) 
   $$ \mu \left( \cup _{ i = 1 } ^ { \infty } A_ { i } \right) \leq \sum _{ i = 1 } ^ { \infty } \mu \left( A_ { i } \right) $$
3. Continuity from below
4. Continuity from above if $\mu$ is finite in $A_i$.

The sense of **4** follows from suppose $A_i \searrow A$, then $A_1-A_i \nearrow A_1-A$, then

$$ \mu(A_1)-\mu(A)=\mu(A_1-A)=\lim \mu(A_1-A_i)=\mu(A_1)-\lim(A_i) $$

where $\mu(A_1)$ cannot be cancelled if $\mu(A_i)=\infty$.


::: {.definition  name=""}

Let $(\Omega,\mathcal{A},\mathcal{\mu})$ be a measure space, and $N\subset\Omega$

1. $N$ is a **$\mu$ null set** iff $\exists B\in \mathcal{A} \quad s.t. \quad \mu(B)=0, \quad N\subset B$
2. This measure space is a **complete measure** space if $\forall$ $\mu$ null space $N$, $N\in \mathcal{A}$

:::



::: {.theorem  name=""}

Given any measure space $(\Omega,\mathcal{A},\mathcal{\mu})$ , there exist a complete measure space $(\Omega,\mathcal{\bar{A}},\mathcal{\bar{\mu}})$, such that $\mathcal{A}\subset \bar{\mathcal{A}}$ and $\bar{\mu}$ is an extension of $\mu$. This space is called completion of $(\Omega,\mathcal{A},\mathcal{\mu})$.

:::



::: {.proof}

Take 

$$ \begin{aligned}
  \bar{\mathcal{A}}&=\{A\cup N:A\in \mathcal{A}\}\\
  \bar{\mathcal{B}}&=\{A\Delta N:A\in \mathcal{A}\}
\end{aligned} $$

$\bar{\mathcal{A}}=\bar{\mathcal{B}}$ since $A\cup N=(A-B) \Delta (B\cap (A\cup N))$ and $A\Delta N=(A-B)\cup(B\cap(A\Delta N))$.

Then we can show that $\bar{\mathcal{A}}$ is a $\sigma$ algebra. Let $\Omega_i=A_i \cup N_i\in \bar{\mathcal{A}}$, then

$$ \bigcup_1^\infty \Omega_i=\bigcup_1^\infty A_i \cup \bigcup_1^\infty N_i $$ 

and note $\bigcup_1^\infty A_i\in \mathcal{A}$ and $\mu(\bigcup_1^\infty N_i)\le \mu(\cup_1^\infty B_i)\le \cup_1^\infty \mu(B_i)=0$. Thus $\bar{\mathcal{A}}$ is closed by countable union. As for complements, note $\Omega^c=A^c \cap N^c=(A^c\cap N^c \cap B^c)\cup (A^c\cap N^c \cap B)=(A^c\cap B^c)\cup (A^c\cap N^c\cap B)\in \bar{\mathcal{A}}$.

Finally we define a measure $\bar{\mu}$ on $\bar{\mathcal{A}}$ by

$$ \bar{\mu}(A\cup N)=\mu(A) $$

We should prove it's well defined. Suppose $A_1\cup N_1=A_2 \cup N_2 \in \bar{\mathcal{A}}$, note $A\Delta B \Delta C=A\Delta (B\Delta C)$ and $A\Delta B=B\Delta A$.

$$\begin{aligned}
  (A_1\Delta A_2)\Delta(N_1\Delta N_2)&=(A_1\Delta A_2 \Delta N_1)\Delta N_2
  \\&=(A_1\Delta N_1)\Delta(A_2\Delta N_2)
  \\&=\emptyset
\end{aligned}$$

Hence $A_1 \Delta A_2=N_1\Delta N_2$, note $N_1\Delta N_2 \subset N_1\cup N_2 \subset B_1 \cup B_2$, hence $\mu(A_1\Delta A_2)=0$ and thus $\mu(A_1 - A_2)=\mu(A_2-A_1)=0$. Therefore

$$ \begin{aligned}
  \mu(A_1)&=\mu(A_1-A_2)+\mu(A_1\cap A_2)=\mu(A_1\cap A_2)
  \\
  \mu(A_2)&=\mu(A_2-A_1)+\mu(A_1\cap A_2)=\mu(A_1\cap A_2)
\end{aligned} $$

$\bar{\mu}$ is do well defined. $\mu^*$ is auto $\sigma$ additive since so is $\mu$ and is easy to check that all $\mu^*$ null set is $\mu$ null set. 

:::


### Specification of measures



::: {.theorem  name=""}

Let $(\Omega,\mathcal{A})$ be a measurable space. Let $\mu,\nu$ be measures on it with $\mu(\Omega)=\nu(\Omega)<\infty$. If $\mu,\nu$ agree on a $\pi$ system generating $\mathcal{A}$, then $\mu,\nu$ are identical.
>

:::



::: {.proof}

Let $\mathcal{C}$ be the  $\pi$ system generating $\mathcal{A}$ and $\mu(A)=\nu(A)$ for every $A\in \mathcal{C}$. Consider $\mathcal{D}=\{A\in \mathcal{A}:\mu(A)=\nu(A)\}$ which satisfies $\mathcal{C\subset D\subset \Omega}$. Then we need to prove that $\mathcal{D}$ is a $\lambda$ system:

- $\Omega\in \mathcal{D}$ by the assumption.
- Let $A,B\in \mathcal{D}$ and $B\subset A$. Then $\mu(A-B)=\mu(A)-\mu(B)=\nu(A)-\nu(B)=\nu(A-B)$, so $A-B\in \mathcal{D}$ 
- Let $(A_n)\uparrow A$ and $(A_n)\subset \mathcal{D}$, then $\mu(A_n)\uparrow \mu(A)$, $\nu(A_n)\uparrow \nu(A)$, since $\mu(A_n)=\nu(A_n)$ for every $n$, so $\mu(A)=\nu(A)$.  

So $\mathcal{D}$ is a d-system. It follows that $\sigma(\mathcal{C})=\mathcal{A}\subset \mathcal{D}$.

:::

As consequence, we have


::: {.corollary  name=""}

Suppose $\mu$ and $\nu$ are probability measures on space on $(\overline{\mathbb{R}},\mathcal{B})$ then $\mu=\nu$ iff $\mu[-\infty,r]=\nu[-\infty,r],\forall r\in \mathbb{R}$.

:::


::: {.proof}

Note $\{[-\infty,r]:r\in \mathbb{R}\}$ is a $\pi$ system and generates $\mathcal{B}$.

:::

### Atomic and diffuse measure



::: {.definition  name=""}

Let $(\Omega,\mathcal{A},\mu)$ be a measure space where $\mathcal{A}$ contains all the singletons: $\{x\}\in \mathcal{A}$ for every $x\in \Omega$ (it's true for all the standard measure).

A point $x$ is said to be an **atom** if $\mu(\{x\})>0$, the measure is said to be **diffuse** if it has no atoms. It is said to be **purely atomic** if the set $D$ of its atoms is countable and $\mu(\Omega-D)=0$.

:::


::: {.lemma  name=""}

A s-finite measure has at most countable many atoms.

:::


::: {.proof}

It suffices to show that when $\mu$ is finite. Suppose $A_n=\{x:\mu \{x\}>\frac{1}{n}\}$ and $A$ consists all atoms, then the claim follows from $A_n \nearrow A$ and $|A_n|\le n\mu(\Omega)$ as $A=\bigcup_{n}A_n$.

:::




::: {.theorem  name=""}

Let $\mu$ be a s-finite measure on $(\Omega,\mathcal{A})$. Then $\mu=\nu+\lambda$ where $\lambda$ is a diffuse measure and $\nu$ is purely atomic.

:::


::: {.proof}

Let $D$ be set of all atoms and define
$$ 
\begin{aligned}
	\lambda(A)=\mu(A-D)\\
	\nu(A)=\mu(A\cap D)
\end{aligned}
$$
for all $A\in \mathcal{A}$. Clearly, $\lambda+\nu=\mu$. Then

- $\lambda$ is diffuse as $\lambda \{x\}=0$ for all $x\in D$ and if $\lambda \{x\}>0$, it must be $x\in D$.
- $\nu$ is purely atomic as $D_\nu = D$ clearly and $\nu(\Omega-D)=\mu(\emptyset)=0$.



:::



## Integration

Let $f$ be Borel measurable on $(\Omega,\mathcal{A},\mu)$. The **integral** of $f$ w.r.t $\mu$ is denoted by
$$ \int f ( \omega ) \mu ( d \omega ) = \int f d \mu = \int f $$

1. If $f=\sum_1^n a_i \bm{\mathbf{1}}_{A_i}$ with $a_i\ge 0$,
$$ \int f d \mu = \sum _ { 1 } ^ { n } a _ { i } \mu \left( A _ { i } \right) $$

2. 
    If $f\ge 0$,define

    $$ \int fd\mu=\lim_n \int f_nd\mu $$ 

    where $f_n$ are simple functions and $f_n \nearrow f$.

1. 
    For any $f$, we have $f=f^{+}-f^{-}$, define 
    
    $$ \int f d \mu : = \int f ^ { + } d \mu - \int f ^ { - } d \mu $$ 

2. 
    $f$ is said to be integrable w.r.t. $\mu$ if $\int|f|d\mu<\infty$. We denote all integrable functions by $L^1$.




::: {.proposition  name=""}

(**Integral over sets**)  
$$ \int _ { A } f d \mu = \int f \bm{\mathbf{1}} _ { A } d \mu = \int f ( \omega ) \bm{\mathbf{1}} _ { A } ( \omega ) \mu ( d \omega ) $$

(**Absolute integrability**). $\int f$ is finite iff $\int|f|$ is finite.

**(Linearity)** If $f,g,a,b\ge 0$ or $f,g\in L^1$
$$ \int(af+bg)=a\int f+b\int g $$

**($\sigma$ additivity over sets)** If $A=\sum_{i=1}^\infty A_i$, then
$$ \int _ { A } f = \sum _ { i = 1 } ^ { \infty } \int _ { A _ { i } } f $$

**(Positivity)** If $f\ge 0$ a.s., then $\int f\ge 0$

**(Monotonicity)** If $f_1\le f\le f_2$ a.s., then $\int f_1\le \int f 
\le \int f_2$

**(Mean value theorem)** If $a\le f \le b$ a.s., then 

$$ a\mu(A)\le \int _Af\le b\mu(A) $$

**(Modulus inequality)**: $|\int f|\le \int |f|$

:::

### Monotone Convergence Theorem


::: {.theorem #MCT name="Monotone Convergence Theorem"}

Suppose nonnegative $f_n\nearrow f$ a.e., then $\int f_n d\mu \nearrow \int f d\mu$.

:::



::: {.theorem name=""}

We may ignore a null set then $f_n \nearrow f$ and their integration still equal. Note $\int f_n d\mu \le \int fd\mu$, $\int f_n d\mu$ must converges to some $L\le \int f$. Then we show $L\ge \int f$. 

Let $s=\sum a_i \chi_{E_i}$ be simple function and $s\le f$. Let $A_n=\{x:f_n(x)\ge cs(x)\}$ where $c\in(0,1)$, then $A_n \nearrow X$. For each $n$

$$ \begin{aligned}
    \int f_n\ge \int_{A_n} f_n &\ge c\int_{A_n} s
    \\&= c\int_{A_n} \sum a_i\chi_{E_i}
    \\&=c \sum a_i\mu(E_i\cap A_n)
    \\&\nearrow c\int s
\end{aligned} $$

hence $L\ge c\int s\implies L\ge \int s\implies L= \lim L\ge \lim \int s_n=\int f$. 

:::




::: {.lemma #fatou name="Fatou's Lemma"}

If  $f_n\ge 0$ a.e. then
$$ \int  \left( \liminf_ { n } f _{ n } \right) \leq \liminf_ { n } \int  f _ { n } $$

:::



::: {.proof}

Suppose $g_n=\inf_{i\ge n}f_i$ and recall that $\lim g_n=\liminf f_n$. Clearly $g_n\le f_i \forall i\ge n$  hence 

$$ \int g_n \le \inf_{i\ge n}\int f_i $$

Take limit both side and note $g_n$ is increasing:

$$ \lim \int g_n=\int \lim g_n=\int \liminf f_n\le \liminf \int f_n $$

:::




::: {.theorem #DCT name="Dominated Convergence Theorem"}

Suppose $f_n(x)\to f(x) \forall x$, and there exists a nonnegative integrable $g$ s.t. $|f_n(x)|\le g(x)$(then we get $f_n\in L^1$ immediately), then

$$ \lim \int f_n d\mu=\int f d\mu $$

:::



::: {.proof}


Since $f_n+g\ge 0$

$$ \int f+\int g=\int f+g\le \liminf \int f_n+g=\liminf \int f_n+\int g $$

thus $\int f\le \liminf_{n\to \infty}\int f_n$. Similarly, we can get $\int f\le \liminf_{n\to \infty}\int f_n$ from $g-f_n\ge 0$. 


:::


::: {.theorem  name="Tonelli's Throrem"}

If $\sum_{1}^\infty \int |f_n|<\infty$, then

$$ \int  \left( \sum _{ i = 1 } ^ { \infty } f_ { n } \right) = \sum _{ i = 1 } ^ { \infty } \int  f_ { n } $$


:::

::: {.proof}

Let $g_k=\sum_1^k |f_n|,g=\sum_1^\infty|f_n|,h_k=\sum_1^k f_n,h=\sum_1^\infty f_n$. Then $g_k \nearrow g$, by MCT, we have

$$ \int g=\lim \int g_k=\lim \sum_1^k \int |f_n|= \sum_1^\infty \int |f_n|<\infty$$

Hence we may let $g$ dominate $h_k$ and get

$$ \int h=\lim \int h_k= \sum_1^\infty \int f_n$$

:::



### Criteria for zero a.e.


::: {.lemma #markov name="Markov inequality"}

Let $A=\{x\in \Omega: f(x)\ge M\}$, then 
$$
\mu(A)\le \frac{\int f}{M} 
$$


:::


::: {.proof}

$$ \mu(A)=\int \chi_A=\int_A \chi_A \le \int_A \frac{f}{M}\le  \int_X \frac{f}{M}=\frac{\int f}{M}$$

:::

Suppose $f$ is measurable and non-negative and $\int fd\mu=0$. Then $f=0$ a.e.


::: {.proof}

By lemma \@ref(lem:markov) and define $A_M=\{x\in \Omega:f(x)\ge M\}$. Consequently, $\mu(A_M)=0$ for all $M > 0$, note $A_{\frac{1}{n}}\nearrow A_0$:

$$ A_0=\bigcup_1^\infty A_{\frac{1}{n}}\implies \mu(A_0)=\sum 0=0 $$

Hence $f=0$ a.e. 

:::


::: {.lemma  name=""}

Suppose $f$ is integrable and $\int_A f=0$ for all measurable $A$. Then $f=0$ a.e.

:::


::: {.proof}

Suppose $A_n=\{x\in \Omega:f(x)\ge \frac{1}{n}\}$, then
$$ 
0=\int_{A_n} f \ge \frac{\mu(A_n)}{n}\xRightarrow{}\mu(A_n)=0
$$

thus $\mu\{x\in \Omega:f(x)>0\}=0$. Similarly, $\mu\{x\in \Omega:f(x)<0\}=0$ and the claim follows.

:::



::: {.theorem  name=""}

Suppose $f:\mathbb{R} \to \mathbb{R}$ is integrable and $\int_a^x f=0$ for all $x$, then $f=0$ a.e.

:::



::: {.proof}

For any interval $I=[c,d]$,

$$ \int_i f=\int_a^d f-\int_a^c f=0 $$

Then the integral is $0$ for finite disjoint union of intervals from additivity. Note open sets $G$ can be written as countable union of disjoint open intervals $G=\sum_1^\infty I_i=\lim \sum I_n\implies$

$$\int_G f=\int f\chi_G=\int f\sum_1^\infty \chi_{I_i}=\int \lim f\sum \chi_{I_i}=\lim \int f\sum \chi_{I_i}=0 $$

If $G_n\searrow H$, then

$$ \int_H f = \int f\chi_H=\int \lim f\chi_{G_n}=\lim\int f\chi_{G_n}=\lim \int_{G_n} f=0 $$

where we apply DMT twice and take dominated function $g=|f|$.

Finally, for any borel measurable set $E$, there is $G_\delta\supset E$ and $m(G_\delta-E)=0$, then

$$ \int_E f=\int f\chi_E=\int f\chi_{G_\delta}=\int_{G_\delta} f=0 $$


:::

### Characterization of the integral

::: {.theorem  name=""}

Let $(\Omega,\mathcal{A})$ be a measurable space and $L:\mathcal{A}\to \overline{\mathbb{R}}_{+}$, then there is a unique measure $\mu$ on $(\Omega,\mathcal{A})$ s.t. $L(f)=\int f$ for every $f\in \mathcal{A}_+$ iff:

-  $f=0\implies L(f)=0$ 
- $f,g\in \mathcal{A}_+$ and $a,b\in \R_+\implies L(af+bg)=aL(f)+bL(g)$
- $(f_n)\subset \mathcal{A}_+$ and $f_n \nearrow f\implies L(f_n)\nearrow L(f)$

:::

::: {.proof}

$\xRightarrow{}$ follows from the definition and properties of integral. For $\xLeftarrow{}$, let there is a function $L$ satisfies above conditions and give a $\mu$ and let $\mu (A)=L(1_A)$, then use those conditions we can prove that $\mu$ is a measure a $(\Omega,\mathcal{A})$.

:::

## Transforms and Indefinite integral

::: {.definition  name="Image measure"}

let $(F,\mathcal{F})$ and $(E,\mathcal{E})$ be measurable spaces. Let $\nu$ be a measure on $(F,\mathcal{F})$ and let $h:F\to E$ be measurable relative to $\mathcal{F}$ and $\mathcal{E}$, then define a mapping $\nu\circ h^{-1}(B)=\nu(h^{-1}B),\ B\in \mathcal{E}$.  
Then $\nu\circ h^{-1}$ is a measure on $(E,\mathcal{E})$, which is called the image of $\nu$ under $h$.

:::

::: {.theorem  name=""}

For every $f\in \mathcal{E_+}$, we have $(\nu\circ h^{-1})f=\nu(f\circ h)$.

:::

::: {.proof}

Let $L:\mathcal{E}_+\to \overline{\R}_+$ by letting $L(f)=\nu(f\circ h)$. Then as the property of $\nu(f\circ h)$, $f$ satisfies the properties of integral characterization theorem. Then, $L(f)=\mu f$ for some unique measure $\mu$ on $(E,\mathcal{E})$. And 
$$ \mu (B)=L(1_B)=\nu(1_B \circ h)=\nu(h^{-1}B), \qquad B\in \mathcal{E} $$


:::

::: {.definition  name="Standard measurable space"}

Let $(E,\mathcal{E})$ and $(F,\mathcal{F})$ be measurable spaces let $f$ be a bijection from $E$ onto $F$, then  $f$ is called an isomorphism of $(E,\mathcal{E})$ and $(F,\mathcal{F})$ iff $f$ is $\mathcal{E}$-measurable and $f^{-1}$ is $\mathcal{F}$-measurable.  
A measurable space $(E,\mathcal{E})$ is said to be a standard measurable space if it is isomorphic to $(F,\mathcal{B}_F)$ for some Borel set $F$ of $\R$.

:::

::: {.definition  name=""}

Let $\mu$ be a measure on $(E,\mathcal{E})$. It is said to be finite if $\mu (E)\lt \infty$, then $\mu (A)\lt\infty$ for every $A\subset E$.  
It is called a probability measure if $\mu (E)=1$.  
It is said to be $\sigma$-finite if there exists a measurable partition $(E_n)$ of $E$ s.t. for each $n$, $\mu (E_n)\lt \infty$.  
It is said to be $\Sigma$-finite if there exists a sequence of finite measures $(\mu_n)$ s.t. $\mu =\sum_{n}^{} \mu_n$.

:::

::: {.theorem  name=""}

If a measure is $\sigma$-finite then it must be  $\Sigma$-finite.

:::

::: {.proof}

Assume that there is a measure $\mu$ on $(E,\mathcal{E})$ is $\sigma$-finite, where there is a $(E_n)\subset \mathcal{E}$ s.t. $\bigcup_{n} E_n=E$. Then give $(\mu_n)$ s.t. for each $n$, 
$$ \begin{cases}
	\mu_n(E_n)=\mu(E_n) \\
	\mu_n(E-E_n)=0
\end{cases} $$
then $\mu_n(E)=\mu_n(E_n)=\mu (E_n)$, so a $\sigma$-finite measure $\mu$ is a $\Sigma$-fnite measure.

:::

Let $(E,\mathcal{E},\mu)$ be a measure space. Let $p$ be a positive $\mathcal{E}$-measurable function. Define: 
$$ \nu(A)=\mu (p 1_A)=\int_A \mu (dx)p(x),\qquad A\in \mathcal{E}$$


::: {.theorem  name=""}

$\nu$ is a measure on $(E,\mathcal{E})$.

:::

::: {.proof}

- Let  $A,B$ be disjoint sets in $E$, then $\mu (p 1_A)+\mu (p 1_B)=\mu (p 1_{A\cup B})$  
- $\mu (p 1_\varnothing)=0$

:::

::: {.theorem  name=""}

Fix a $p \in \mathcal{E_+}$, and give a measure $\mu$ on $(E,\mathcal{E})$, then there must be a measure $\nu$ satisfying $\nu f=\mu (pf)$ for every $f\in \mathcal{E_+}$.

:::

::: {.proof}

Let $L(f)=\mu (pf)$. Check $L$ :
- $f=0\implies L(f)=0$ 
- Give $f,g\in \mathcal{E_+}$ and $a,b\in \mathbb{R}_+\implies L(af+bg)=\mu (p(af+bg))$ and based on the arithmetic rules on $\mathbb{R}$ and the linearity of $\mu$, $L(af+bg)=aL(f)+bL(g)$ 
- Give $(f_n)\subset \mathcal{E_+}$ and $f_n \nearrow f$, $L(f_n)=\mu (pf_n)$ and as $f_n \nearrow f$, $pf_n \nearrow pf$ so $\lim L(f_n)=\lim \mu (pf_n)$. According to the monotone converging theorem, $\lim \mu (pf_n)=\mu (pf)=L(f)$ 

So there exists a $\nu$ satisfying $\nu f=L(f)=\mu (pf)$.

:::

Written above result in an explicit notation: 
$$ 
\int_E \nu(dx)f(x)=\int_E \mu (dx)p(x)f(x)
$$
then we can change the $\nu(dx)$ with $\mu (dx)p(x)$ where $x\in E$, $p\in \mathcal{E_+}$.


::: {.definition  name="absolutely continuous"}

Let $\nu$ and $\mu$ be measures on a measurable space  $(E,\mathcal{E})$. Then $\nu$ is said to be absolutely continuous respect to $\mu$ if for any set $A\in \mathcal{E}$, $\mu (A)=0\implies\nu(A)=0$.

:::

::: {.theorem  name=""}

If $\nu$ satisfies the conditions $\nu f=\mu(pf)$ for every $f\in \mathcal{E_+}$, then $\nu$ is absolutely continuous with respect to $\mu$.

:::
 

::: {.proof}


Let $\mu (A)=0$, then we need to prove that  $\mu (p \bm{\mathbf{1}}_{A})=0$: 
- Let $p$ is a simple function with a cononical form on $E$ with $p=\sum_{i=1}^{n} a_i \bm{\mathbf{1}}_{B_i}$ and as $(B_i)$ is a partition, $(B_i\cap A)$ is a partition of $A$, noted as $(A_i)$. Then 
$$ 
\mu (p \bm{\mathbf{1}}_{A})=\int_A pd\mu =\sum_{i=1}^{n} a_i \mu (A_i)
$$ 
As $\mu (A)=0$ and $A=\bigcup_{i=1} ^{n}A_i$, $\mu (A)=\sum_{i=1}^{n} \mu (A_i)$, so $\mu (A_i)=0$ for every $i$. So $\mu (p \bm{\mathbf{1}}_{A})=0$.
- Let $p\in \mathcal{E_+}$, give $(p_n)$ s.t. $p_n \nearrow p$ where $p_n=d_n\circ p$. Then  $p_n \bm{\mathbf{1}}_{A}\nearrow p \bm{\mathbf{1}}_{A}$ and for every $n$, $\mu (p_n \bm{\mathbf{1}}_{A})$ holds. So: 
$$ 
\mu (p \bm{\mathbf{1}}_{A})=\mu (\lim p_n \bm{\mathbf{1}}_{A})=\lim \mu (p_n \bm{\mathbf{1}}_{A})=0
$$
according to the monotone converging theorem, so $\nu$ is absolutely continuous respect to $\mu$


:::

::: {.theorem  name="Radon Nikodym Theorm"}

Suppose that $\mu$ is $\sigma$-finite and $\nu$ is absolutely continuous with repect to $\mu$. Then there exists a positive $\mathcal{E}$-measurable function $p$ s.t. $\nu f=\mu (pf)$ on $E$ for every $f\in \mathcal{E_+}$.  
Moreover, $p$ is unique above, if there is a $q\in \mathcal{E_+}$, then $q=p$ a.e. 

:::

Notice that Randon Nikodym theorem is the converse of the theorem before it.  
The proof of the Randon Nikodym theorem is not able to show here now.


::: {.definition  name="transition kernal"}

Let  $(E,\mathcal{E})$ and $(F,\mathcal{F})$ be measurable spaces. Let $K$ be a mapping from $E\mathcal{\times F}$ into $\overline{\mathbb{R}}_+$. Then, $K$ is called a transition kernal from $(E,\mathcal{E})$ into $(F,\mathcal{F})$ if:
- the mapping $x\mapsto K(x,B)$ is $\mathcal{E}$-measurable for every set $B\in \mathcal{F}$ 
- the mapping $B\mapsto K(x,B)$ is a measure on $(F,\mathcal{F})$ for every $x\in E$

:::

For example, if $\nu$ is a finite measure on $(F,\mathcal{F})$, and $k$ is a positive function on $E\times F$ that is $\mathcal{E\times F}$-measurable, then 
$$ 
K(x,B)=\int_B \nu(dy)k(x,y), \qquad x\in E, B\in \mathcal{F}
$$
when fix $x\in E$, $K(x,B)=\nu(k(x,y)\bm{\mathbf{1}}_{B})=\mu (B)$ for some $\mu$ which is the measure on $(F,\mathcal{F})$.  
when fix $B\in \mathcal{F}$, $K(x,B)=f(x)=$



::: {.theorem  name=""}

Let $K$ be a transition kernal from  $(E,\mathcal{E})$ into $(F,\mathcal{F})$. Then 
$$ 
Kf(x)=\int_F K(x,dy)f(y), \qquad x\in E,
$$
defines a function  $Kf\in \mathcal{E_+}$ for every $f\in \mathcal{F_+}$. 
$$ 
\mu K(B)=\int_E \mu (dx)K(x,B), \qquad B\in \mathcal{F},
$$
defines a measure $\mu K$ on $(F,\mathcal{F})$ for each measure  $\mu$ on $(E,\mathcal{E})$.
and  
$$ 
(\mu K)f=\mu (Kf)=\int_E \mu (dx)\int_F K(x,dy)f(y)
$$
for every measure $\mu$ on $(E,\mathcal{E})$ and function $f$ in $\mathcal{F_+}$.

:::

::: {.proof}



:::

::: {.theorem  name=""}

Let $f\in \mathcal{E\times F}$, then $x\mapsto f(x,y)\in \mathcal{E}$ for each  $y\in F$ and $y\mapsto f(x,y)\in \mathcal{F}$ for each $x\in E$.

:::






















