# Measure Theory


::: {.theorem  name="monotone class theorem"}

Let $\mathcal{H}$ be a class of bounded functions from $S$ to $\mathbb{R}$ s.t. 

1.  $\mathcal{H}$ is a vector space over $\mathbb{R}$.
2.  constant function $1$ is an element in $\mathcal{H}$.
3.  if $(f_n)$ is a sequence of non-negative functions in $\mathcal{H}$ s.t. $f_n\nearrow f$ where $f$ is a bounded functions on $S$, then $f\in \mathcal{H}$.

If $\mathcal{H}$ contains all of the indicator functions of some $\pi$-system $\mathscr{P}$, then $\mathcal{H}$ contains every bounded  $\sigma(\mathscr{P})$-measurable function on  $S$.

:::

::: {.proof}

Define
$$ 
\mathscr{D}=\left\{D\subset S:\bm{\mathbf{1}}_{D}\in \mathcal{H}\right\}
$$
Note that  $S\in \mathscr{D}$, and if $A,B\in \mathscr{D}$ and $A\subset B$, then $\bm{\mathbf{1}}_{B-A}=\bm{\mathbf{1}}_{B}-\bm{\mathbf{1}}_{A}\in \mathcal{H}$ since the property of vector space, $\mathscr{D}$ is a $d$-system.
By hypothesis, $\mathscr{D}\supset \mathscr{P}$, so $\mathscr{D}\supset \sigma(\mathscr{P})$.

Suppose $f$ is a $\sigma(\mathscr{P})$-measurable function s.t. for some $K\in \mathbb{N}$,
$$ 
0\le f(s)\le K \mathop{\text{ for every }}s \in S
$$
then define:
$$
f_n(s)=\sum_{i=0}^{K 2^{n}} \frac{i}{2^{n}}\bm{\mathbf{1}}_{D(n,i)}(s)
$$
where
$$ 
D(n,i)=\left\{s:i 2^{-n}\le f(s)\lt (i+1)2^{-n}\right\}
$$
Note that $f_n\nearrow f$, then $D(n,i)\in \sigma(\mathscr{P})$ so $\bm{\mathbf{1}}_{D(n,i)}\in \mathcal{H}$, so $f\in \mathcal{H}$.

:::

::: {.definition  name="product $\sigma$-algebra"}

Let $\mathcal{F}_{}=\mathcal{F}_{1}\times \mathcal{F}_{2}$, where $(S_1,\mathcal{F}_{1}),(S_2,\mathcal{F}_{2})$ be measurable spaces. Then $\mathcal{F}_{}$ is the  $\sigma$-Algebra generated by the coordinate mapping, i.e. generated by $\rho_1$ and $\rho_2$ where $\rho_1(s_1,s_2)=s_1,\rho_2(s_1,s_2)=s_2$.

Thus $\mathcal{F}_{}$ is generated by the sets of the form $\rho_1(B_1)=B_1\times S_2$ where $B_1\in \mathcal{F}_{1}$. 

:::

Note that $(A_1\times A_2)\cap (B_1\times B_2)=(A_1\cap B_1)\times (A_2\cap B_2)$, then
$$ 
\mathscr{P}=\left\{B_1\times B_2:B_1\in \mathcal{F}_{1},B_2\in \mathcal{F}_{2}\right\}
$$
is a $\pi$-system. Now consider the $\sigma(\mathscr{P})$. $(B_1\times S_2)\cap (S_1\times B_2)=B_1\times B_2$, so $\sigma(\mathscr{P})=\sigma(\mathscr{B})$ where
$$ 
\mathscr{B}=\left\{B_{1}\times S_2:B_1\in \mathcal{F}_{1}\right\}\cup \left\{S_1\times B_2:B_2\in \mathcal{F}_{2}\right\}
$$
which means $\sigma(\rho_1,\rho_2)=\sigma(\mathscr{P})$.


::: {.lemma  name=""}

Let $\mathcal{H}$ denote the class of functions $f:S\to \mathbb{R}$ that are $\mathcal{F}_{}$-measurable and bounded  s.t. 

-   For each $s_1\in S_1$, the mapping $s_2\mapsto f(s_1,s_2)$ is $\mathcal{F}_{2}$-measurable.
-   For each $s_2\in S_2$, the mapping $s_1\mapsto f(s_1,s_2)$ is $\mathcal{F}_{1}$-measurable.

Then $\mathcal{H}=\mathcal{B}_{\mathcal{F}_{}}$ where $\mathcal{B}_{\mathcal{F}_{}}$ denotes the bounded $\mathcal{F}_{}$-measurable function space.

:::

::: {.proof}

Define 
$$ 
\mathscr{P}=\left\{B_1\times B_2:B_1\in \mathcal{F}_{1},B_2\in \mathcal{F}_{2}\right\}
$$
If $A\in \mathscr{P}$ then $\bm{\mathbf{1}}_{A}\in \mathcal{H}$. Then by the monotone class theorem, $\mathcal{H}\supset \mathcal{B}_{\sigma(\mathscr{P})}=\mathcal{B}_{\mathcal{F}_{1}\times \mathcal{F}_{2}}$

:::

Suppose that $\mu_{i}$ is a finite measure on $(S_{i},\mathcal{F}_{i})$. Define:
$$ 
I_1^{f}(s_1)=\int_{S_2}f(s_1,s_2)d\mu_2, \\
I_2^{f}(s_2)=\int_{S_1}f(s_1,s_2)d \mu_1
$$


::: {.lemma  name=""}

Let $\mathcal{H}$ be the class of elements in $\mathcal{B}_{\mathcal{F}_{}}$ s.t. 

-   $I_1^{f}\in \mathcal{B}_{\mathcal{F}_{1}}$ 
-   $I_2^{f}\in \mathcal{B}_{\mathcal{F}_{2}}$ 
-
    $$ 
    \int_{S_1}I_1^{f}(s_1)d \mu_1=\int_{S_2}I_2^{f}(s_2)d\mu_2
    $$

Then $\mathcal{H}=\mathcal{B}_{\mathcal{F}_{}}$.

:::





























