# Stochastic Process

## Filtrations and stopping time


::: {.definition  name="filtration"}

A **filtration** on $(\Omega,\mathcal{F},P)$ is a family of  $\sigma$-Algebra $\left\{\mathcal{F}_t:t\in \mathbb{R}_+\right\}$ satisfying:
$$ 
\mathcal{F_s\subset F_t\subset F}\mathop{\text{ for all }}0\le s\le t\lt \infty
$$
we add the definition:
$$ 
\mathcal{F}_\infty=\sigma\left(\bigcup_{0\le t\lt \infty} \mathcal{F_t}\right)
$$
Notice that $\mathcal{F}_\infty\subset \mathcal{F}$ and no need to equal to $\mathcal{F}$.

:::

Then we complete the filtration. Let 
$$
\overline{\mathcal{F}}_t=\left\{B\in \mathcal{F}:\mathop{\text{ there exists $A\in \mathcal{F}_t$ s.t. }}P(A\triangle B)=0\right\}
$$
Notice that $\overline{\mathcal{F}}_t$ is also a $\sigma$-Algebra and it contains all the $\mathcal{F}$-measurable $P$-null set.


::: {.definition  name="stochastic process"}

A **stochastic process** is a collection of random variables $\left\{X_{i}:i\in I\right\}$ indexed by an arbitrary index set $I$ and all defined on the same probability space $(\Omega,\mathcal{F},P)$.

Let $X=\left\{X_t:t\in \mathbb{R}_+\right\}$ be a process on $(\Omega,\mathcal{F},P)$. Then it is convenient to regard $X$ as a function on $\mathbb{R}_+\times \Omega$ through the formula $X(t,\omega)=X_t(\omega)$ for $\omega\in \Omega$ and $t\in \mathbb{R}_+$.

:::

::: {.definition  name="Adapted"}

A process $X=\left\{X_t:t\in \mathbb{R}_+\right\}$ is adapted to the filtration $\left\{\mathcal{F}_t\right\}$ if $X_t$ is $\mathcal{F_t}$-measurable for each $t\in [0,\infty)$. The smallest filtration to which $X$ is adapted is the filtration it generates, i.e. 
$$ 
\mathcal{F}_t^{X}=\sigma\left\{X_s:0\le s\le t\right\}
$$

:::

::: {.definition  name="measurability of a process"}

A process $X$ is measurable if $X$ is $\mathcal{B}_{\mathbb{R}_+}\times \mathcal{F}$ measurable as a function from $\mathbb{R}_+\times \Omega\to \mathbb{R}^{d}$.

Furthermore, $X$ is **progressively measurable** if the restriction of the function $X$ to $[0,T]\times \Omega$ is  $\mathcal{B}_{[0,T]}\otimes \mathcal{F}_T$ measurable for each $T$.

:::




















