---
title: 
author:
  - Xie zejian
bibliography: references.bib
output:
  bookdown::pdf_document2:
    includes:
      in_header: preamble.tex
---

```{=latex}
\newcommand{\lt}{<}
\newcommand{\gt}{>}
\newcommand{\R}{\mathbb{R}}
\newcommand{\Reals}{\mathbb{R}}
\newcommand{\Real}{\mathbb{R}}
\newcommand{\N}{\mathbb{N}}
\newcommand{\Q}{\mathbb{Q}}
\newcommand{\sub}{\subset}
\newcommand{\subsets}{\subset}
\newcommand{\exist}{\exists}
```

::: {.definition  name=""}

- 
    A set $X$ is a **vector space** over $\mathbb{K}$ if there exists two mappings: 
    $$ 
    \begin{aligned}
        (x,y)\in X\times X&\to x+y\in X \\
        (\alpha,x)\in \mathbb{K}\times X&\to \alpha x\in X 
    \end{aligned}
    $$ 
    there exists an element of $X$ denoted as $0$ s.t. $x+0=x$ for all $x\in X$, define $(-x)$ is a vector s.t. $x+(-x)=0$.
- 
    A **subspace** of a vector space $X$ over $\mathbb{K}$ is any subset of $X$ which is also a vector space over $\mathbb{K}$.
- 
    Let $Y$ and $Z$ be two subspace of $X$ then $X$ is said to be the **direct sum** of $Y,Z$ if any vector $x\in X$ can be written as 
    $$ 
    x=y+z \qquad y\in Y,z\in Z
    $$
    and such a decomposition is unique.
- 
    A subspace $B$ is called **subspace spanned by a subset $A$** of $X$ consisting of all finite linear combinations of vectors of $A$, i.e., $x\in B$ of the form $x=\sum_{i\in I}^{} \alpha_{i}a_{i}$ where the set $I$ is finite and $\alpha_{i}\in \mathbb{K}$, $a_{i}\in A$, we said that 
    $$ 
    B=\text{span}A
    $$
- 
    The **Hamel basis** in $X$ is any family $\{e_i\}_{i\in I}$ of vectors $e_{i}\in X$ satisfying:  
    + First, the family is linearly independent. It means that give any finite subfamily of $\{e_j\}_{j\in J}$ and any scalars $\alpha_j\in \mathbb{K},j\in J$ s.t. $\sum_{j\in J}^{} \alpha_j e_j=0$ then $\alpha_j=0,j\in J$.
    + Second, $\text{span}\{e_{i}\}_{i\in I}=X$.


:::


::: {.theorem  name=""}

Let $X\neq \{0\}$ be a vector space.  
- There exists a Hamel base of $X$ 
- Let $E,F$ be two Hamel bases of $X$. Then $\text{card}E=\text{card}F$.

:::

::: {.definition  name=""}

A vector space $X$ is finite-dimensional if there exists a finite Hamel basis of $X$, and its  **dimension** denoted as $\text{dim}X$.  
If $E$ is a Hamel base of $X$, then $\text{dim}X=\text{card}E$

:::

::: {.definition  name="norm"}

Let $X$ be a vector space over $\mathbb{K}$. A norm on $X$ is a mapping $\|\cdot \|:X\to \mathbb{R}$ with:
- $\|x\|\ge 0$ for all $x\in X$ and $\|x\|=0$ iff $x=0$
- $\|\alpha x\|=\|\alpha\|\|x\|$ for all $\alpha\in \mathbb{K},x\in X$ 
- $\|x+y\|\le \|x\|+\|y\|$ for all  $x,y\in X$

:::

::: {.definition  name="distance in normed vector space"}

Let $(X,\|\cdot\|)$ be a normed vector space, then the mapping $d:X\times X\to \mathbb{R}$ defined by $d(x,y)=\|x-y\|$ for all $x,y\in X$ is a **distance** on $X$.

:::

::: {.proof}

First we need to show that $\big\lvert\|x\|-\|y\|\big\rvert\le \|x-y\|$.  
Assume that $\|x\|\ge \|y\|$, then consider $\|x\|=\|x-y+y\|\le \|x-y\|+\|y\|$, so $\|x\|-\|y\|\le \|x-y\|$, as they all non-negative, $\big\lvert\|x\|-\|y\|\big\rvert\le \|x-y\|$ holds.  
- $d(x,y)=\|x-y\|\ge 0$ 
- $d(x,y)=0\implies \|x-y\|=0\implies x=y$ 
- $d(x,y)=\|x-y\|=\|y-x\|=d(y,x)$ 
- $d(x,y)\le d(x,z)+d(y,z)$, notice that  $\|x-z\|+\|z-y\|\ge \|(x-z)+(z-y)\|=\|x+y\|$, so for any $x,y,z\in X$, $d(x,y)\le d(x,z)+d(y,z)$  

So we find that  $d(x,y)=\|x-y\|$ is truly a metric on $X$, so $(X,d)$ is a metric topological space. It is also called the **norm topology** of $X$.

:::

::: {.theorem  name=""}

Let $X$ be a finite-dimensional vector space over $\mathbb{K}$, and let $(e_i)_{i=1}^{n}$ denote a basis of $X$ :

- 
    For each $p \in [1,\infty]$, the mapping $\|\cdot \|_p$ defined by: 
    $$ 
    \begin{aligned}
        x&=\sum_{i=1}^{n} x_{i}e_{i}\in X\to \|x\|_p=\bigg(\sum_{i=1}^{n} \lvert x_{i} \rvert ^{p}\bigg)^{1 /p} \qquad &&\text{if } p \in [1,\infty) \\
        x&=\sum_{i=1}^{n} x_{i}e_{i}\in X\to \|x\|_{\infty}= \max_{1\le i\le n}\lvert x_{i} \rvert &&\text{if }p=\infty
    \end{aligned}
    $$
    is a norm on $X$. 
- For each $p \in [1,\infty]$, the space $(X,\|\cdot\|_{p})$ is separable.


:::

::: {.theorem  name="Holder's and Minkowski's inequalities"}

- 
    Given a $p \in \mathbb{R}$ s.t. $p>1$, let the real number $q$ be defined by: 
    $$ 
    \frac{1}{p}+\frac{1}{q}=1 \qquad \text{hense }q>1
    $$
    and let $(x_{i})_{i=1}^{\infty}$ and $(y_{i})_{i=1}^{\infty}$ be two sequences of scalers satisfying 
    $$ 
    \sum_{i=1}^{\infty} \lvert x_{i} \rvert ^{p}\lt \infty \text{  and  } \sum_{i=1}^{\infty} \lvert y_{i} \rvert ^{q}\lt \infty
    $$
    Then the series $\sum_{i=1}^{\infty} \lvert x_{i}y_{i} \rvert$ converges and Holder's inequality holds:
    $$ 
    \sum_{i=1}^{\infty} \lvert x_{i}y_{i} \rvert\le \bigg(\sum_{i=1}^{\infty} \lvert x_{i} \rvert ^{p}\bigg) ^{1 /p} \bigg(\sum_{i=1}^{\infty} \lvert y_{i} \rvert ^{q}\bigg) ^{1/q}
    $$
- 
    Give a real number $p\ge 1$ s.t. 
    $$ 
    \sum_{i=1}^{\infty} \lvert x_{i} \rvert ^{p}\lt \infty \text{ and } \sum_{i=1}^{\infty} \lvert y_{i} \rvert ^{p}\lt \infty
    $$
    Then $\sum_{i=1}^{\infty} \lvert x_{i}+y_{i} \rvert ^{p}$ converges and Minkowski's inequality holds: 
    $$ 
    \bigg(\sum_{i=1}^{\infty} \lvert x_{i}+y_{i} \rvert ^{p}\bigg)^{1 /p}\le \bigg(\sum_{i=1}^{\infty} \lvert x_{i} \rvert ^{p}\bigg)^{1 /p}+\bigg(\sum_{i=1}^{\infty} \lvert y_{i} \rvert ^{p}\bigg) ^{1/p}
    $$
    

:::

::: {.proof}

1. 
    If $p>1$ and $\frac{1}{p}+\frac{1}{q}=1$, then 
    $$ 
    \alpha \beta\le \frac{\alpha ^{p}}{p}+\frac{\beta^{q}}{q}\qquad \text{for all $\alpha>0$, $\beta>0$}
    $$
    To see this, note that the convexity of exponential function implies that 
    $$ 
    e^{\theta r+(1-\theta)s}\le \theta e^{r}+(1-\theta)e^{s}
    $$
    for all $\theta\in (0,1)$ and $r,s \in \mathbb{R}$. Now let $\theta=\frac{1}{p},r=p\text{Log}\alpha,s=q\text{Log}\beta$, the first inequality is proved.  

2. 
    Let $\|x\|_{p}=(\sum_{i=1}^{\infty} \lvert x_{i} \rvert ^{p})^{1 /p}$ and $\|y\|_p=(\sum_{i=1}^{\infty} \lvert y_{i} \rvert ^{p})^{1 /p}$. Let $\alpha=\frac{\lvert x_{i} \rvert}{\|x\|_{p}}$ and $\beta=\frac{\lvert y_{i} \rvert}{\|y\|_p}$. Then as shown above: 
    $$ 
    \frac{\lvert x_{i}y_{i} \rvert}{\|x\|_p \|y\|_q}\le \frac{\lvert x_{i} \rvert ^{p}}{p(\|x\|_p)^{p}}+\frac{\lvert y_{i} \rvert ^{q}}{q(\|y\|_q)^{q}}
    $$
    for each $i\in \mathbb{N},i\ge 1$. Then take sum of above inequality: 
    $$ 
    \sum_{i=1}^{n} \bigg(\frac{\lvert x_{i}y_{i} \rvert}{\|x\|_{p} \|y\|_{q}}\bigg)\le \sum_{i=1}^{n} \bigg(\frac{\lvert x_{i} \rvert ^{p}}{p(\|x\|_{p})^{p}}+\frac{\lvert y_{i} \rvert ^{q}}{q(\|y\|_q)^{q}}\bigg)
    $$
    Notice that the right side of above:
    $$ 
    \|x\|_p=\bigg(\sum_{i=1}^{\infty} \lvert x_{i} \rvert ^{p}\bigg)^{1 /p}\implies \|x\|_p ^{p}=\sum_{i=1}^{\infty} \lvert x_{i} \rvert ^{p}
    $$
    similar of $\|y\|_{q}$, so
    $$ 
    \frac{\sum_{i=1}^{n} \lvert x_{i} \rvert ^{p}}{p(\|x\|_p)^{p}}=\frac{\sum_{i=1}^{n} \lvert x_{i} \rvert ^{p}}{p(\sum_{i=1}^{\infty} \lvert x_{i} \rvert ^{p})}\le \frac{1}{p}
    $$
    and the same as $\|y\|_q$, so the right side is less than $\frac{1}{p}+\frac{1}{q}=1$, so 
    $$ 
    \sum_{i=1}^{n} \lvert x_{i}y_{i} \rvert\le \|x\|_p \|y\|_q
    $$
    holds for every $n\in \mathbb{N}$ and take the limit $n\to \infty$, the holder's inequality holds.  

3. 
    Notice that $\frac{1}{p}+\frac{1}{q}=1\implies p+q=pq\implies p-1=\frac{p}{q}$.
    $$ 
    \begin{aligned}
        \sum_{i=1}^{n} (\lvert x_{i} \rvert+\lvert y_{i} \rvert)^{p}&=\sum_{i=1}^{n} \lvert x_{i} \rvert(\lvert x_{i} \rvert+\lvert y_{i} \rvert)^{p-1}+\sum_{i=1}^{n} \lvert y_{i} \rvert(\lvert x_{i} \rvert+\lvert y_{i} \rvert)^{p-1} 
        \\ &\le \bigg(\sum_{i=1}^{n} \lvert x_{i} \rvert^{p}\bigg)^{1 /p} \bigg(\sum_{i=1}^{n} (\lvert x_{i} \rvert+\lvert y_{i} \rvert)^{p}\bigg)^{1 /q}+\bigg(\sum_{i=1}^{n} \lvert y_{i} \rvert^{p}\bigg)^{1 /p} \bigg(\sum_{i=1}^{n} (\lvert x_{i} \rvert+\lvert y_{i} \rvert)^{p}\bigg)^{1/q} 
        \\ &=\bigg(\sum_{i=1}^{n} (\lvert x_{i} \rvert+\lvert y_{i} \rvert)^{p}\bigg)^{1 /q} \bigg(\bigg(\sum_{i=1}^{n} \lvert x_{i} \rvert^{p}\bigg)^{1 /p}+\bigg(\sum_{i=1}^{n} \lvert y_{i} \rvert^{p}\bigg)^{1/p}\bigg)
    \end{aligned}
    $$
    Notice that 
    $$ 
    \bigg(\sum_{i=1}^{n} \lvert x_{i}+y_{i} \rvert^{p}\bigg)^{1 /p}\le \bigg(\sum_{i=1}^{n} (\lvert x_{i} \rvert+\lvert y_{i} \rvert)^{p}\bigg)^{1 /p}
    $$
    so the Minkowski's inequality holds.

:::

::: {.proof}

Now we prove that $\|x\|_p$ satisfies the triangle inequality.  
$$ 
\|x+y\|_p \le \|x\|_p+\|y\|_p
$$
As shown above, when we prove Minkowski's inequality, before letting $n\to \infty$, we find that
$$ 
\bigg(\sum_{i=1}^{n} \lvert x_{i}+y_{i} \rvert^{p}\bigg)^{1 /p}\le \bigg(\sum_{i=1}^{n} \lvert x_{i} \rvert^{p}\bigg)^{1 /p}+\bigg(\sum_{i=1}^{n} \lvert y_{i} \rvert^{p}\bigg)^{1 /p}
$$
which means $\|x+y\|_p \le \|x\|_p +\|y\|_p$ holds.

Then we prove that $\|x\|_\infty$ is a norm.  
- $\|x\|_\infty=\max_{1\le i\le n}\lvert x_{i} \rvert \ge 0$
- $\|\alpha x\|_\infty=\max_{1\le i\le n}\lvert \alpha x_{i} \rvert=\lvert \alpha \rvert\|x\|_\infty$ 
- 
    $$ 
    \begin{aligned}
        \|x+y\|_\infty &= \max_{1\le i\le n}\lvert x_{i}+y_{i} \rvert\le \max_{1\le i\le n}\lvert x_{i} \rvert+\max_{1\le i\le n}\lvert y_{i} \rvert
        \\ &=\|x\|_\infty+\|y\|_\infty
    \end{aligned}
    $$
    

:::

Notice that when $p=2$, $\|x\|_2$ is the Euclidean distance between point $x\in \mathbb{R}^{n}$ and $0$, and the distance generated by $\|x\|_2$, $d(x,y)=\|x-y\|_2$ is the Euclidean distance between $x$ and $y$.

#### Space $\mathcal{C}(K;Y)$ with $K$ compact


::: {.theorem  name=""}

Let $K$ be a compact topological space and let $(Y,\|\cdot\|_{Y})$ be a normed vector space. Then $\mathcal{C}(K;Y)$ is a vector space with the norm $\|\cdot \|:\mathcal{C}(K;Y)\to \mathbb{R}$ :
$$ 
\|f\|_{\mathcal{C}}=\sup_{x\in K}\|f(x)\|_{Y}
$$
for each $f\in \mathcal{C}(K;Y)$. It is called the **sup-norm** on $\mathcal{C}(K;Y)$.

:::

::: {.proof}

Notice that $(Y,\|\cdot\|_{})$ is a metric space and a compact subset in a metric space is bounded and closed.  
-   $\sup\|f(x)\|_Y \lt \infty$ and $\sup\|f(x)\|_Y \ge 0$ 
-   $\sup\|\alpha f(x)\|_Y=\lvert \alpha \rvert \sup \|f(x)\|_Y$
-   $\sup\|f+g\|_Y \le\sup\|f\|_Y+\sup\|g\|_Y$

:::


::: {.definition  name="converge uniformly"}

A sequence $(f_n)_{n=1}^{\infty}$ of functions $f_n\in \mathcal{C}(K;Y)$ is said to **converge uniformly** if $\lim _{n\to \infty}\|f_n-f\|_{\mathcal{C}}=0$. It means
$$ 
\lim _{n\to \infty}\bigg(\sup_{x\in K}\|f_n(x)-f(x)\|_Y\bigg)=0
$$

:::

::: {.theorem  name=""}

Let $X$ be any set and let $(Y,\|\cdot\|_{Y})$ be a normed vector space. Then the set $\mathcal{B}(X;Y)$ of all bounded mappings $f:X\to Y$ i.e. $f(X)\subset Y$ is a bounded subset in $Y$ is a vector space and the function $\|\cdot \|_{\mathcal{B}}:\mathcal{B}(X;Y)\to \mathbb{R}$ defined by:
$$ 
\|f\|_{\mathcal{B}}=\sup_{x\in X}\|f(x)\|_{Y}
$$
is a norm on $\mathcal{B}(X;Y)$.

:::

::: {.proof}

Notice that a bounded function $f$ over $\mathbb{K}$, for any $\alpha\in \mathbb{K}$, $\alpha f$ is still bounded and for $f,g\in \mathcal{B}(X;Y)$, $f+g$ is still bounded.

It is easy to show that $\|f\|_{\mathcal{B}}$ is truly a norm on $\mathcal{B}(X;Y)$.

:::

::: {.definition  name="local uniform convergence"}

Let $X$ be a topological space and $Y$ be a normed vector space. Then a sequence $(f_n)_{n=1}^{\infty}$ of mappings $f_n:X\to Y$ is said to converge locally uniformly to a mapping $f:X\to Y$ as $n\to \infty$ if given any $x_0\in X$ there exists a neighborhood $V(x_0)$ of $x_0$ s.t. 
$$ 
\lim _{n\to \infty}\bigg(\sup_{x\in V(x_0)}\|f_n(x)-f(x)\|_{Y}\bigg)=0
$$

:::

Notice that local uniform convergence and uniform convergence implies the pointwise convergence.


::: {.theorem  name=""}

Let $X$ is a topological space and $Y$ be a normed vector space, let $(f_n)_{n=1}^{\infty}$ be a sequence of continuous mapping from $X$ to $Y$ that converges locally uniformly to a $f:X\to Y$, then $f$ is continuous on  $X$.

Moreover, if $f_n$ continuous at $x_0$ and they locally uniformly convergence to $f$ then $f$ is continuous at $x_0$.

:::

::: {.proof}

Assume that $f$ is continuous at $x_0$ which means give $\epsilon\gt 0$, there exists a neighborhood  $V(x_0)\in \mathcal{N}_{x_0}$ s.t. for every $x\in V(x_0)$, $\|f(x_0)-f(x)\|_{Y}\le \epsilon$.

Now suppose that $\epsilon\gt 0$ is given. As $(f_n)\to f$ locally uniformly. Then we can choose a $k\in \mathbb{N}$ s.t. for any $i\ge k$, we can find a neighborhood $V(x_0)$ s.t. for any $x\in V(x_0)$, 
$$
\sup_{x\in V(x_0)}\|f_i(x)-f(x)\|_{Y}\le \epsilon /3
$$
and as all $f_n:n\in \mathbb{N}$ is continuous at $x_0$, so we can find a neighborhood of $x_0$, $U(x_0)\in \mathcal{N_{x_0}}$ s.t. for any $x\in U(x_0)$, 
$$ 
\sup_{x\in U(x_0)}\|f_{i}(x)-f_{i}(x_0)\|_{Y}\le \epsilon /3
$$
Then we consider the set $W(x_0)=U(x_0)\cap V(x_0)\in \mathcal{N}_{x_0}$, for any $x\in W(x_0)$ :
$$ 
\begin{aligned}
    \|f(x)-f(x_0)\|_{Y}&\le \|f(x)-f_{i}(x)\|_{Y}+\|f_{i}(x)-f_{i}(x_0)\|_{Y}+\|f_{i}(x_0)-f(x_0)\|_{Y} \\
    &\le \epsilon /3 + \epsilon /3 +\epsilon /3 \\ 
    &= \epsilon
\end{aligned}
$$
so if $(f_n)\to f$ locally uniformly, and $f_n$ is continuous at $x_0$ for every $n$ then $f$ is continuous at $x_0$. Moreover, if $f_n$ is continuous at every $x\in X$ i.e. continuous at $X$, then $f$ is continuous at $X$.

:::

#### $\ell^{p}$ space and $L^{p}$ space


::: {.definition  name="$\ell^{p}$ space"}

 $\ell^{p}$ space is a normed vector space of all the infinite sequences $x=(x_{i})_{i=1}^{\infty}$ of scalars $x_{i}\in \mathbb{K}$ that satisfy: 
$$ 
\begin{aligned}
    \sum_{i=1}^{\infty} \lvert x_{i} \rvert^{p}\lt \infty \qquad &\mathop{\text{if }}p \in [1,\infty) \\ 
    \sup_{i\ge 1}\lvert x_{i} \rvert \lt \infty \qquad &\mathop{\text{if }} p = \infty
\end{aligned}
$$
For each $p \in [1,\infty]$, the set $\ell^{p}$ is a vector space with the norm $\|\cdot \|_{p}$ :
$$ 
\begin{aligned}
    x= (x_{i})\in \ell^p & \to \|x\|_{p}=\bigg(\sum_{i=1}^{\infty} \lvert x_{i} \rvert^{p}\bigg)^{1 /p} \qquad &&\mathop{\text{if }}p \in [1,\infty) \\
    x=(x_{i})\in \ell ^{\infty}& \to \|x\|_{\infty}=\sup_{i \ge 1}\lvert x_{i} \rvert &&\mathop{\text{if }} p=\infty
\end{aligned}
$$
is a norm on $\ell^{p}$ space.

:::

::: {.proof}

Notice that from Minkowski's inequality, when $p \in [1,\infty)$ and $\sum_{i=1}^{\infty} \lvert x_{i} \rvert^{p}\lt \infty, \sum_{i=1}^{\infty} \lvert y_{i} \rvert^{p}\lt \infty$, $\sum_{i=1}^{\infty} \lvert x_{i}+y_{i} \rvert^{p}$ converges, and for a finite $\alpha\in \mathbb{K}$, $\sum_{i=1}^{\infty} \alpha \lvert x_{i} \rvert^{p}=\alpha \sum_{i=1}^{\infty} \lvert x_{i} \rvert^{p}$ also converges.

And with Minkowski's inequality, we can also easily to determine that $\|\cdot \|_{p}$ is a norm.

:::

::: {.theorem  name=""}

-   The normed vector space $\ell^{p}$ space is separable if $p \in [1,\infty)$ 
-   The normed vector space $\ell^{p}$ space is not separable if $p=\infty$

:::

::: {.proof}

Let $\mathbb{K}=\mathbb{R}$, and $p \in [1,\infty)$, let
$$ 
A=\bigcup_{n=1} ^{\infty}\{(y_{i})\in \ell^p ;y_{i}\in \mathbb{Q}\mathop{\text{ for }}i\le n,y_{i}=0\mathop{\text{ for }}i\ge n+1\}
$$
Then we show  $\overline{A}=\ell^p$, notice that $\ell^p$ is a metric space and we only need to show that for any $x\in \ell^p$ and any $\epsilon\gt 0$, there exists some $y\in A$ s.t. $\|x-y\|_{p}\le \epsilon$.

Give any $x=(x_{i})\in \ell^p$, there exists a $k\in \mathbb{N}$ s.t. $\sum_{i=k}^{\infty} \lvert x_{i} \rvert^{p}\le \epsilon^{p} /2$, and there exists some $y\in A$ which means $y_{i}\in \mathbb{Q}$ for each $i$ s.t. $\sum_{i=1}^{k-1} \lvert x_{i}-y_{i} \rvert^{p}\le \epsilon^{p} /2$, then for these $x,y\in \ell^p$, we find that $\|x-y\|_{p}\le \epsilon$.

Now give a proof of $\ell^\infty$ space is not separable.  
Give a set 
$$ 
B=\{(x_{i})\in \ell^\infty;x_{i}=0\mathop{\text{ or }}x_{i}=1,i\ge 1\}
$$
is an **uncountable set** since there is a one-to-one and onto mapping:
$$ 
(x_{i})\in B\to \sum_{i=1}^{\infty} \frac{1}{2^{i}}x_{i}
$$
It is one-to-one obviously and onto $[0,1]$ by the binary representation of a real number.  
Now suppose there is a $C \subset \ell^\infty$ s.t. $\overline{C}=\ell^\infty$. Then give any $x\in B$, there exists a $y(x)\in C$ s.t. $\|y(x)-x\|_{\infty}\lt 1 /2$ then the mapping $x\in B\to y(x)\in C$ is a injection  since if $x_1,x_2\in B$ with $x_1\neq x_2$, then $\|x_1-x_2\|_{\infty}=1$, now let $y(x_1)=y(x_2)=y$, we find that $\|x_1-x_2\|_{\infty}\le \|x_1-y\|_{\infty}+\|y-x_2\|_{\infty}$, then we get the contradiction. So if $x_1\neq x_2$, $y(x_1)\neq y(x_2)$, so this mapping must be one-to-one. It means  $\mathop{\text{card}} C \ge \mathop{\text{card}}B$ so $C$ is uncountable.

:::


::: {.definition  name="$L^{p}(\Omega)$"}

Let $\Omega$ is a open subset in $\mathbb{R}^{n}$ thus measurable. Remember that the $L^{1}(A)$ consists of all equivalence classes of real Lebesgue-measurable functions, i.e. those measurable functions $f:\Omega\to [-\infty,\infty]$ that satisfy:
$$ 
\int_\Omega \lvert f(x) \rvert dx \lt \infty
$$
Notice that a function $f:\Omega\to \overline{\mathbb{R}}$ is integrable iff $\int_\Omega \lvert f(x) \rvert dx \lt \infty$.

Now extend this definition. Let $p \in [1,\infty)$, we let $L^p(\Omega)$ denote the set formed by all equivalence classes of measurable functions $f:\Omega\to [-\infty,\infty]$ s.t. $f'=\lvert f \rvert^{p}\in L^1(\Omega)$ which means:
$$ 
\int_\Omega \lvert f(x) \rvert^{p}dx \lt  \infty \qquad \mathop{\text{for some }}p \in [1,\infty)
$$

:::

::: {.theorem  name="Holder and Minkowski's inequality for functions"}

-
    Holder:
    $$ 
    \begin{aligned}
        \frac{1}{p}+\frac{1}{q}&=1 \\
        \int_\Omega \lvert f(x) \rvert^{p}dx \lt  \infty &\mathop{\text{ and }}\int_\Omega \lvert g(x) \rvert^{q}dx \lt \infty \\
        \int_\Omega \lvert f(x)g(x) \rvert dx &\le \bigg(\int_\Omega \lvert f(x) \rvert^{p}dx\bigg)^{1 /p}\bigg(\int_\Omega\lvert g(x) \rvert^{p}dx\bigg)^{1 /q}
    \end{aligned}
    $$

-
    Minkowski:
    $$ 
    \begin{aligned}
        \int_\Omega \lvert f(x) \rvert^{p}dx \lt \infty &\mathop{\text{ and }}\int_\Omega\lvert g(x) \rvert^{p}dx \lt \infty \\
        \bigg(\int_\Omega \lvert f(x)+g(x) \rvert^{p}dx\bigg)^{1 /p}&\le \bigg(\int_\Omega \lvert f(x) \rvert^{p}dx\bigg)^{1/p}+\bigg(\int_\Omega\lvert g(x) \rvert^{p}dx\bigg)^{1 /p}
    \end{aligned}
    $$
    
:::

::: {.proof}

Replace the sum to integral from the sequence Holder and Minkowski's inequality.

:::

As we defined the space $L^p(\Omega)$ above, it is easy to verify that $L^p(\Omega)$ is a vector space and $\|\cdot \|_{p}:f\to \mathbb{R}$ defined by:
$$ 
\|f\|_{p}=\bigg(\int_\Omega \lvert f(x) \rvert^{p}dx\bigg)^{1 /p} \qquad p \in [1,\infty)
$$
Now we define the space $L^\infty(\Omega)$.

::: {.definition  name="$L^\infty(\Omega)$ space"}

-
    $L^\infty(\Omega)$ space denote the set of all measurable functions $f:\Omega\to [\infty,\infty]$ that satisfy:
    $$ 
    \inf\{C\ge 0;\lvert f \rvert\le C \mathop{\text{ a.e. in }}\Omega\}\lt \infty
    $$
    
-
    The norm $\|\cdot \|_{\infty}$ on $L^\infty(\Omega)$ is defined:
    $$ 
    \|f\|_{\infty}=\inf\{C\ge 0;\lvert f \rvert\le C \mathop{\text{ a.e. in }}\Omega\}
    $$

:::


::: {.definition  name="essential supremum"}

Give a measurable function $f:\Omega\to [-\infty,\infty]$, the extended real number
$$ 
\inf\{C\ge 0;\lvert f \rvert\le C \mathop{\text{ a.e. in }}\Omega\}\in [0,\infty]
$$
is called the **essential supremum** of $f$.

Notice that $L^\infty(\Omega)$ space consists of all equivalence class of measurable functions whose essential supremum is finite.

:::


::: {.theorem  name=""}

Let $\Omega$ is a open subset of $\mathbb{R}^{n}$, define the space
$$ 
\mathcal{C}_c(\Omega)=\{g\in \mathcal{C}(\Omega); \mathop{\text{ supp $g$ is compact in $\Omega$}}\}
$$
Then, for each $p \in [1,\infty)$, the subspace $\mathcal{C}_c(\Omega)$ is dense in $L^p(\Omega)$.

:::

::: {.proof}

To prove that $\mathcal{C}_c(\Omega)$ is a dense set, we need to show that for every $f\in L^p(\Omega)$, give any $\epsilon\gt 0$, we have some $g\in \mathcal{C}_c(\Omega)$ s.t. $\|f-g\|_{p}\le \epsilon$.

1.
    There exists a measurable simple function $s=s(f,\epsilon)$ s.t. 
    $$ 
    \mu (\{x\in \Omega;s(x)\neq 0\})\lt \infty \mathop{\text{ and }}\|f-s\|_{p}\le \epsilon /2
    $$
    to achieve this, assume that $f\ge 0$ then there exists a sequence of simple function with:
    $$ 
    0\le s_k\le f \mathop{\text{ for all }}k\ge 1 \mathop{\text{ and }}(s_k)\nearrow f \mathop{\text{ pointwise}}
    $$
    Notice that $f\in L^p(\Omega)$, which means $\int_\Omega \lvert f(x) \rvert^{p}dx\lt \infty$. As $s_k\le f$ holds for every $k\in \mathbb{N}$, $s_k\in L^p(\Omega)$. So $\mu (\{x\in \Omega;s_k(x)\neq 0\})\lt \infty$ as the definition of the integral over a simple function.  
    As $(s_k)\nearrow f$, notice that $\lvert (f-s_k) \rvert^{p}\le \lvert f \rvert^{p}$ and $\lvert f-s_k \rvert^{p}\to 0$ when $k\to \infty$, using Lebesgue's dominated convergence theorem:
    $$ 
    \int_\Omega \lim_{k\to \infty}\lvert f-s_k \rvert^{p}=\lim _{k\to \infty}\int_\Omega\lvert f-s_k \rvert^{p}=0
    $$
    so we can find some $k$ s.t. $\int_\Omega \lvert f-s_i \rvert^{p}\le (\epsilon /2)^{p}$ for all $i\ge k$, so there exists some $s=s(f,\epsilon)$ s.t. $\|f-s\|_{p}\le \epsilon /2$.

2.
    Let $s=s(f,\epsilon)$ be the measurable simple function constructed in step 1. Then there exists a function $g=g(s,\epsilon)=g(f,\epsilon)\in \mathcal{C}_c(\Omega)$ s.t. 
    $$ 
    \|s-g\|_{p}\le \epsilon /2
    $$
    Since $\mu (\{x\in \Omega;s(x)\neq 0\})\lt \infty$, Lusin's property implies that there exists a function $g\in \mathcal{C}_{c}(\Omega)$ that satisfies 
    $$ 
    \sup_{x\in \Omega}\lvert g(x) \rvert\le \|s\|_{\infty}
    $$
    $$ 
    \mu (\{x\in \Omega;g(x)\neq s(x)\})\le \bigg(\frac{\epsilon}{4\|s\|_{\infty}}\bigg)^{p}
    $$
    Then 
    $$ 
    \|s-g\|_{p}=\bigg(\int_A \lvert s-g \rvert^{p}\bigg)^{1 /p}
    $$
    Notice that $\lvert s-g \rvert\le 2\|s\|_{\infty}$ as $\sup\lvert g(x) \rvert\le \|s\|_{\infty}$, and $A$ denotes the set $\{x\in \Omega;g(x)\neq s(x)\}$, so the integral above is less than $2\|s\|_{\infty}\cdot \mu A\le \epsilon /2$.

As shown above, give $\epsilon\gt 0$ and $f\in L^p(\Omega)$ there is a $g(f,\epsilon)$ s.t. $\|f-g\|_{p}\le \|f-s_k\|_{p}+\|s_k-g\|_{p}\le \epsilon /2 +\epsilon/2=\epsilon$.

:::


::: {.theorem  name=""}

1.  $L^p(\Omega)$ is separable if $p \in [1,\infty)$ 
2.  $L^\infty(\Omega)$ is not separable.

:::

::: {.proof}

1.
    Let a $f\in L^p(\Omega)$ where $p \in [1,\infty)$ then there exists a $g=g(f,\epsilon)\in \mathcal{C}_{c}(\Omega)$ s.t. 
    $$ 
    \|f-g\|_{p}\le \epsilon /2
    $$
    Since $K=\mathop{\text{supp}}g$ is compact, there exists a bounded open set $U$ s.t. $K\subset U\subset \Omega$.
    As $U$ is bounded, $\overline{U}$ is bounded too, so $g$ is uniformly continuous on  $\overline{U}$, then there exists $\delta_0\gt 0$ s.t. 
    $$ 
    \lvert g(x)-g(y) \rvert\le \frac{\epsilon}{2(\mu (U))^{1 /p}} = \epsilon'
    $$
    for all $x,y\in \overline{U}$ s.t. $\|y-x\|_{\infty}\lt \delta_0$  
    As the compactness of $K$ and the property of distance function, there exists $\delta_1\gt 0$ s.t. 
    $$ 
    \{y\in \mathbb{R}^{n};\|y-x\|_{\infty}\lt \delta_1\} \subset U \mathop{\text{ for all }}x\in K
    $$
    Let $\delta\in \mathbb{Q}$ s.t. $0\lt \delta \le \min_{}\{\delta_0,\delta_1\}$.  
    Let $(B_{i})_{i\in I}$ denote the countable family formed by all open balls:
    $$ 
    \bigg\{y\in \mathbb{R}^{n};\|x-y\|_{\infty}\lt \frac{\delta}{2}\mathop{\text{ with }}x_{j}=p_{j}\delta\mathop{\text{ for some }}p_{j}\in \mathbb{Z},j\in [1,n]\bigg\}
    $$
    Now pick the subfamily $(B_{i})_{i\in I(K)}$ s.t. for any  $i\in I(K)$, $B_{i}\cap K\neq \varnothing$.
    Then for each $i\in I(K)$, notice that $\delta /2$ makes sure that $\mathop{\text{diam}}(B_{i}\cap K)\le \delta\le \delta_0$, so if $x\in K$, then $B_{i}\subset U$ and $\lvert g(y_1)-g(y_2) \rvert \le \epsilon'$ for every $y_1,y_2\in B_{i}$ since the property of uniform continuous. If $x\notin K$, then  as its minimum is $0$, we can also pick some $\alpha_{i}$ as blow:  
    we pick some $\alpha_{i}\in \mathbb{Q}$ s.t. 
    $$ 
    \lvert g(y)-\alpha_{i} \rvert\le \epsilon' \mathop{\text{ for all }}y\in B_{i}
    $$
    Now we can construct a simple function:
    $$ 
    h=\sum_{i\in I(K)}^{} \alpha_{i}\bm{\mathbf{1}}_{B_{i}}
    $$
    which satisfies that $\lvert h(x)-g(x) \rvert\le \epsilon'$ for almost all $x\in U$ s.t. 
    $$ 
    \|h-g\|_{p}=\bigg(\int_U \lvert h-g \rvert^{p}\bigg)^{1 /p}\le (\mu (U))^{1 /p}\cdot \frac{\epsilon}{2(\mu (U))^{1 /p}}=\frac{\epsilon}{2}
    $$
    Notice that $\|f-g\|_{p}+\|g-h\|_{p}\ge \|f-h\|_{p}$, so $\|f-h\|_{p}\le \epsilon$ and as $h$ is simple and $\alpha_{i}\in \mathbb{Q}$, so $h$ is countable as $I(K)$ is always a finite subset of a countable set and $\mathbb{Q}$ is a countable set. So $L^p(\Omega)$ is separable.


:::



















