---
title: Normed space
authors:
  - name: Xie zejian
    email: xiezej@gmail.com
bibliography: references.bib
output: rticles::arxiv_article
---

# Space of sequences

For $1\le p \lt \infty$, $\ell_p$ is defined to be the set of all sequences $x.=(x_1,x_2,\cdots)$ for which $\|x\|_p\lt \infty$. Where 
$$ \|x\|_p=(\sum_1^\infty |x_i|^p)^{1/p} $$
is the **$\ell_p$ norm** of the sequences.

While $\ell_\infty$ is defined as the set of all $\sup \{|x_n|\}\le \infty$, such norm is called **$\ell_\infty$ norm**, **supremum norm** or **uniform norm**.

All of these spaces are vector space. And sequence $\ell_i$ is increasing.

The space of all convergent sequence is denoted $c$ and all sequences convergent to $0$ is denoted $c_0$. Finally, the collection of sequences with finite nonzero terms is $\varphi$. One can check that

$$ \varphi\subset \ell_p \subset c_0 \subset \ell_\infty \subset \R^n $$

# Spaces of functions

One can think $\R^n$ as 

$$ \{f:\{1,2,\cdots,n\}\to \R\}=\R^n=\R^{\{1,2,\cdots,n\}} $$

Replace $\{1,2,\cdots,n\}$ by an arbitrary $X$, then $\R^X$ is all functions from $X$ to $\R$.

For $1\le p \lt \infty$, $L_p(\mu)$ is defined to be the set of all $\mu$ measurable functions $f$ for which $\|f  \|_p< \infty$, where the **$L_p$ norm** is defined as 

$$ \|f\|_p=(\int_\Omega |f|^p)^{1/p} $$

And the **$L_\infty$ norm**, or **essential supremum** is defined as

$$ \|f\|_\infty=\operatorname{ess}\sup f=\sup \{t:\mu(\{x:|f(x)|\ge t\})>0\}  $$






## Existence of basis
Every non-zero vector space has a basis.

**Proof** Let $\mathcal{X}$ be the class of all independent subsets of space $V$. Then $(\mathcal{X},\subset)$ is a poset. Forall chain $\mathcal{Y}\subset \mathcal{X}$, note $\cup \mathcal{Y}\in \mathcal{X}$ is a upper bound of $\mathcal{Y}$. Apply Zorn's lemma we can find a maximal element $B\in \mathcal{X}$ and $\langle B \rangle=V$, so $B$ forms a basis of $V$.

## Knaster-Tarski fixed point theorem

Let $(X,\succeq)$ be an inductive ordered set. Let $f:X\to X$ is monotone and assume there exist $x\in X$ s.t. $x\le f(x)$. Then the set of all fixed point is nonempty and has a maximal fixed point.

**Proof** 

# Ordinals

A set $X$ is **well ordered** by linear $\preceq$ if every nonempty subset has a least element. An **initial segement** of $(X,\preceq)$ is any set of the form $I(x)=\{y\in X:y\le x\}$. An **ideal** in a well ordered $X$ is a subset $A$ s.t. forall $a\in A$, $I(a)\subset A$.

> **Theorem** Every nonempty set can be well ordered.
>
> **Proof** Let $X$ nonempty, and let
> $$ \mathcal{X}=\{(A,\preceq_A) \text{ is well order}:A\subset X\} $$
> all well ordered sets, and define $\preceq$ on $\mathcal{X}$ as $(B,\preceq_B) \preceq (A,\preceq_A)$ if $B$ is an ideal in $A$ and $\preceq_A$ extends $\preceq_B$. Suppose every chain $\mathcal{C}$ in $\mathcal{X}$, $(\cup \mathcal{C},\cup \{\prec_A:A\in \mathcal{C}\})$ clearly an upper bound of $\mathcal{C}$ and well ordered. By Zorn's lemma, there is a maximal element of $\mathcal{X}$ and it's actually $X$. $\blacksquare$

> **Theorem** There exist poset $(\Omega,\preceq )$ satisfy
> 1. $(\Omega,\preceq)$ is weel ordered.
> 2. $\Omega$ has a greast element $\omega_1$
> 3. $I(x)$ is countable for $x<\omega_1$
> 4. $\{y\in \Omega:x\le y\le \omega_1\}$ is uncountable.
> 5. Every nonempty subset of $\Omega$ has a least upper bound.
> 6. A nonempty subset of $\Omega-\{\omega_1\}$ has greatst element iff it's countable. Every uncountable subset has least upper bound $\omega_1$.


```{theorem, name="Pythagorean theorem"}
For a right triangle, if $c$ denotes the length of the hypotenuse
and $a$ and $b$ denote the lengths of the other two sides, we have
$$a^2 + b^2 = c^2$$
```

# Inequality

### Young's inequality

Let $f$ be a continues and strictly increasing function with $f(0)=0$, then we have

$$ a b \leq \int _ { 0 } ^ { a } f ( x ) d x + \int _ { 0 } ^ { b } f ^ { - 1 } ( x ) d x $$

Take $f(x)=x^{p-1}$, then $f^{-1}(x)=x^{q-1}$ if $(p-1)(q-1)=1\iff \frac{1}{p}+\frac{1}{q}=1$. Hence we have

$$ ab\le\frac{a^p}{p}+\frac{b^q}{q} $$

### Holder's inequality

For $\mathbf{a,b}\in \mathbb{R^n}$, $\frac{1}{p}+\frac{1}{q}=1$,

$$ \sum |a_ib_i|=\mathbf{|a|'|b|}\le \|\mathbf{a}\|_p\|\mathbf{b}\|_q $$

### Minkowski's inequality

For $\mathbf{a,b}\in \mathbb{F}^n$, $\frac{1}{p}+\frac{1}{q}=1$,

$$ \|\mathbf{a+b}\|_p \le \|\mathbf{a}\|_p+\|\mathbf{b}\|_p $$

## Normed Vector spaces

Let $(X,+,\cdot)$ be a vector space over $\mathbb{F}$. A norm on $X$ is a function from $X\to \mathbb{R\ge0}$ satisfy:

1. $\|x\|\ge0$ and $=$ occurs iff $x=0$
2. $\|x+y\|\le \|x\|+\|y\|$
3. $\|cx\|=|c|\|x\|$

A vector space with a norm is **normed vector space**. 

Let $\mathbf{c}$ is $n\times 1$ and $\mathbf{X}=\begin{bmatrix}
  \mathbf{x_1}&\mathbf{x_2}&\cdots & \mathbf{x_n}
\end{bmatrix}$ is $n\times n$ where $x_i$ is $n$ vector. Then

$$ \begin{aligned}
  \|\mathbf{Xc}\|&=\|\sum c_i \mathbf{x_i}\|
  \\&\le \sum \|c_i \mathbf{x_i}\|
  \\&= \sum |c_i|\| \mathbf{x_i}\|
  \\&= \|\mathbf{X}\||\mathbf{c}|
\end{aligned} $$

where 

$$
\|\mathbf{X}\|=\begin{bmatrix}
  \|\mathbf{x_1}\|&\|\mathbf{x_2}\|&\cdots & \|\mathbf{x_n}\|
\end{bmatrix},|\mathbf{c}|=\begin{bmatrix}
  |c_1|\\
  |c_2|\\
  \vdots\\
  |c_n|
\end{bmatrix}
$$



Let $(X,\|\cdot\|)$ be a normed space, define $d(x,y)=\|x-y\|$, one can check $d$ is a metric and is called as induced metric of the form. Then we can talk about convergence in this space. Clearly, the norm is a continuous function and $+$ and $\cdot$ are also continuous.

If $x_n\to x$ in $\|\cdot\|_1\implies x_n\to x$ in $\|\cdot\|_2$, we say $\|\cdot\|_1$ is stronger than $\|\cdot\|_2$. If they are stonger than each other, we say they are equivalent.

> All norm on finite dimensional space are equivalent.

**Proof** It's sufficient to show that every norm is equivalet to $\|\cdot\|_2$:

$$ \|\mathbf{x}\|=\|\mathbf{Ex}\|\le\|\mathbf{E}\||\mathbf{x}|\le \|\mathbf{x}\|_2\|(\|\mathbf{E}\|')\|_2=c\|\mathbf{x}\|_2 $$

where 

$$ \mathbf{E}=\begin{bmatrix}
  \mathbf{e_1}&\mathbf{e_2}&\cdots & \mathbf{e_n}
\end{bmatrix}=\mathbf{I} $$

This state that $\|\cdot\|$ stronger than any norm. On the other hand, consider

$$ \alpha=\inf\{\|\mathbf{x}\|:\|\mathbf{x}\|_2=1\} $$

It's positive since $\{\|\mathbf{x}\|_2=1\}$ is compact. Then we have

$$ \alpha\le \|\frac{\mathbf{x}}{\|\mathbf{x}\|_2}\|=\frac{\|\mathbf{x}\|}{\|\mathbf{x}\|_2}\implies\|\mathbf{x}\|\ge \alpha \|\mathbf{x}\|_2 $$

For any abstract space $X$, $x\in X$ can be presented as linear combinations of bias, say $x=\sum a_i e_i$, then $x\mapsto (a_1,\cdots,a_n)$ is isomorph from $X$ to $\mathbb{R^n}$. And any norm iduced a norm on $\mathbb{R^n}$ by

$$ \|x\|=\|(a_1,\cdots,a_n)\widetilde{\|} $$

Hence all norm is equivalent.

### Separability

A subset $E$ of $(X,d)$ is a **dense set** if its closure is $X$: 

$$ \overline{E}=X $$

A metric space is called **separable** if it has a countable dense subset.

### Completeness

A metric space $(X,d)$ is **complete** if every Cauchy sequence converges.

> Every metric space has a completion







<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>








