---
title: Topology Space
authors:
  - name: Xie zejian
    email: xiezej@gmail.com
bibliography: references.bib
output: rticles::arxiv_article
---

## Topology

Let $\Omega$ be as space

**Definition**: A class of subset $\mathcal{T}$ of $\Omega$ is an **topology** if

1. $\emptyset$ and $\Omega$ belongs to $\mathcal{T}$.
2. closed under arbitary union.
3. closed under finite intersection.

$(X,\rho)$ is a **metric space**, when $\rho$ defined on $X\times X$ s.t. $\forall x,y,z \in X$:
1. $\rho(x,y)\ge 0$, the equality hold iff $x=y$.
2. $\rho(x,y)=\rho(y,x)$
3. $\rho(x,y)\le\rho(x,z)+\rho(z,y)$

$\rho$ is called a **metric**.

Let $E=\mathbb{R}^n$, $l^2=\sqrt{\sum_1^n(x_i-y_i)^2}$ is called **Euclidean metric**. $l^1=\sum_1^n|x_i-y_i|$ is called **texi-cab metric** and $l^\infty=\sup\{|x_i-y_i|\}$ is called **sup norm metric**.

Let $(E,d)$ be an metric space. $V(a,r)=\{x\in E,d(x,a)<r\}$ is **$r$-ball** with center $a$. 

$U$ is **open** relative to $d$ iff $\forall x\in U, \exists r_x> 0 \ni V_d(x,r_x)\subseteq U$. Let $T_d$ be the set of all open subsets of $E$, we call $T_d$ the **topology induced by $d$**.

Suppose $d$ is discrete, that is, $d(x,y)=0$ iff $x=y$, otherwise, $d(x,y)=1$. Then every subset is open and $T_d=\mathcal{P}(\Omega)$. Such $T_d$ is called **discrete topology**.

Note $d_{l^2}(x,y)\le d_{l^1}(x,y)\le \sqrt{n}d_{l^2}(x,y)$ and $d_{l^2}(x,y)\le \sqrt{n}d_{l^\infty}(x,y)\le \sqrt{n}d_{l^2}(x,y)$, then $d_{l^\infty}$ open $\iff d_{l^2}$ open $\iff$ $d_{l^1}$ open. Hence $T_{d_{l^2}}=T_{d_{l^1}}=T_{d_{l^\infty}}$.

One can change **1** in definition of metric from "iff" to "if" to get a **pseudometric**. A **quasimetric** is measure without **2**. And a **ultrametric** is a metric plus

$$ u(x,z)\le \max(u(x,y),u(y,z)) $$

One can check that a triangle in an ultrametric must be a  isosceles. The pseudometric, quasimetric, ultrametric can induce topology in a familar way.

Then We can forget metric in some way. $(X,\Omega)$ is a topological space if $\mathcal{T}$ is a topology on $E$. Where $E$ is called as **uderlying set**. The sets in $\mathcal{T}$ are called **open**. If $\mathcal{T}$ can be form by taking union of families in some $\mathcal{B}\subset T$, we call $\mathcal{B}$ the **base** for the topology $\mathcal{T}$.

> $\mathcal{B}$ is a base in $(X,\mathcal{T})$ iff $\forall U\in \mathcal{T},\forall x\in U, \exists W\in \mathcal{B}\ni x\in W\subset U$.

**Proof** $\implies$: Any $U$ can be written as $U=\cup W_i$ and $x\in U\implies x\in W_i$ for some $i$ and $W_i\in \mathcal{B}$.
$\impliedby$: For any $U\in T$, consider arbitary $x\in U$, then there exist $W_x$ such that $x\in W_x \subset U$, thus we have $U=\cup_x W_x$. $\blacksquare$

> If $\cup \mathcal{B}=E$ and $\forall W_1,W_2\in \mathcal{B},\forall x \in W_1\cap W_2,\exists W\in \mathcal{B} \ni x\in W\subset W_1\cap W_2$. Then $\{\text{union of families of } \mathcal{B}\}$ is a topology and it's the unique topology with $B$ as base.

**Proof**  Let $T=\{\text{union of families of } \mathcal{B}\}$, then it's sufficient to show that $\mathcal{T}$ is a topology. 

Note the families can be empty, $\mathcal{T}$ enjoy **1** and **2** clearly. To show it also satisfy **3**, suppose $U_1,U_2\in \mathcal{T}$, for any point $x\in U_1\cap U_2$, we may find some $x\in W_1\subset U_1$ and $X\in W_2\subset U_2$. By hypotheseis there exist $W_x\subset W_1\cap W_2\subset U_1\cap U_2$ in $B$. Hence we may form $U_1\cap U_2$ by $\cup_x W_x$, thus $U_1\cap U_2\in \mathcal{T}$. We skip the discussion of if $U_1$ or $U_2$ is empty since it's trival. $\blacksquare$

Let $\mathcal{S}$ be a class of subset in $X$, the define $\tau(\mathcal{S})$ as all topology contains $\mathcal{S}$. Let $T(S)=\cap \tau(\mathcal{S})$, then $T(\mathcal{S})$ is the smallest topology contains $\mathcal{S}$. We call it the topology **generated** by $\mathcal{S}$.

> $T(\mathcal{S})$ is unions of families of finite intersections together with $\Omega$
> $$ \{\bigcup(\bigcap_1^N S_i)\}\cup \Omega $$

A subset $F$ is **closed** if $F^c\in \mathcal{T}$, it has parallel properties with open sets. Countable intersection of open sets is $G_\sigma$ set and countable union of closed sets is $F_\delta$ set. A complement of a $G_\sigma$ set is $F_\delta$ and vice versa. 

A subset $V$ is called a **neighborhood** of $a$ if there exists a open set $U\subset V$ contains $a$. Then we called $V'=V-\{a\}$ **punctured(deleted)** neighborhood. A **neighborhood base** is a collection of neighborhood $BN(a)$ s.t. for any neighborhood $V$ of $a$, there exist a $W\in BN(a)$ and $W\subset V$.

> A subset $U$ is open iff it's a neighborhood for each of its points.

**Proof** $\implies$ is trival. $\impliedby$ follows from $\cup_x G_x=U$ and unions of open set is still open. $\blacksquare$

This suggest a equivalent definition of finear topology:

> $T'\subset T\iff$ T' neighborhood is a T neighborhood.

**Proof** $\implies$ any open set $G_x$ satisfy $x\in G_x\subset V$ in $T'$ is still open in $T$, hence $V$ is $T$ neighborhood.
$\impliedby$ Consider any open set $G\in T'$, it's a $T'$ neighborhood for each of its points implies it's a $T$ neighborhood for each of its points and hence $G$ is $T$ open.

The **interior** of $A$ is the union of all open sets which are included $A$, i.e., the largest open set included in $A$, we denote it $A^\circ$. And the **closure** is the intersection of all closed sets which include $A$ and thus the smallest closed set includes $A$, we denote it $\overline{A}$.

> 1. $(A\cap B)^\circ=A^\circ \cap B^\circ$
> 2. $\overline{A\cup B}=\overline{A}\cup \overline{B}$
> 3. $A \subset \overline{B}\implies \overline{A}\subset \overline{B}$
> 4. $A^\circ\subset B\implies A^\circ \subset B^\circ$
> 5. $\overline{A^c}=(A^\circ)^c$
> 6. $(\overline{A})^c=(A^c)^\circ$

**Proof** We only prove **5**, note $(A^\circ)^c$ is closed and

$$ A^\circ\subset A\implies (A^c)\subset (A^\circ)^c $$

we have $\overline{A^c}\subset (A^\circ)^c$. On the other hand

$$\overline{A^c}\supset (A^\circ)^c\impliedby (\overline{A^c})^c\subset A^\circ\impliedby (\overline{A^c})^c \subset A \impliedby \overline{A^c}\supset A^c.\blacksquare $$




The **frontier** of $A$ is $\partial A=\overline{A}\cap \overline{A^c}=\overline{A}\cap (A^\circ)^c=\overline{A}-A^\circ$.

> $\overline{A}=A \cup \partial A$ and $A^\circ=A-\partial A$

**Proof** 

$$ \begin{aligned}
  A\cup \partial A&= A\cup (\overline{A}\cap \overline{A^c})
  \\&= (A\cup \overline{A})\cap (A\cup \overline{A^c})
  \\&= ( \overline{A})\cap (A\cup (A^\circ)^c)
\end{aligned} $$

note $A\cup (A^\circ)^c\supset A^\circ\cup (A^\circ)^c=\Omega$, $A\cup \partial A=\overline{A}\cap \Omega=\overline{A}$. And the $A^\circ=A-\partial A$ follows from substituting $\overline{A}=A \cup \partial A$. $\blacksquare$

$x$ is said to be an **interior point** of $A$ if $A$
is neighborhood of $x$.

$x$ is said to be an **adherent point** if it's every neighborhood meets $A$, an **$\omega$ accumulation point** of $A$ if every neighborhood of $x$ contains **infinitely** many points of $A$ and is a **condensation point** of $A$ if every neighborhood of $x$ contains **uncountable** many points of $A$.

$x$ is a **cluster point** or **accumulation point** if every deleted neighborhood of $x$ meets $A$ and is **isolated point** if $x$ is not cluster point.

$x$ is **frontier point** if every neighborhood of $x$ meets both $A$ and $A^c$.

> The points of $A^\circ$ are precisely all the interior points of $A$ and $\overline{A}$ are precisely all the adherent points.

**Proof** For interior points, consider $I$ as all the interior points, it's sufficient to show that $I=A^\circ$

$$I\subset  \bigcup_{x\in I} G_x \subset A^\circ $$

where $G_x$ is the corresponding open set. On the other hand we have $A^\circ \subset I$ since every points in $A^\circ$ has $A^\circ$ as their neighborhood.

For interior points, suppose $x\in \overline{A}$ but is not an adherent point, then there is a open $G$ contains $x$ and $G\cap A=\emptyset$. Hence $A\subset G^c$, note $G^c$ is closed and thus $G^c\supset \overline{A}$, which is contradict to $x\in \overline{A}$. On the other hand, suppose $x$ is adherent but not in $\overline{A}$. Then $\overline{A}^c$ is a neghborhood of $A$ and disjoint to $\overline{A}$, a contradition. $\blacksquare$.

By above theorem, we have 

> $\partial A$ is precisely points of frontier.

**Proof** By definition, point of frontier is both adherent point of $A$ and $A^c$ and thus all the points of frontier are

$$ \overline{A}\cap\overline{A^c}=\partial A $$


> For any subset $X$, define $\alpha(X)=(\overline{A})^\circ$, then
> 
> 1. $X\subset Y\implies \alpha(X)\subset \alpha(Y)$
> 2. If $X$ is open, $X\subset \alpha(X)$
> 3. $\alpha(\alpha(X))=\alpha(X)$
> 4. If $X$ and $Y$ are disjoint open then $\alpha(X)$ and $\alpha(Y)$ are also.
> 
> If $\alpha(X)=X$, $X$ is said to be **regular open**

**Proof** **2** follows from $X\subset \overline{X}\implies X\subset \alpha(X)$. 

To estabish **3**, we show that $A^\circ$ is regular open when $A$ is closed and $\overline{A}$ is regular open when $A$ is open. When $A$ is closed, $\partial A\subset A$, then

$$ \overline{A^\circ}=(A-\partial A)\cup \partial A=A \implies \alpha(A^\circ)=A^\circ$$

Hence $\alpha(X)=(\overline{A})^\circ$ is regular open since $\overline{A}$ is closed.

For **4**, suppose there is $x\in \alpha(X)\cap \alpha(Y)$, then 

$$ \begin{aligned}
  \alpha(X)\cap \alpha(Y)=(\overline{X}\cap \overline{Y})^\circ\subset \overline{X}\cap \overline{Y}
\end{aligned} $$

hence $x$ is adherent to both $X$ and $Y$, note $X$ is neighborhood of $x$ and $X$ meets $Y$ by definition, a contradiction. $\blacksquare$

> Finite intesection of regular open sets is regular open

**Proof** Let $(G_i)_{i\in I}$ be a finite family of regular open sets. We have

$$ \bigcap_{i\in I} G_i\subset \alpha(\bigcap_{i\in I} G_i)\subset \alpha(G_i)=G_i $$

holds for all $G_i$, hence $\alpha(\bigcap_{i\in I} G_i)\subset \bigcap_{i\in I} G_i$, then the claim follows. $\blacksquare$

> 1. $\partial (\overline{A}) \subset \partial A$ and $\partial(A^\circ)\subset \partial A$
> 
> 2. $\partial(A\cup B)\subset \partial A\cup \partial B$

**Proof**:

**2**: Suppose $x\in \partial (A\cup B)$, then any neighborhood $N$ meet $A\cup B$ and $A^c\cap B^c$. W.L.O.G, we assume $N$ meet $A$, since $N$ also meet $A^c$, $x\in \partial A\subset \partial A\cup \partial B$. $\blacksquare$

$A$ is said **dense** if $\overline{A}=\Omega$ and **nowhere dense** if $(\overline{A})^\circ=\emptyset$ ($\mathbb{Q}$ is dense in $\mathbb{R}$ while $\mathbb{Z}$ is nowhere dense.) $A$ is said to be **meagre** or **set of the first category** if it's countable union of nowhere dense. Sets which are not meagre is **set of the second** category set.

Space $(\Omega,\mathcal{T})$ is **first countable** if every point of $\Omega$ has countable neighborhood base and is **second countable** if $\mathcal{T}$ has countable base. The space is said **separable** if $\Omega$ has a countable dense subset.

> Second countable space is separable

**Proof** Suppose $\mathcal{B}=(B_i)_{i\in I}$ is a countable base, by axiom of choice, we may take $x_i$ in $I$, let $X=\{x_i\}_{i\in I}\subset \Omega$. Then we show that $X$ is dense. For any $x\in \Omega$, it's neighborhood must contain some open $G$ which is unions of $\mathcal{B}$ and thus contains at least one element in $X$, that is, $G$ meet $X$. Hence $\overline{X}=\Omega$. $\blacksquare$ 

> Second countable space is first countable

Suppose $\mathcal{B}=(B_i)_{i\in I}$ is a countable base, for each point $x\in \Omega$, one may take all the sets in $\mathcal{B}$ which contains $x$ as a neighborhood base. To verify it's neighborhood base, if there is a neighborhood $N$ of $x$, then there is a open $G$ contains $x$. By the definition of base, $G$ is the union of sets of $\mathcal{B}$ and those sets must at least one contains $x$ and these sets is subset to $G$. $\blacksquare$ $$








<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>



