# Topology

## Topological spaces

Let $\Omega$ be as space

:::{.definition #topology name=""}
A class of subset $\tau$ of $\Omega$ is an **topology** if

1. $\emptyset$ and $\Omega$ belongs to $\tau$.
2. closed under arbitrary union.
3. closed under finite intersection.

:::

$(\Omega,\tau)$ called a **topological space** where $\Omega$ is called as **underlying set**. The sets in $\tau$ are called **open** while sets with complement in $\tau$ is **closed**. Both open and closed set is called **clopen**. 

:::{.definition #countableclosed name=""}

Countable intersection of open sets is $\mathcal{G}_\sigma$ set and countable union of closed sets is $\mathcal{F}_\delta$ set.

:::

:::{.definition #metric name=""}

$(X,\rho)$ is a **semimetric space**, when $\rho$ defined on $X\times X$ s.t. $\forall x,y,z \in X$:

1. $\rho(x,y)\ge 0$
2. $\rho(x,y)=\rho(y,x)$
3. $\rho(x,y)\le\rho(x,z)+\rho(z,y)$

$\rho$ is called a **semimetric**.

:::

If $\rho(x,y)=0\iff x=y$, $\rho$ become a **metric** and $(X,\rho)$ become **metric space**.
$B(a,r)=\{x\in E,d(x,a)<r\}$ is $r$-ball with center $a$. 

$U$ is **open** in $(\Omega,d)$ iff $\forall x\in U, \exists r_x 0 \ni B_d(x,r_x)\subseteq U$. Let $\tau_d$ be the set of all open subsets of $\Omega$, we call $\tau_d$ the **topology generated by** $d$. A Topological space is **metrizable** if there exist metric $d$ generates it.

Suppose $d$ is discrete, that is, $d(x,y)=0$ iff $x=y$, otherwise, $d(x,y)=1$. Then every subset is open hence $\tau_d=\mathcal{P}(\Omega)$ and called **discrete topology**. The zero semimetric, defined by $d(x,y)=0$ for all $x,y\in \Omega$ generates $\tau_d=\{\emptyset,\Omega\}$ and called **trivial topology**.

Let $\Omega=\R^n$, $l^2=\sqrt{\sum_1^n(x_i-y_i)^2}$ is called **Euclidean metric**. $l^1=\sum_1^n|x_i-y_i|$ is called **taxi-cab metric** and $l^\infty=\sup\{|x_i-y_i|\}$ is called **sup norm metric**.

Note $d_{l^2}(x,y)\le d_{l^1}(x,y)\le \sqrt{n}d_{l^2}(x,y)$ and $d_{l^2}(x,y)\le \sqrt{n}d_{l^\infty}(x,y)\le \sqrt{n}d_{l^2}(x,y)$, then $d_{l^\infty}$ open $\iff d_{l^2}$ open $\iff$ $d_{l^1}$ open. Hence $\tau_{d_{l^2}}=\tau_{d_{l^1}}=\tau_{d_{l^\infty}}$.

All topologies on $\Omega$ is poset with greatest element $\mathcal{P(\Omega )}$ and least $\{\emptyset,\Omega\}$. If $\tau'\subset \tau$, we say $\tau'$ **coarser** than $\tau$ while $\tau$ finer than $\tau'$.


If $\tau$ can be form by taking union of families in some $\mathcal{B}\subset \tau$, we call $\mathcal{B}$ the **base** for the topology $\tau$.

:::{.theorem #equivbase name=""}

$\mathcal{B}$ is a base in $(X,\tau)$ iff $\forall U\in \tau,\forall x\in U, \exists W\in \mathcal{B}\ni x\in W\subset U$.

:::

:::{.proof}

$\implies$: Any $U$ can be written as $U=\cup W_i$ and $x\in U\implies x\in W_i$ for some $i$ and $W_i\in \mathcal{B}$.
$\impliedby$: For any $U\in T$, consider arbitrary $x\in U$, then there exist $W_x$ such that $x\in W_x \subset U$, thus we have $U=\cup_x W_x$.

:::

Let $\mathcal{S}\subset \tau$, suppose all topologies include $\mathcal{S}$. Then the intersection of all of them is again a topology, denoted as $\tau(S)=\cap \Tau$, then $\tau(\mathcal{S})$ is the smallest topology contains $\mathcal{S}$. We call it the topology **generated** by $\mathcal{S}$.

:::{.theorem #topogen name=""}

$\tau(\mathcal{S})$ is unions of families of finite intersections together with $\Omega$, formally:

$$ \{\bigcup(\bigcap_1^N S_i)\}\cup \Omega $$

:::

$\mathcal{S}\subset \tau$ is a **subbase** for $\tau$ if $\bigcup \mathcal{S}=\Omega$ then all finite intersections of $\mathcal{S}$ is a base. Note that if $\Omega \in \mathcal{S}$, $\mathcal{S}$ is the subbase of $\tau(\mathcal{S})$. 

$(\Omega,\tau)$ is **second countable** if $\tau$ has countable base. Clearly, a topology is second countable iff it has countable subbase.

For any subset $X$ in $(\Omega,\tau)$, then

$$ \tau_X=\{X\cap V:V\in \tau \} $$

form a topology in $X$ and we call $(X,\tau_X)$ a **subspace** or **relative topology**. Sets in $\tau_X$ are **relative open**. **Relative closed** sets of the form

$$ X-(X\cap V)=X-V=X\cap V^c $$

## Neighborhood

A subset $V$ is called a **neighborhood** of $a$ if there exists a open set $U\subset V$ contains $a$. Then we called $V'=V-\{a\}$ **punctured(deleted)** neighborhood. A **neighborhood base** is a collection of neighborhood $BN(a)$ s.t. for any neighborhood $V$ of $a$, there exist a $W\in BN(a)$ and $W\subset V$. Clearly, all the neighborhoods is a neighborhood base and denoted as $\mathcal{N}(x)$, which is called **neighborhood system**.

:::{.lemma #openquiv name=""}

A subset $U$ is open iff it's a neighborhood for each of its points.

:::

:::{.proof}

$\implies$ is trivial. $\impliedby$ follows from $\cup_x G_x=U$ and unions of open set is still open. $\blacksquare$

:::

This suggest a equivalent definition of finer topology:

:::{.lemma #euqivfiner name=""}
$\tau'\subset \tau\iff$ $\tau$' neighborhood is a $\tau$ neighborhood.
:::

:::{.proof}

$\implies$ any open set $G_x$ satisfy $x\in G_x\subset V$ in $T'$ is still open in $T$, hence $V$ is $T$ neighborhood.
$\impliedby$ Consider any open set $G\in T'$, it's a $T'$ neighborhood for each of its points implies it's a $T$ neighborhood for each of its points and hence $G$ is $T$ open.

:::



## Closures

The **interior** of $A$ is the union of all open sets which are included $A$, i.e., the largest open set included in $A$, we denote it $A^\circ$. And the **closure** is the intersection of all closed sets which include $A$ and thus the smallest closed set includes $A$, we denote it $\overline{A}$.

:::{.lemma name=""}
Following is some useful truth:

1. $(A\cap B)^\circ=A^\circ \cap B^\circ$
2. $\overline{A\cup B}=\overline{A}\cup \overline{B}$
3. $A \subset \overline{B}\implies \overline{A}\subset \overline{B}$
4. $A^\circ\subset B\implies A^\circ \subset B^\circ$
5. $\overline{A^c}=(A^\circ)^c$
6. $(\overline{A})^c=(A^c)^\circ$

:::

:::{.proof}

We only prove **5**, note $(A^\circ)^c$ is closed and

$$ A^\circ\subset A\implies (A^c)\subset (A^\circ)^c $$

we have $\overline{A^c}\subset (A^\circ)^c$. On the other hand

$$\overline{A^c}\supset (A^\circ)^c\impliedby (\overline{A^c})^c\subset A^\circ\impliedby (\overline{A^c})^c \subset A \impliedby \overline{A^c}\supset A^c$$

:::

The **frontier** of $A$ is $\partial A=\overline{A}\cap \overline{A^c}=\overline{A}\cap (A^\circ)^c=\overline{A}-A^\circ$.


$x$ is said to be an **interior point** of $A$ if $A$
is neighborhood of $x$.

$x$ is said to be an **adherent point** if it's every neighborhood meets $A$, an **$\omega$ accumulation point** of $A$ if every neighborhood of $x$ contains **infinitely** many points of $A$ and is a **condensation point** of $A$ if every neighborhood of $x$ contains **uncountable** many points of $A$. 

$x$ is a **cluster point** or **accumulation point** if every deleted neighborhood of $x$ meets $A$ and is **isolated point** if $x$ is not cluster point. That is, $\{x\}$ is relative open in $A$. We denoted all the cluster points as $A'$ and called **derived set**.

$x$ is **frontier point** or **boundary point** if every neighborhood of $x$ meets both $A$ and $A^c$.

It's east to show that the points of $A^\circ$ are precisely all the interior points of $A$ and $\overline{A}$ are precisely all the adherent points. $\partial A$ is precisely points of frontier. We claim that

$$ \overline{A}=A^\circ\cup \partial A=A\cup A' $$

A subset $A$ is called **perfect** if it's closed while point in $A$ is cluster points in $A$, that is $A'=A=\overline{A}$.

## Dense

$A$ is said **dense** if $\overline{A}=\Omega$ and **nowhere dense** if $(\overline{A})^\circ=\emptyset$ ($\mathbb{Q}$ is dense in $\mathbb{R}$ while $\mathbb{Z}$ is nowhere dense.) $A$ is said to be **meagre** or **set of the first category** if it's countable union of nowhere dense. Sets which are not meagre is **set of the second** category set.

Space $(\Omega,\tau)$ is **first countable** if every point of $\Omega$ has countable neighborhood base. The space is said **separable** if $\Omega$ has a countable dense subset.

:::{.lemma #snds name=""}

Second countable space is separable

:::

:::{.proof}

Suppose $\mathcal{B}=(B_i)_{i\in I}$ is a countable base, by axiom of choice, we may take $x_i$ in $I$, let $X=\{x_i\}_{i\in I}\subset \Omega$. Then we show that $X$ is dense. For any $x\in \Omega$, it's neighborhood must contain some open $G$ which is unions of $\mathcal{B}$ and thus contains at least one element in $X$, that is, $G$ meet $X$. Hence $\overline{X}=\Omega$. 

:::

:::{.lemma #sndc name=""}

Second countable space is first countable

:::

:::{.proof}

Suppose $\mathcal{B}=(B_i)_{i\in I}$ is a countable base, for each point $x\in \Omega$, one may take all the sets in $\mathcal{B}$ which contains $x$ as a neighborhood base. To verify it's neighborhood base, if there is a neighborhood $N$ of $x$, then there is a open $G$ contains $x$. By the definition of base, $G$ is the union of sets of $\mathcal{B}$ and those sets must at least one contains $x$ and these sets is subset to $G$.

:::


## Mappings

Suppose $(\Omega,\tau)$ and $(\Omega',\tau')$ are two spaces and $f$ is a mapping from $\Omega$ to $\Omega'$ in the following.


:::{.lemma name=""}

Following is some useful truth for mappings.

1. $ff^{-1}(A)\subset A$
2. $f^{-1}f(A)\supset A$
3. $f^{-1}(U\cap N)=f^{-1}(U)\cap f^{-1}(N)$
4. $f^{-1}(U\cup N)=f^{-1}(U)\cup f^{-1}(N)$
5. $f^{-1}(A^c)=(f^{-1}(A))^c$
6. $f^{-1}f(A)=A$ always holds if $f$ is injection while $ff^{-1}(A)=A$ always holds if $g$ is surjection.
7. If $f$ is bijection, $(f^{-1})^{-1}(A)=f(A)$ always hold.
8. $(f\circ g)^{-1}(A)=g^{-1}f^{-1}(A)$
9. $f^{-1}(A)\subset f^{-1}(B)\impliedby A\subset B$
10. $f(A)\subset f(B) \impliedby A\subset B$

:::


:::{.definition #cont name=""}

$f$ is **continuous** at $x$ if for every neighborhood $N'$ of $f(x)$, there is a neighborhood $N$ of $x$ s.t. $f(N)\subset N'$. It's continuous if it's continuous at every points $x\in \Omega$.
:::

:::{.theorem name=""}

$f$ is continuous iff 

1. $f^{-1}(G')$ is open for every open subset $G'$ of $\Omega'$.
2. $f^{-1}(F')$ is closed for every closed subset $F'$ of $\Omega'$.
3. If $A\subset \Omega'$, then $f^{-1}({A^\circ})\subset (f^{-1}(A))^\circ$
4. If $A\subset \Omega$, then $f(\overline{A}\subset \overline{f(A)})$

:::

:::{.proof}

We only prove 1 and 3.

1 $\implies$: For any $x\in f^{-1}(G')$, it's sufficient to show that $f^{-1}(G')$ is its neighborhood. By definition, there is a neighborhood $N$ s.t. $f(N)\subset G'$, and
 
$$ x\in N\subset f^{-1}f(N)\subset f^{-1}(G') $$

$\impliedby$: For every neighborhood $N'$, there is some open $G'$ contain $f(x)$, and $f^{-1}(G')$ is neighborhood of $x$ and $ff^{-1}(G')\subset G'$.

3 $\implies$: $f^{-1}(A^\circ)$ is open and th claim follows from $f^{-1}(A\circ)\subset f^{-1}(A)$.
$\impliedby$: Suppose $A$ is open, then $A^\circ=A$ and hence $f^{-1}(A)\subset (f^{-1}(A))^\circ$. Which suggest $f^{-1}(A)$ is open. 

:::


::: {.lemma #glue name="Glueing Lemma"}

Let $X=A \cup B$ and $A$ and $B$ are both closed or both open, then $f:X \to Y$ is continuous iff it's restriction on $A$ and $B$ are both continuous.

:::


::: {.proof}

$\implies$ is trivial.

$\xLeftarrow{}$ Suppose they are both open and $U$ be any open set in $Y$. Note $f_{|A}^{-1}(U)$ is open in $A$ and thus open in $X$, thus
$$ 
f^{-1}(U)=\left( f^{-1}(U) \cap B \right) \cup\left(  f^{-1}(U) \cap A \right)=f_{|A}^{-1}(U)+f_{|B}^{-1}(U)
$$
is open.

:::



:::{.lemma name=""}

Suppose $f:\Omega_1 \to \Omega_2$ and $g:\Omega_2\to \Omega_3$, $f\circ g$ is continuous if $f$ and $g$ are continuous.

:::
 
:::{.proof}

Suppose $G_3$ is open and the claims follows from $(f\circ g)^{-1}(G_3)=f^{-1}(g^{-1}(G_3))$.

:::

:::{.lemma #contingen name=""}
Suppose $f:(\Omega,\tau),(\Omega',\tau(\mathcal{S}))$, $f$ is continuous iff $f^{-1}(S)\in \tau$ for any $S\in \mathcal{S}$.
:::


$(\Omega,\tau)$ and $(\Omega',\tau')$ are said to be **homeomorphic** if there exist continuous bijection $f$, s.t. $f^{-1}$ is continuous and such $f$ is called **homeomorphism**. In particular, $f$ is an **embedding** if $f:(\Omega,\tau) \to (f(\Omega),\tau|f(\Omega))$ is a homeomorphism.

$f$ is **open** if $f(G)$ is open for all open set $G\in \tau$ and is **closed** if $f(F)$ is closed for all closed set $F^c\in \tau$.

:::{.lemma #homoclopen name=""}
Suppose $f$ is bijection, then it's homeomorphism iff it's continuous and either open or closed.
:::
 
:::{.proof}

By the continuity of $f^{-1}$, since $(f^{-1})^{-1}(G)=f(G)$ for all open set $G$.

$$f^{-1} \text{ is continuous} \iff f(G) \text{ is open} \iff f \text{ is open .}$$

:::

:::{.lemma name=""}

Suppose $f$ is bijection, it's a homeomorphism iff $\tau'$ is the finest topology where $f$ continuous.

:::
 
:::{.proof}

Suppose $f$ is homeomorphism, $T_0$ is another topology where $f$ is continuous. For any $G\in \tau_0$, $f^{-1}(G)\in \tau$ by the continuity of $f^{-1}$,
 $$G= (f^{-1})^{-1}(f^{-1}(G))\in \tau' $$
 That is $\tau'$ is finer than any $\tau_0$.

:::

Note that $\mathcal{P(\Omega)}$ let all $f$ continuous and $\{\emptyset,\Omega\}$ let all $g:\Omega'\to \Omega$ continuous.


## Semicontinuous

$f:\Omega \to \R^*$ is

- **lower semicontinuous** if for any $c\in \R$, the set $\{x\in \Omega:f(x)\le c\}$ is closed.
- **upper semicontinuous** if for any $c\in \R$, the set $\{x\in \Omega:f(x)\ge c\}$ is closed.

Clearly $f$ is lower semicontinuous iff $-f$ is upper and vice versa. Also, $f$ is continuous iff it's both upper and lower semicontinuous.

:::{.lemma name=""}
Suppose $\{f_i\}_{i\in I}$ is family of lower(upper) semicontinuous function then $\sup f_i(\inf f_i)$ is lower(upper) semicontinuous.
:::

:::{.proof}
Note

$$ \{x\in \Omega:\sup f_i(x)\le c\} =\bigcap_{i\in I} \{x\in \Omega:f_i(x)\le c\}$$

is closed.
:::

:::{.lemma name=""}
$f:\Omega \to \R^*$ is

- **lower semicontinuous** iff for any net
  $$ x.\to x \implies \liminf f(x.) \ge f(x) $$
- **upper semicontinuous** iff for any net
  $$ x.\to x \implies \limsup f(x.) \le f(x) $$
  
:::

:::{.proof}
Suppose $f$ is lower semicontinuous and $x.\to x$. For any $c<f(x)$, then $G=\{\omega\in \Omega:f(\omega)c\}$ is open and thus $x.$ eventually in, that is $x.c$ eventually and thus $\liminf f(x.) \ge c$. This implies that $\liminf f(x.)\ge f(x)$.

Conversely, for any $c\in \R$, consider $F=\{\omega\in\Omega:f(\omega)\le c\}$. Then we show that $F$ is closed. Suppose $x.$ is nets in $F$ and converges to some $x\in \Omega$. Then $c\ge \lim\inf f(x.) \ge f(x)$ thus $x$ in $F$ and thus $F$ is closed.
:::

Then we can generalizes Weierstrass' Theorem in corollary \@ref(cor:exvalue).

:::{.theorem name=""}
$f:\Omega \to \R^*$ on a compact set attains a minimum(maximum) value and set of minima(maxima) is compact if it's lower(upper) semicontinuous.
:::

:::{.proof}
Suppose $X$ is compact and $f$ is lower semicontinuous, then for every $c\in f(X)$, $F_c=\{x\in X:f(x)\le c\}$ is closed and $\{F_c:c\in f(X)\}$ has FIP clearly. Note $X$ is compact, $\ker \{F_c:c\in f(X)\}$ is nonempty by \@ref(thm:cptequiv). That is just the set of minima and it's compact since it's closed.
:::

## Comparing topologies

We list some useful properties when comparing topologies, some of them has been mentioned before and proof omitted.

:::{.lemma #weaker name=""}
Suppose $\tau'$ and $\tau$ are two topologies on $\Omega$, then the following are equivalent.

1. $\tau'\subset \tau$
2. Identity mapping $I:x\mapsto x$ from $(\Omega,\tau)$ to $(\Omega',\tau')$ is continuous.
3. $\tau'$ closed set is closed in $\tau$.
4. $x.\overset{\tau}{\to} x\implies x. \overset{\tau'}{\to} x$
5. $\mathop{\text{Cl}}_{\tau}(A) \subset \mathop{\text{Cl}}_{\tau'}(A)$

:::

:::{.lemma name=""}
Suppose $\tau'\subset \tau$, then

1. Every $\tau$ compact set is $\tau'$ compact.
2. Every $\tau'$ continuous function is $\tau$ continuous.
3. Every $\tau$ dense set is $\tau'$ dense.

:::
