## Filter

```{definition, filter, name=""}
A **filter** is a non-empty collection $\mathcal{F}$ of subset in $\Omega$ s.t.

1. $A\in \mathcal{F},A\subset \mathcal{B}\implies \mathcal{B}\in \mathcal{F}$
2. Closed under finite intersection.
3. $\emptyset \notin \mathcal{F}$

```

Note the definition of $\mathcal{F}$ is independent with topology $\tau$. A **free filter** is filter with $\ker \mathcal{F}=\bigcap_{F\in \mathcal{F}}^{}F=\emptyset$. Not free filters are called **fixed**. 

Filter can be formed by taking upward closure of a filter base.

```{definition, base, name=""}
A collection $\mathcal{B}$ of subset in $\Omega$ is a **fiter base** of $\mathcal{}$ or **prefilter** if

1. $\mathcal{B}\subset \mathcal{F}$
2. $\forall N\in \mathcal{F},\exists W\in \mathcal{B}\ni W\subset N$

We say $\mathcal{B}$ generates $\mathcal{F}$, where

$$ \mathcal{\mathcal{F}}=\mathcal{B}^\uparrow=\{X\in \mathcal{P}(\Omega):\exists A\in \mathcal{B}\ni X\supset A\}  $$
```

For example, 

- Suppose $x\in \Omega$ then 
  $$ \mathcal{N}(x)=\{\text{All neighbourhoods of } x\} $$
  
  is a filter on $\Omega$, that is, **neighbourhood filter**, while each neighborhood base is a base for this filter. Note
  
  $$ \tau(x)=\{X\in \tau:x\in X\} $$
  
  is a base for $\mathcal{N}(x)$ and thus $\mathcal{N}(x)=\tau(x)^\uparrow$.

- Suppose $\Omega$ is infinite, the collection of all **cofinite** subsets( subset s with finite complement) is a filter on $\Omega$, such filter is free and called **Frechet filter**.

To assert a collection is a base, we have

```{theorem, defprefilter, name=""}
Let $\mathcal{B}$ be a collection of nonempty subsets. Then $\mathcal{B}$ is a filter base, that is, $\mathcal{B}$ may generates a filter iff

1. The intersection of each finite family of sets in $\mathcal{B}$ inclueds a set in $\mathcal{B}$ 
2. $\mathcal{B}$ is non-empty and $\emptyset \notin \mathcal{B}$.

```

```{proof}
We claim that

$$ \mathcal{\mathcal{F}}=\{X\in \mathcal{P}(\Omega):\exists A\in \mathcal{B}\ni X\supset A\} $$

$\mathcal{F}$ is the filter generated by $\mathcal{B}$.
```

A family of subsets $\mathcal{F}$ is said to have **finite intersection property** if intersection of every finite subfaimily is nonempty. 

Let $\mathcal{A}$ be collection of subsets with finite intersection property, then collection of all finite intersection of $\mathcal{A}$ is a base, we call the filter generated **filter generated by $\mathcal{A}$**. Formally

$$ \mathcal{F}=\{\bigcap_{A \in \mathcal{I}} A:\mathcal{I}\subset \mathcal{A} \text{ and } \mathcal{I} \text{ is finite}\}^\uparrow $$

A filter $\mathcal{F}$ is **finer** than another $\mathcal{G}$ if $\mathcal{F\subset G}$. Clearly, the set of all filters on $\Omega$ is inductively ordered by inclusion. By Zorn's lemma, the set of all filters has maximal filters and we call such fliters **ultrafilters**.

```{lemma, , name=""}
Every fixed ultrafilter of the form

$$ \mathcal{U(x)}=\{x\}^\uparrow $$

for any $x\in \Omega$. And every free ultrafilter contains no finite subsets.
```



To assert a filter is ultra, we have:

```{theorem, ufq, name=""}
Let $A$ be a collection of subsets and $\mathcal{F}$ the filter generates by $A$. If 

$$ \forall X\subset \Omega, \text{either } X\in A \text{ or } X^c \in A $$

then $A$ is an ultrafilter on $\Omega$.
```

```{proof}
Suppose $\mathcal{F}'$ is an ultrafilter include $\mathcal{F}$, we have $\mathcal{F}'\supset A$ clearly. Consider any $X\in \mathcal{F}'$, we claim that $X\in A$ since if $X^c\in A$ then $X^c\in \mathcal{F}'$ as $\mathcal{F}'\supset \mathcal{F}\supset A$ and $X\cap X^c=\emptyset\in \mathcal{F}'$ results in a contradiction. It follows that $A\supset \mathcal{F}'$ and thus $A=\mathcal{F}'$.
```


```{theorem, , name=""}
Every filter $\mathcal{F}$ is the intersection of all the ultrafilter which include $\mathcal{F}$.
```

```{proof}
We claim that

$$ \mathcal{F}=\cap \{\text{ultrafilter generates by } \{x\}:x\in \cap \mathcal{F}\} $$
```

Suppose mappings on a filter:

```{theorem, , name=""}
Let $f$ be a mapping from $\Omega$ to $\Omega'$ and $\mathcal{B}$ a base for a fliter $\mathcal{F}$ on $\Omega$. Then $f(\mathcal{B})=\{f(X)\}_{X\in B}$ is also a base on $\Omega'$. Moreover, if $\mathcal{F}$ is ultra then $f(\mathcal{B})$ also generates an ultrafilter.
```

```{proof}
First assertion is straightforward and the second follows from $\mathcal{B}$ is collection of supset for some $\{x\}$, then $f(\mathcal{B})$ generates the fliter that generates by $\{f(x)\}$.
```

```{theorem, , name=""}
In the same situation as previous theorem. If $\mathcal{B}'$ is a base on $\Omega'$, then $f^{-1}(\mathcal{B}')$ is a base on $\Omega$ iff every set in $\mathcal{B}'$ meets $f(\Omega)$
```

```{proof}
We have 

$$ \Omega\in f^{-1}(\mathcal{B}')\implies f(\Omega)\subset X' $$

for some $X'\in f^{-1}(\mathcal{B}')$, by definition, $\implies$ is immediately.

For $\impliedby$, suppose any finite family $X_i\in \mathcal{B}'$, then

$$ \bigcap_{i=1} f^{-1}(X_i)=f^{-1}(\bigcap_i X_i)\in f^{-1}(\mathcal{B}') $$

Then the claim follows from theorem \@ref(thm:defprefilter). 
```

A point $x\in \Omega$ is said to be a **limit** or a **limit point** of the fliter $\mathcal{F}$ and $\mathcal{F}$ is said to **converge** to $x$, or $\mathcal{F}\to x$, if the neighborhood filter $\mathcal{N}(x)\subset \mathcal{F}$. For filter base $\mathcal{B}$, we define on the filter generated by $\mathcal{B}$, that is, if $\mathcal{N}(x)\subset \mathcal{B}^\uparrow$.

This implies a equivalent definition of finer topology:

$$ \tau \supset \tau'\iff \mathcal{N}_\tau(x)\supset \mathcal{N}_{\tau'}(x) \iff \mathcal{F} \to a \implies \mathcal{F}' \to a  $$

also, an equivalent definition of continuity as follows:

```{theorem, defcontinue, name=""}
$f:(\Omega,\tau)\to (\Omega',\tau')$ is continous at $x$ iff 

$$ \forall \mathcal{F}\to x, f(\mathcal{F})\to f(x) $$
```

```{proof}
By definition, $f(\mathcal{F})\to f(x)$ if

$$\mathcal{N}(f(x))\subset f(\mathcal{F})^\uparrow  $$

That is, for any neighbourhood $N'\in \mathcal{N}(f(x))$, there exist some $A\in \mathcal{F}$ s.t. $f(A)\subset N'$, as $\mathcal{N}(x)\subset \mathcal{F}$ and $f$ is continous at $x$, such $A$ is always exists. Conversely, take $\mathcal{F}=\mathcal{N}(x)$ then the claim is follows 
```

A point $x\in \Omega$ is said to be an **adherent point** of $\mathcal{F}$ if $x$ is an adherent point of every set in $\mathcal{F}$. The **adherence** of $\mathcal{F}$, $\mathop{\text{Adh}}_{\tau}(\mathcal{F})$ or $\overline{\mathcal{F}}$ is the set of all adherent points, thus

$$ \overline{\mathcal{F}}=\bigcap_{X\in F} \overline{X} $$

Define similarly on filter base $\mathcal{B}$ by the filter generated. By definition, we have


$$ \overline{\mathcal{B}}=\bigcap_{X\in B} \overline{X} $$

```{lemma, , name=""}
Suppose $A$ be a subset of $\Omega$, then $x\in \overline{A}$ iff there is a filter $\mathcal{F}$ s.t. $A\in \mathcal{F}$ and $\mathcal{F}$ converges to $x$.
```
 
```{theorem, bnn, name=""}
Suppose $BN(x)$ a neighbourhood base of $x$, then
 
1. $\mathcal{B}$ converges to $x$ iff every set in $BN(x)$ includes a set in $\mathcal{B}$.
2. $x\in \overline{\mathcal{B}}$ iff every set in $BN(x)$ meets every set in $\mathcal{B}$.

```

As consequence, we have

```{corollary, adhlim1, name=""}
$x$ is adherent to a filter $\mathcal{F}$ iff there is $\mathcal{F}'\supset \mathcal{F}$ and converges to $x$
```
```{proof}
$\implies$ follows from taking $\mathcal{F}=BN(x)$. Conversely, $\forall N\in BN(x)$, we have $X'\subset N$ for some $X'\in \mathcal{F'}$, thus for any $X\in \mathcal{F}$, $N\cap X\subset X'\cap X\neq \emptyset$ as $X',X\in \mathcal{F}'$.
```
 
```{corollary, adhlim2, name=""}
Every limit point of $\mathcal{F}$ is adherent to $\mathcal{F}$
```
 
```{proof}
Clearly holds by applying theorem \@ref(thm:bnn).1 and  \@ref(thm:bnn).2.
```
 
```{corollary, adhlim3, name=""}
Every adherent point of an ultra-filter is a limit point of it. 
```
 
```{proof}
Clearly as kernel of ultrafilter is a one point set.
```

Suppose $f:(\Omega,\tau)\to (\Omega',\tau')$, a point $x'\in \Omega'$ is called 

1. a **limit point** of $f$ relative to $\mathcal{F}$ if $f(\mathcal{F})\to x$. 
2. an **adherent point** of $f$ relative $\mathcal{F}$ if it's adherent point of $f(\mathcal{F})$.

```{theorem, , name=""}
Suppose $f:(\Omega ,\tau )\to (\Omega ',\tau ')$

1. $x'$ is a limit point of $f$ relative to $\mathcal{F}$ iff for any $\tau'$ neighbourhood $N'\in \mathcal{N}(x')$, we have $f^{-1}(N')\in \mathcal{F}$.
2. $x'$ is an adherent point of $f$ relative to $\mathcal{F}$ iff for any $\tau'$ neighbourhood $N'\in \mathcal{N}(x')$, it meets $f(X)$ for any $X\in \mathcal{F}$.

```

```{proof}
$x'$ is limit is equivalent to
$$ \mathcal{N}(x')\subset f(\mathcal{F})^\uparrow $$
That is, there exist some $A=f(X)\subset N'$ for any $N'$, followed by $X\subset f^{-1}f(X)\subset f^{-1} (N')$, then the claim follows from the definition of filter.

By theorem \@ref(thm:bnn), $x'$ is adherent to $f(\mathcal{F})$ iff
$$ \forall N'\in BN(x'), \forall X\in \mathcal{F},f(X)\cap N'\neq \emptyset $$
note for any $N'\in N'(x')$, there exist $N'\in BN(x') \ni N'\subset N'$, thus $f(X)\cap N'\neq \emptyset$ also holds. Conversely, making use of $BN(x')\subset N'(x')$.
```

For example, suppose $f:(\mathbb{N},\tau)\to (\Omega',\tau')$ and $\mathcal{F}$ the frechet filter on $\mathbb{N}$. Then $x'$ is limit of $f$ relative to $\mathcal{F}$ iff for all $N'\in N'(x')$, $f^{-1}(N')\in \mathcal{F}\iff f^{-1}(N')^c\subset [0,k] \iff f^{-1}(N')\supset \{n\in\mathbb{N}:n\ge k\}$ for some $k$, that is, $f(n)\in N'$ for any $n\ge k$.

```{theorem, contatx, name=""}
Suppose $f:(\Omega,\tau)\to (\Omega',\tau')$ and let $\mathcal{F}=\mathcal{N}(x)$. By theorm 9, $x'$ is limit of $f$ relative to $\mathcal{N}(x)$ iff for all $N'\in \mathcal{N}(x')$, $f^{-1}(N')\in \mathcal{N}(x) \iff N\subset f^{-1}(N')\iff f(N)\subset N'$ for some $N\in \mathcal{N}(x)$. That is, iff $x'=f(x)$, $f$ is continous at $x$. Such limit points also called limit points of $f$ at $x$.
```

## Net

$(D,\preceq)$ is called a **directed set** if every couple $\{x,y\}$ in which has an upper bound. 

If $\{D_i\}_{i\in I}$ is family of directed set then $D=\prod_{i\in I} D_i$ is also directed under **product direction** defined by $(a_i)_{i\in I}\succeq (b_i)_{i\in I}$ for all $i\in I$.

```{definition, net, name=""}
Let $(D,\preceq)$ be a directed set, $\nu:D\to \Omega$ is called a **net** in $\Omega$ with domain $D$. The directed set is called **index set** of the net and members of $D$ are **indexes**. We often write $\nu$ as $x.$ or $\{x_\alpha\}$.
```

Suppose $A$ a subset of $\Omega$, we say $x.$ **eventually in** $A$ if there exist some $k\in D$ s.t. $x_n \in A$  for all $n\succeq k$. And we say $\nu$ is **frequently** in $A$ if for all $n\in D$, there exist an $n'\succeq n$ s.t. $x_{n'}\in A$. 

```{lemma, , name=""}
If $x.$ not frequently in $A$, then $x.$ eventually in $A^c$. Thus, for any $X\in \Omega$, $x.$ frequently in either $X$ or $X^c$.
```

Suppose $x\in \Omega$, then $x.$ is said **converge** to $x$, or $x.\to x$ if $x.$ eventually in $N$ for all $N\in \mathcal{N}(x)$, i.e., $\mathcal{N}(x)\subset \mathcal{F}(x.)$. The point $x$ is **adherent** to $x.$ if $x.$ frequently in $N$ for all $N\in \mathcal{N}(x)$.

```{theorem, , name=""}
Suppose $A\in (\Omega,\tau)$, then $x\in \overline{A}$ iff it's the limit of some net in the set.
```

```{proof}
$\impliedby$ is clear. $\implies$ follows from we may find a associated net taking value in $A$(since each neighborhood meets $A$) and such net converges to $x$.
```

As with sequence, if $x.$ is bounded, there is

$$ \liminf x.=\sup\inf x. \preceq \limsup x.=\inf \sup x $$

Subnet generalizes subsequence.

```{definition, , name=""}
Suppose $D$ is directed, a subset $B$ of $D$ is called **cofinal** if for any $a \in D$, there exist $b\in B$ s.t. $a\preceq b$. A map $f:D\to A$ is **final** if $f(D)$ is cofinal of $A$.

Let $x.$ and $x.'$ are two nets in $\Omega$ with domains $D$ and $D'$ respectively. We say that $x.'$ is a **subnet** of $x.$ if there exists a final mapping $\varphi:D'\to D$ s.t. $x'_{\alpha}=x_{\varphi(\alpha)}$.
```

```{theorem, evinsub, name=""}
Let $\mathcal{A}$ be a collection of subsets that $x.$ is frequently in. If $\mathcal{A}$ is closed under finite intersection, then there exists a subnet $x'.$ of $x.$ and $x.'$ eventually in every member of $\mathcal{A}$
```

```{lemma, netwithsubnet, name=""}
Suppose $x.'$ is subnet of $x.$, we have

1. $x.\to x\implies x.'\to x$
2. $x$ adherent to $x.'$ $\implies$ $x$ adherent to $x.$.

```

```{theorem, , name=""}
A point $x$ is adherent to $x.$ iff there is a subnet converges to $x$. While $x.\to x$ iff every subnet converges to $x$.
```

```{proof}
$\implies$ is clear by lemma\@ref(lem:netwithsubnet). Conversely, suppose $a$ is not adherent to $x$, there exist a neighborhood $N$ that $x.$ not frequently in, i.e., exist $k$ s.t. $x_n\notin N$ for any $n\ge k$, thus there is no subnet eventually in $N$.

For the second part, $\implies$ is also clear by lemma\@ref(lem:netwithsubnet) and $\impliedby$ comes from taking subnet as itself.
```

A net $x.$ is called **ultranet** or **universal net** if for all $X\in \Omega$, we have either $x.$ eventually in $X$ or $x.$ eventually in $X^c$. Clearly, subnet of ultranet is ultra and

```{lemma, , name=""}
Every net has a ultra subnet.
```
 
```{proof}
Consider collection of $\mathcal{Q}$ s.t. $x.$ is frequently in every member and closed under finite intersection. By Zorn's Lemma, there is a maximal $\mathcal{Q}_0$. By theorem 11, $x.$ has a subnet $x.'$ which eventually in every member of $\mathcal{Q}_0$. We claim that this subnet is ultra since, $\mathcal{Q}_0$ is maximal and thus either $X\in \mathcal{Q}_0$ or $X^c \in \mathcal{Q}_0$.
```

## Nets and filters

Let 

$$ \mathcal{F}(x.)=\{X\in \mathcal{P}(\Omega ): x.\text{ is eventually in } X\}  $$


Then $\mathcal{F}(x.)$ is a filter and we call it the **filter associated with the net $x.$**.

```{theorem, equivassf, name=""}
Associated filter is the upward closure of the net's tail, that is

$$ \mathcal{F}(x.)=\{\{x_b:b\succeq a\}: a\in D\} $$
```

Motivated by the definition of filter that filter is closed under pairwise intersection, let $X\preceq Y\iff X\supset Y$, then any mapping $\nu:\mathcal{F}\to \Omega$ s.t. $\nu(X)\in X$ is a **net associated with the filter $\mathcal{F}$**. 

By definition, we claim that $\mathcal{F}$ is the associated filter of every associated net and $x.$ is an associted net of the associated fiter.





```{theorem, assn, name=""}
Filter $\mathcal{F}\to x$ iff $x.\to x$ for any $x.$ associated with $\mathcal{F}$.
```

```{proof}
Note
$$\forall N\in \mathcal{N}(x), x.\text{ eventually in } N  \iff \mathcal{N}(x)\subset\mathcal{F}(x.)  $$
Then is sufficient to show that $\mathcal{F}(x.)=\mathcal{F}$. It's follows from for any $X\in \mathcal{F}$, $x.$ eventually in $X$.
```

```{theorem, assf, name=""}
$$ x.\to x \iff \mathcal{F}(x.)\to x $$
```
 
```{proof}
Both side is equivalent to $\mathcal{N}(x)\subset \mathcal{F}(x.)$
```

```{theorem, , name=""}
Suppose $f:(\Omega,\tau)\to (\Omega',\tau')$, then $f$ is continous at $x$ iff $\forall x.\to x$, $f(x.)\to f(x)$.
```

```{proof}
By theorem \@ref(thm:assf),\@ref(thm:assn) and \@ref(thm:contatx).
```

By above theorems, we have

$$ \mathop{\text{Adh}}_{}(\mathcal{F(x.)})=\mathop{\text{Adh}}_{}(x.), \mathop{\text{Lim}}_{}(\mathcal{F(x.)})=\mathop{\text{Lim}}_{}(x.)  $$

and similarly results holds for any filter and one of associated nets.

```{lemma, , name=""}
If $x.$ is ultra then the associated filter $\mathcal{F}(x.)$ is also ultra and if $\mathcal{F}$ is ultra, every associated net is ultra.
```
 
```{proof}
Directly from theorm \@ref(thm:ufq).
```


## Convergence

If $\mathcal{F}$ is collection of functions on $X$, $X$ can be seen as functions on $\mathcal{F}$ by $e_x(f)=f(x)$ for each $x \in  X$, such functions are called  **evaluation functional**. 

The product topology on $\R^X$ is also called **topology of pointwise convergence** on $X$ because a net $f.\to f$ iff $e_x(f.)\to e_x(f)\iff f.(x)\to f(x)$ for each $x \in X$.

 There also exist induced topology $\sigma\left( \mathcal{F},X \right)$ on $\mathcal{F}$, which is identical to the subspace  $\R^X |_{\mathcal{F}}$ endowed the product topology. Formally 

$$ \sigma(\mathcal{F},X)=\sigma(\R^X,X)|_{\mathcal{F}} $$

::: {.lemma  name=""}

If $\mathcal{F}$ is total, the function 

$$ x\mapsto e_x:(X,\sigma(X,\mathcal{F}))\to (\R^{\mathcal{F}},\sigma(\R^{\mathcal{F}},\mathcal{F})) $$

is injective and thus an embedding.

:::

::: {.proof}

It's remain to show the continuity.

$$ \begin{aligned}
	 x. \to x &\iff \forall  f \in \mathcal{F}, f(x.) \to f(x) 
	 \\&\iff \forall f \in \mathcal{F}, e_{f}(e_{x.})\to e_f(e_{x})
	 \\&\iff e_{x.}\to e_{x} 
\end{aligned} $$

:::

By Tychonoff theorem \@ref(thm:tychonoff), $\mathcal{F}$ is compact iff $\forall x \in X$, $\{f(x)\}_{f\in \mathcal{F}}$ it's closed and pointwise bounded by borel theorem. 

::: {.definition name=""}

A net $f.$ converges uniformly to $f\in \R^X$ iff $|f.(x)-f(x)|< \epsilon$ eventually for each $x \in X$ after some $f_{\alpha}$ for any $\epsilon$.

:::


::: {.theorem  name=""}

The uniform limit of a continuous net is continuous.

:::


::: {.proof}

Suppose $f.\to f$ uniformly, then for any $x\in X$, for any $\alpha>\alpha_0$
$$ 
|f_\alpha(x)-f(x)|<\epsilon
$$
as $f_\alpha$ is continuous, for any $x. \to x$, for any $\lambda>\lambda_0$
$$ 
|f_\alpha(x_\lambda)-f_\alpha(x)|<\epsilon
$$
also, there is 
$$ 
|f_\alpha(x_\lambda)-f(x_\lambda)|<\epsilon
$$
Hence, we have 
$$ 
|f(x_\lambda)-f(x)|<3\epsilon
$$

Thus, $f(x.)\to f$ and continuity follows.

:::


::: {.theorem #dini name="Dini's Theorem"}

If continuous real function net $f.$ on a compact set converges monotonically to $f$ pointwise, then the net converges to $f$ uniformly.

:::


::: {.proof}

Let $g.=f.-f$, we have $g.\to 0$, $|g.|$ is decreasing as monotone. Then it's sufficient to show that $g.\to g$ uniformly. Note $|g.(x)|<\epsilon$ eventually for any $x \in X$ after, say, $\alpha_x$. By continuity and compactness:

$$ X=\bigcup_{x \in X} |g_{\alpha_x}|^{-1}(B(0,\epsilon))=\bigcup_{x \in J} |g_{\alpha_x}|^{-1}(B(0,\epsilon)) $$

Then we may pick $\alpha_0 \ge \alpha_x$ for all $x\in J$, and for any $\alpha \ge \alpha_0$ and any $x\in X$, suppose $x\in |g_{\alpha_{x_j}}|^{-1}\left( B(0,\epsilon) \right)$
$$ 
\epsilon>|g_{\alpha_{x_j}}(x)|>|g_{\alpha}(x)|
$$
by monotone and thus $g. \to 0$ uniformly.

:::


