## Compactness

::: {.definition  name=""}

A **cover** of a set $K$ is collection of sets whose union includes $K$. A **subcover** is subcollection of a cover and also covers $K$. 

:::

::: {.definition  name=""}

$K$ is **compact** if every open cover has a finite subcover and called **relatively compact** if it's closure is compact. A topology $(\Omega,\tau)$ is **compact** if $\Omega$ is compact.

:::

Compactness is a "topological" property. That is, subset compactness in a subspace iff it's also compact in full space.

::: {.theorem #cptequiv name=""}

Let $(\Omega,\tau)$ be a space, TFAE:

1. $(\Omega,\tau)$ is compact.
2. Every filter(net) has at least one adherent point.
3. Every ultrafilter(ultranet) converges.
4. $\ker \mathcal{F}\neq \emptyset$ For every collection $\mathcal{F}$ of closed sets having FIP.

:::

::: {.proof}

$4\iff 1$ Taking contrapositive:

$$ \neg {\ker \mathcal{F}\neq\emptyset}\equiv\ker \mathcal{F}=\emptyset\equiv\bigcup_{F\in \mathcal{F}} F^c=\Omega $$

And

$$\neg \forall \bigcap_{i}^n F_i=\emptyset \equiv  \exists\bigcup_{i}^n F_i^c=\Omega $$

note that's precisely the definition of compactness.

$1\implies 2$ Suppose filter $\mathcal{F}$, then

$$ \{\overline{F}:F\in \mathcal{F}\} $$

Enjoy finite intersection property by definition, then $\overline{F}$ has at least one adherent point since $\ker \{\overline{F}:F\in \mathcal{F}\}=\overline{\mathcal{F}} \neq \emptyset$ by 4

$2\implies 3$ Clearly by corollary \@ref(cor:adhlim3).

$3 \implies 1$ Suppose $\mathcal{A}$ a family of closed subsets with finite intersection property. Then the filter generates by $\mathcal{A}$ has an ultrafilter with a limit point $x$. Note $x$ is also adherent to $\mathcal{U}$ and thus adherent to $\mathcal{F}$, followed by $x\in A$ for any $A\in \mathcal{A}$, hence $\ker \mathcal{A} \supset \{x\}$. Then the claim follows from 4.

:::

:::{.theorem #cptiscl name=""}

Let $(\Omega , \tau )$ be Hausdorff, then every compact subset and disjoint singleton can be separated by open sets. In particular, compact subset is closed.

:::

:::{.proof}

Suppose $F\subset \Omega$ is compact, for any $x\in \Omega$ not in $F$, by Hausdorff, there is $x\notin U_y$ and $y\notin V_y$. Then $\bigcup_{y\in F} U_y$ cover $F$, there is subcover $U=\bigcup_{i}^n U_{y_i}$ and $V=\bigcup_{i}^n V_{y_i}$ selected from the same family separated $F$ and $\{x\}$.

:::

:::{.theorem #clcpt name=""}

Closed subset is compact in compact topological space.

:::

:::{.proof}

Note any open cover of $F$ plus $F^c$ become a open cover of $\Omega$.

:::

:::{.theorem name=""}

Every compact Hausdorff space is normal.

:::

:::{.proof}

Suppose $A$ and $B$ are closed and thus compact by theorem \@ref(thm:clcpt). For any point $x\in A$, there exist disjoint $V_x \supset B$ and $x\in U_x$ by theorem \@ref(thm:cptiscl). Note $\bigcup_{x\in A} U_x$ cover $A$, there exist subcover $U=\bigcup_i^n U_{x_i}\supset A$ and $V=\bigcap_i^n V_{x_i}\supset B$ separated $A$ and $B$.

:::

:::{.theorem #contcpt name=""}

Suppose $f:(\Omega,\tau ) \to (\Omega',\tau ')$ is continuous, then $f(A)$ is compact if $A$ is compact.

:::

:::{.proof}

For any open cover of $f(A)$:

$$ \cup G_i \supset f(A)\implies f^{-1}(\cup G_i)=\cup f^{-1}(G_i) \supset f^{-1}f(A)\supset A$$

Thus there exist subcover s.t.

$$ \cup_1^n f^{-1}(G_i)=f^{-1}(\cup_1^n G_i)\supset A \implies\cup_1^n G_i\supset ff^{-1}(\cup_1^n G_i)\supset f(A)$$

Which shows that $f(A)$ is compact.

:::

::: {.corollary #contcpthcl name=""}

Let $X$ be compact and $Y$ be Hausdorff and $f:X\to Y$ is continuous bijection, then $f$ is closed.

:::

::: {.proof}

Note $F$ is closed and thus compact as theorem \@ref(thm:clcpt) then $f(F)$ is compact as theorem \@ref(thm:contcpt) and thus closed by theorem \@ref(thm:cptiscl).

:::


As consequence:

:::{.corollary #exvalue name="Extreme value theorem"}

A continuous real valued function defined on a compact space achieves its maximum and minimum values.

:::

:::{.theorem name=""}

Let $X$ be compact and $Y$ be Hausdorff and $f:X\to Y$ is continuous bijection. Then $f$ is homeomorphism.

:::

:::{.proof}

By lemma \@ref(lem:homoclopen) and corollary \@ref(cor:contcpthcl).

:::

### Sequentially compact

A subset $A$ of a topological space is **sequentially compact** if every sequence in $A$ has a subsequence converging to an element of $A$. A topological space is sequentially compact if itself is a sequentially compact set.


::: {.example  name=""}

The open interval $(0,1)$ is not sequentially compact because $\{\frac{1}{n}\}$ has no convergent subsequence.

:::

## Locally compact spaces

::: {.definition #loccpt name=""}

A topological space is **locally compact** if every point has a compact neighborhood.

:::


::: {.definition  name=""}

Subset $A\subset X$ is said **precompact** if $\overline{A}$ is compact.

:::




::: {.theorem #loccptnb name="Compact neighborhood base"}

Let $X$ be Hausdorff, TFAE

1. $X$ is locally compact.
2. Every $x\in X$ has a precompact neighborhood.
3. $X$ has a basis of precompact open sets, i.e., there exist $x\in K^\circ \subset K\subset N$.

:::


::: {.proof}

It's clear that $3\xRightarrow{}2\xRightarrow{}1$ even without Hausdorff, so we show that $1\xRightarrow{}3$.

Begin by open $G$ and compact $K$ neighborhood for $x$ s.t.  $A:=K-G \neq \emptyset$. For any $y\in A$, there is $U_y\cap W_y=\emptyset$ by Hausdorff, where $y\in U_y$ and $x \in W_y \subset K$. Note $A$ is also compact and then there exist:
$$ 
U=\bigcup_{i=1}^k U_{y_i} \supset A
$$
Respectively, consider $W=\bigcap_{i=1}^{k} W_{y_i}$, and we claim that $\overline{W}$ is compact and included in $G$. Compactness is clear as $\overline{V}\subset K$. By theorem \@ref(thm:cptiscl), $\overline{W}\cap U=\emptyset$. Consequently,
$$ 
\overline{W}\cap G^{c}=\overline{W}\cap K\cap G^c=\overline{W}\cap A\subset \overline{W}\cap U=\emptyset
$$
hence $\overline{W}\subset G$.	

::: 

Consequently, that imply the existence of a compact neighborhood base.

::: {.corollary #cloptisloccpt name=""}

Suppose $G$ is open and $F$ is closed in a locally compact Hausdorff space, then $G \cap F$ is locally compact. That implies every closed and open set is locally compact. 

:::


::: {.proof}

Let $x \in G \cap F$, and $N\cap G \cap F$ be neighborhood of $x$ in the subspace, by theorem \@ref(thm:loccptnb), there exist $K$ s.t.
$$ 
x \in K^\circ \subset K\subset N \cap G
$$
Then $F \cap K$ is compact as it's closed in compact Hausdorff subspace $K$. 

:::


::: {.corollary #loccptasnorm name=""}

If $K$ is compact in a locally compact Hausdorff space and $G$ is an open set including $K$, then there is an open $V$ with compact closure s.t.

$$ 
K\subset V\subset \overline{V}\subset G
$$

:::

::: {.proof}

For any $x \in K$, by theorem \@ref(thm:loccptnb), we have 
$$ 
x \in V_x \subset \overline{V_{x}}\subset G
$$
then note 
$$ 
K\subset \bigcup_{i=1}^{k} V_{x_i}=V
$$
we claim that $V$ is desired. Since 
$$ 
\overline{V}=\overline{\bigcup_{i=1}^{k}V_{x_i}}=\bigcup_{i=1}^{k}\overline{V_{x_i}}
$$
is compact and included in $G$.

:::

Locally compact Hausdorff space is very close to a compact Hausdorff space


::: {.definition name=""}

A **Compactification** of a space $X$ is an embedding $i:X \hookrightarrow Y$, where $Y$ is compact and $i(X)$ is dense.

:::


::: {.definition  name=""}

Let $(X,\tau)$ be a space and define $\hat{X}=X\cup \{\infty\}$, with topology $\hat{\tau}$ consisting of sets that:

1. $G\in \tau$.
2. $\infty\in G$ and $\hat{X} - G =X-G \subset X$ is compact.

:::


::: {.theorem  name=""}

If $X$ is Hausdorff and noncompact, then $\hat{X}$ is a compactification.

:::


::: {.proof}

Firstly we show that $\hat{X}$ is a space. By definition, $\emptyset$ and $\hat{X}$ are open clearly. To show it's closed under countable intersection, it suffices to show that $U_1\cap U_2$ is open when $U_1$ and $U_2$ are so. We classify cases by whether $\infty$ occurs.

1. If $\infty\notin U_1\cup U_2$, $U_1\cap U_2\in \hat{\tau}$ as $U_1\cap U_2\in \tau$.
2. If $\infty\in U_1$ and $\infty\notin U_2$, then $X-U_1$ is compact, as $X$ is Hausdorff, $X-U_1$ is closed in $X$ and thus $X-(X-U_1)=U_1-\{\infty\}$ is open in $X$, it follows that $U_1\cap U_2=(U_1-\{\infty\})\cap U_2$ and the same as 1.
3. 
	If $\infty\in U_1\cap U_2$, then
	$$ 
	X-(U_1\cap U_2)=(X-U_1)\cup (X-U_2)
	$$

	is compact as it's union of compact sets and thus $U_1\cap U_2$ is open.

Now we turn to show closed under union. Suppose $\bigcup_{i \in  I}U_i$ is a collection of open sets. If none contain $\infty$, $\bigcup_{i \in  I}U_i$ is open clearly as it's open in $X$. If $\infty\in U_j, \forall j\in J$ for some $J\subset I$. Then

$$ 
X-\bigcup_{i \in  I}U_i=\bigcap_{i\in I}\left( X-U_i \right)
$$

is closed subset of any compact Hausdorff space $X-U_j$ and thus compact. It follows that $\bigcap_{i \in  I}U_i$ is open.

Next, we show that $\iota:X \xrightarrow{} \hat{X}$ is an embedding. It's injective and open clearly and it suffices to show it continuity by lemma \@ref(lem:homoclopen). For open sets  $G$ in $\hat{X}$:

$$ 
\iota^{-1}(G)=\begin{cases}
	G&\infty\notin G\\
	G-\{\infty\}&\infty \in G
\end{cases}
$$

is also open as $G-\{\infty\}=X-(X-G)$ is open have shown above.

To see $\iota(X)$ is dense, it suffices to see $\{\infty\}$ is not open and that follows from definition of $\hat{X}$.

Finally, we show that $\hat{X}$ is compact. Let $\mathcal{G}$ be open cover, then there is some $G\in \mathcal{G}$ contains $\infty$. Note remaining of $\mathcal{G}$ still cover $X-G$ and thus have a finite cover then claim follows easily,


:::


::: {.lemma #loccpt-compactification name=""}

If noncompact $X$ is Hausdorff and locally compact, $\hat{X}$ is also Hausdorff.

:::


::: {.proof}

Let $x_1$ and $x_2$ in $\hat{X}$. If neither is $\infty$, we have desired disjoint neighborhood immediately. If $x_2=\infty$, let $x_1\in U\subset K$ then $U$ and $V=\hat{X}-K$ are what we desired.

:::


::: {.lemma name=""}
 
$\hat{X}$ is not Hausdorff if there is no subset $G$ and $K$ of $X$ s.t. $G\subset K$.

:::


::: {.proof}

Suppose $\hat{X}$ is Hausdorff, then there is $\infty\in U$ s.t. $K=X-U$ is compact and disjoint to some $V$ open in $X$, note

$$ 
\begin{aligned}
	U\cap V=\emptyset&\xRightarrow{}(U-\{\infty\})\cap V=\emptyset
	\\&\xRightarrow{}(X-K)\cap V=\emptyset
	\\&\xRightarrow{}V\subset K
\end{aligned}
$$

:::




::: {.example  name=""}

$\hat{\mathbb{Q}}$ is non Hausdorff as any open sets $G$ of the form $(a,b)\cap \mathbb{Q}$, if it's contained in a compact subset $K$, then $\overline{G}$ would be compact, which contradict to $[a,b]\cap \mathbb{Q}$ is not compact.

:::

::: {.theorem #compactification name=""}

$X$ is locally compact iff $X$ is open of $\hat{X}$.

:::


::: {.proof}

$\impliedby$ comes from corollary \@ref(cor:cloptisloccpt).

$\implies$ Suppose $(\hat{X},\hat{\tau})$ is compactification of Hausdorff $(X,\tau)$. For any $x \in X$, we may pick $x \in  G \subset K$, where $G$ is open and $K$ is compact in $\tau$. Consider $W \in \hat{\tau}$ where $W \cap X=G$, we have 
$$ 
W=W \cap \hat{X}=W \cap \overline{X} \subset \overline{W \cap X}=\overline{G}\subset K\subset X
$$

that implies $x \in X^\circ\implies X^\circ=X$, i.e. $X$ is open.

:::





<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
