## Semicontinuous

$f:\Omega \to \R^*$ is

- **lower semicontinuous** if for any $c\in \R$, the set $\{x\in \Omega:f(x)\le c\}$ is closed.
- **upper semicontinuous** if for any $c\in \R$, the set $\{x\in \Omega:f(x)\ge c\}$ is closed.

Clearly $f$ is lower semicontinuous iff $-f$ is upper and vice versa. Also, $f$ is continuous iff it's both upper and lower semicontinuous.

:::{.lemma name=""}
Suppose $\{f_i\}_{i\in I}$ is family of lower(upper) semicontinuous function then $\sup f_i(\inf f_i)$ is lower(upper) semicontinuous.
:::

:::{.proof}
Note

$$ \{x\in \Omega:\sup f_i(x)\le c\} =\bigcap_{i\in I} \{x\in \Omega:f_i(x)\le c\}$$

is closed.
:::

:::{.lemma name=""}
$f:\Omega \to \R^*$ is

- **lower semicontinuous** iff for any net
  $$ x.\to x \implies \liminf f(x.) \ge f(x) $$
- **upper semicontinuous** iff for any net
  $$ x.\to x \implies \limsup f(x.) \le f(x) $$
  
:::

:::{.proof}
Suppose $f$ is lower semicontinuous and $x.\to x$. For any $c<f(x)$, then $G=\{\omega\in \Omega:f(\omega)c\}$ is open and thus $x.$ eventually in, that is $x.c$ eventually and thus $\liminf f(x.) \ge c$. This implies that $\liminf f(x.)\ge f(x)$.

Conversely, for any $c\in \R$, consider $F=\{\omega\in\Omega:f(\omega)\le c\}$. Then we show that $F$ is closed. Suppose $x.$ is nets in $F$ and converges to some $x\in \Omega$. Then $c\ge \lim\inf f(x.) \ge f(x)$ thus $x$ in $F$ and thus $F$ is closed.
:::

Then we can generalizes Weierstrass' Theorem in corollary \@ref(cor:exvalue).

:::{.theorem name=""}
$f:\Omega \to \R^*$ on a compact set attains a minimum(maximum) value and set of minima(maxima) is compact if it's lower(upper) semicontinuous.
:::

:::{.proof}
Suppose $X$ is compact and $f$ is lower semicontinuous, then for every $c\in f(X)$, $F_c=\{x\in X:f(x)\le c\}$ is closed and $\{F_c:c\in f(X)\}$ has FIP clearly. Note $X$ is compact, $\ker \{F_c:c\in f(X)\}$ is nonempty by \@ref(thm:cptequiv). That is just the set of minima and it's compact since it's closed.
:::

## Comparing topologies

We list some useful properties when comparing topologies, some of them has been mentioned before and proof omitted.

:::{.lemma #weaker name=""}
Suppose $\tau'$ and $\tau$ are two topologies on $\Omega$, then the following are equivalent.

1. $\tau'\subset \tau$
2. Identity mapping $I:x\mapsto x$ from $(\Omega,\tau)$ to $(\Omega',\tau')$ is continuous.
3. $\tau'$ closed set is closed in $\tau$.
4. $x.\overset{\tau}{\to} x\implies x. \overset{\tau'}{\to} x$
5. $\mathop{\text{Cl}}_{\tau}(A) \subset \mathop{\text{Cl}}_{\tau'}(A)$

:::

:::{.lemma name=""}
Suppose $\tau'\subset \tau$, then

1. Every $\tau$ compact set is $\tau'$ compact.
2. Every $\tau'$ continuous function is $\tau$ continuous.
3. Every $\tau$ dense set is $\tau'$ dense.

:::

## Weak topology

Suppose $\{(Y_i,\tau_i)\}_{i\in I}$ a family of topological space and ${ f_i:X\to Y_i }_{i\in I}$. Let $\mathscr{F}$ be the set of all the topologies s.t. $f_i$ is continuous for all $i$. We call $\cap \mathscr{F}$, i.e., the coarsest topology the **induced topology** or **weak topology** or **initial topology** on $X$ by $\{ f_i \}_{i\in I}$. The topology induced by $\{ f_i \}_{i\in I}$ is generated by 
$$ \mathcal{S}=\{f_i^{-1}(G_i):  G_i\in \tau_i \} $$

or

$$ \mathcal{S}=\{f_i^{-1}(G_i):  G_i\in \mathcal{S_i} \} $$

where $\mathcal{S_i}$ is a subbase for $\tau_i$.

:::{.lemma name=""}
A net $x.\to x$ in the weak topology iff $f_i(x.)\to f_i(x)$ for each $i$.
:::

:::{.proof}
$\implies$ is immediately. Conversely, noting sets of the form $\bigcap_1^n f_{i}^{-1}(V_i)$ consist a neighborhood base.
:::

:::{.theorem name=""}
$g$ is $(\tau',\tau)$ continuous iff $f_i\circ g$ continuous for each $f_i$. Where $\tau$ is $\tau(S)$ in above .theorem.
:::
:::{.proof}
$\implies$ is immediately. $\impliedby$, suppose $G\in \tau$,by above .theorem, this implies
$$ G=\cup_I \cap_F X = \cup_I  \cap_F  f_i^{-1}(G_i)       $$
thus $g^{-1}(G)$ is open since $f\circ g^{-1}$ is continuous and thus $g^{-1}(G)= \cup_I  \cap_F g^{-1}f^{-1}(G)= \cup_I  \cap_F (f\circ g)^{-1}(G)$. 
:::

If the family $\mathcal{F}$ consists of real function on $X$, the weak topology is denoted $\sigma(X,\mathcal{F})$. A subbase for $\sigma(X,\mathcal{F})$ consist of

$$ U(f,x,\epsilon)=f^{-1}(B(f(x),\epsilon))=\{y\in X: |f(y)-f(x)|<\epsilon\} $$

where $f\in \mathcal{F},x\in X, \epsilon>0$. $\mathcal{F}$ is said **total** if $\forall f\in \mathcal{F},f(x)=f(y)\implies x=y$. $\sigma(X,\mathcal{F})$ is Hausdorff iff $\mathcal{F}$ is total.

:::{.lemma name=""}
Let $A$ be a subset, then

$$ (A,\sigma(A,\mathcal{F}|_A))=(A,\sigma(X,\mathcal{F})|_A) $$
:::

:::{.proof}
Nets converges in $(A,\sigma(X,\mathcal{F})|_A)$ also converges in $(X,\sigma(X,\mathcal{F}))$, that is $\forall f,f_i(x.)\to x.$ and thus the same as nets converges in $\sigma(A,\mathcal{F}|_A)$. That implies identical mapping is a homeomorphism since $x.\to x \iff I(x.)\to I(x)$.
:::

The weak topology generated by $C(X)$ is also generated by $C_b(X)$ by noting for any $f\in C(X)$,

$$ g(y)=\min \{f(x)+\epsilon,\max \{f(x)-\epsilon,f(y)\}\} $$

is bounded by $B(f(x),\epsilon)$ and $U(g,x,\epsilon)=U(f,x,\epsilon)$.

:::{.theorem name=""}
(X,\tau) is completely regular iff $\tau=\sigma(X,C(X))$
:::
Suppose $\tau=\sigma(X,\mathcal{F})$ and is completely regular, then we claim that $\mathcal{F}=C(X)$.


## Product topology


::: {.theorem #upcont name="Universal property of the Cartesian product"}

Let $X,Y$ and $Z$ be any space and given $f_X:Z\to X$ and $f_Y:Z \to Y$, there exist unique function $f:Z \to X \times Y$ s.t.
$$ 
f_X=\pi_X \circ f \text{ and } f_Y=\pi_Y \circ f
$$

and $f$ is just $(f_X,f_Y)$.

:::

```{=latex}
\begin{center}
	\begin{codi}[tetragonal]
		\obj { Z & |(pb)| X \times Y \\ };
		\obj [above right=of pb] {X};
		\obj [below right=of pb] {Y};
		\mor[swap] pb "\pi_X":-> X;
		\mor[swap] pb "\pi_Y":-> Y;
		\mor [swap]:[dashed] Z "\exists ! f":-> pb;
		\mor :[bend left=15] * "f_X":-> X;
		\mor[swap]:[bend right=15] * "f_Y":-> Y;
	\end{codi}
\end{center}
```



::: {.lemma name=""}

Suppose $\varphi:X \times Y \to Z$ is continuous, for each $x\in X$, define $\hat{\varphi}:Y \to Z$ by $\hat{\varphi}_x(y)=\varphi(x,y)$, then $\varphi_x$ is continuous.

:::


::: {.proof}

Note $\hat{\varphi}_x$ is composition by $Y \overset{i_x}{\to } X \times Y \overset{\varphi}{\to }Z$, so it suffices to show that $i_x$ is continuous. And that is just the product of constant map $Y \to X$ and identity map $Y \to Y$. Then the claim follows as both is continuous.

:::

Also, $\varphi$ is continuous if $\hat{\varphi}$ is continuous as $\varphi$ is composition by

$$ 
\begin{aligned}
X \times Y \xrightarrow{ \hat{\varphi} \times  i } \mathcal{C}(Y,Z) \times Y \xrightarrow{eval} Z
\end{aligned}
$$

Where we should use the truth that product of continuous function is continuous:

::: {.theorem  name=""}

Let $f:X \xrightarrow{} Y$ and $f':X' \xrightarrow{} Y'$ be continuous. Then the product $f \times f': X \times X'\xrightarrow{} Y\times Y'$ is also continuous.

:::


::: {.proof}

Clearly as the factor $X \times X' \xrightarrow{} Y$ is the composition $X \times X' \xrightarrow{\pi_X} X \xrightarrow{f} Y$

:::


Let $((\Omega_i,\tau_i))_{i\in I}$ be family of topological spaces, let $\Omega=\prod_{i\in I} \Omega_i$ and $\pi_i$ be projection mappings from $\Omega$ to $\Omega_i$. The topology $\tau$ induced by $(\pi_i)_{i\in I}$ is called **product topology** on $\Omega$ and denoted by $\prod_{i\in I} \tau_i$. $(\Omega,\tau)$ is called **topological product**. 

A subbase of this topology is all the sets of the form $\pi_i^{-1}(U_i)=\prod_{i\in I} X_i$ where $X_j=\Omega_j$ for all $i \neq j$ and $X_i=U_i$. 

:::{.lemma name=""}

Suppose $G\in \prod \tau_i$, then $\pi_i(G)=\Omega_i$ except a finite set in $I$.

:::

:::{.proof}

By definition, 
$$ G=\bigcup_I \bigcap_F(\prod_{i\in I} X_i) $$
where $X_i=\Omega_i$ for all $i$ but one. Note there is a finitely intersection, that is
$$ G=\bigcup_I (\prod_{i\in I} X_i)  $$
where $X_i=\Omega_i$ for all $i$ but finite exception. And the claim is easily follows.

:::

The product topology satisfy similar universal property if $I$ is finite, that is 


::: {.theorem  name=""}

Given any space $Z$ and $\{f_i:Z\xrightarrow{}\Omega_i\}_{i\in I}$, there exist unique continuous $f:Z \xrightarrow{} \prod_{i\in I}\Omega_i$ s.t. $\forall i\in I,\pi_i \circ f=f_i$.

:::


::: {.proof}

Existence is clear as we may define $f$ by $f(z)_i=f_i(z)$ and $\pi_i \circ f=f_\alpha$ suggests the uniqueness. Then it suffices to show that continuity. Note the product topology has subbasis $\pi_i^{-1}(U_i)$ and
$$ 
f^{-1}(\pi_i^{-1}(U_i))=(\pi_i \circ f)^{-1}(U_i)=f_i^{-1}(U_i)
$$
is open as $f_i$ is continuous.

:::

We call the topology generated by $\{\prod_{i\in I} U_i \}$ **box topology** and it's finer than product topology unless $I$ is finite and can't enjoy universal property. But they still share following property.


::: {.lemma  name=""}

Let $A_i \subset \Omega_i$ for each $i \in I$, then
$$ 
\prod_{i \in I}^{} \overline{A_i}=\overline{\prod_{i \in I}^{} A_i} 
$$
in both product and box topology.

:::


::: {.proof}

$\subset$: Let $(x_i)_{\{i \in I\}} \in \prod_{i \in I} \overline{A_i}$, and $U=\prod_{i \in I}^{} U_i$ be a open neighborhood of which, then $U_i$ is neighborhood of $x_i$ and thus $U_i$ meet $A_i$ in, say, $y_i$, then we may find $(y_i) \in U\cap \prod_{i \in I} A_i$ and thus $(x_i) \in \overline{\prod_{i \in I} A_i }$.

$\supset$: Note product closed set is closed as

$$ 
\left( \prod_{i \in I} F_i \right)^c=\bigcup_{i \in  I} \prod_{i=I}^{} X_i 
$$

Where $X_j=\Omega_j$ for $j\neq i$ and $X_i=F_i^c$, that is open clearly. And the claim follows as closure is minimum.

:::

::: {.lemma  name=""}

$\Omega_i$ is Hausdorff for each $i$ iff so is $\prod_{i \in I} \Omega_j$ in both product and box topology.

:::

::: {.proof}

$\xRightarrow{}$: Pick any different $(x_i)$ and $(x_i')$ in $\prod_{i \in I}\Omega_i$ and suppose $x_\ell \neq x_{\ell}'$ for particular $\ell$ and they can be separated by $U_\ell$ and $U_{\ell}'$. Then $(x_i)$ and $(x_i)'$ can be separated by $\pi_{\ell}^{-1}(U_i)$ and $\pi_{\ell}^{-1}(U_i')$ and thus Hausdorff. For box topology, it's Hausdorff clearly as it's finer than product topology.

$\xLeftarrow{}$: Note Hausdorff property is hereditary and we may treat factor $\Omega_{\ell}$ as subspace by define embedding
$$ 
f_{\ell}(x)_{j}:\Omega_\ell\xrightarrow{}\prod_{i \in I} \Omega_i =\begin{cases}
	x&j= \ell\\
	y_j&j\neq \ell
\end{cases}
$$
where $y_j$ is any fixed point for each $j$. It's continuous and injective certainly, to see it's embedding, it suffices to show that it's open. Suppose any open $U_\ell \subset \Omega_\ell$, then
$$ 
f_\ell(U_\ell)=\pi_\ell^{-1}(U_\ell)\cap f_\ell(\Omega_\ell)
$$
is open in subspace $f_\ell(\Omega_\ell)$.

:::

```{=latex}
\begin{center}
	\begin{codi}[tetragonal]
		\obj { Z & |(pb)| X \times Y \\ };
		\obj [above right=of pb] {X};
		\obj [below right=of pb] {Y};
		\mor[swap] pb "\pi_X":-> X;
		\mor[swap] pb "\pi_Y":-> Y;
		\mor [swap]:[dashed] Z "\exists ! f":-> pb;
		\mor :[bend left=15] * "f_X":-> X;
		\mor[swap]:[bend right=15] * "f_Y":-> Y;
	\end{codi}
\end{center}
```

Thus,$\{\left( x_{i}^\alpha \right)\}_{\{i \in I\}}$ in $X$ converges to some $\left( x_{i} \right)_{i\in I}$ iff its every components converges to the components respectably. A function is called **jointly continuous** if it's continuous w.r.t. the product topology. 


:::{.theorem #CGT name="Closed Graph Theorem"}

Function $f:\left( X,\tau \right)\to \left(Y,\tau\right)$ where $Y$ is compact Hausdorff is continuous iff its graph $\mathop{\text{Gr}}f$ is closed.

:::


:::{.proof}

$\implies$. For any net $\left( x.,y. \right)\to \left( x,y \right)$, we show that $(x,y)\in  \mathop{\text{Gr}}f$. Note $f(x.)=y.\to y$, also, $f(x.)\to f(x)$ by continuity. It follows by $f(x)=y$ since Hausdorff and we finished.

$\impliedby$. Since $Y$ is compact and Hausdorff, $f(x.)$ converges to precisely one point and denoted as $y$. As $\mathop{\text{Gr}}f$ is closed, $y=f(x)$ and hence $f$ is continuous.

:::

Suppose $A_i$ is subset of each $i$, then
$$ \mathop{\text{Cl}}_{\tau}(\prod A_i)=\prod(\mathop{\text{Cl}}_{\tau_i}(A_i)) $$

Thus we have an alternative definition of semicontinuous:

$f:X\to \R^*$ is 

- lower semicontinuous iff its epigraph $\{(x,c):c\ge f(x)\}$ is closed.
- upper semicontinuous iff its hypograph $\{(x,c):c\le f(x)\}$ is closed.


:::{.theorem #tychonoff name="Tychonoff Product Theorem"}
The product topology of a family of topologies $\tau=\prod_{i\in I} \tau_{i}$ is compact iff $\tau_{i}$ is compact for every $i\in I$.


:::


:::{.proof}

$\implies$ is clearly as projection is continuous. 

$\impliedby$, suppose $\mathcal{U}$ is ultrafilter in $\tau$, then $\pi_{i}(\mathcal{U})$ is ultra base and thus converges to some point, say $x_{i}$, then we claim that $\mathcal{U}\to x=(x_{i})_{i \in I}$. Suppose $V$ any neighborhood of $x$, there is

$$ a \in \bigcap_{i \in J} \pi^{-1}_{i}(X_{i}) \subset V $$

where $X_{i}$ is neighborhood of $x_{i}$ and thus belong to  $\pi_{i}(\mathcal{U})^\uparrow$, that implies there is $U\in \mathcal{U}$ s.t. $\pi_{i}(U) \subset X_{i}$, note $U \subset \pi_{i}^{-1}\pi_{i}(U)\subset \pi_{i}^{-1}(X_i)$, then $\pi_{i}^{-1}	(X_i) \in \mathcal{U}$ and thus $V \in \mathcal{U}$. It followed by $x$ is adherent to $\mathcal{U}$ and thus $\mathcal{U}\to x$ as $\mathcal{U}$ is ultra.
:::

As consequence, we have


:::{.theorem name=""}

In the same notations, let $K_{i}$ be compact for each $i$, $G$ is open in  $\tau$ and including $\prod_{i \in I} K_{i}$, then there exist basic open set sandwich by them.

:::


