## Semicontinuous

$f:\Omega \to \R^*$ is

- **lower semicontinuous** if for any $c\in \R$, the set $\{x\in \Omega:f(x)\le c\}$ is closed.
- **upper semicontinuous** if for any $c\in \R$, the set $\{x\in \Omega:f(x)\ge c\}$ is closed.

Clearly $f$ is lower semicontinuous iff $-f$ is upper and vice versa. Also, $f$ is continous iff it's both upper and lower semicontinuous.

```{lemma, , name=""}
Suppose $\{f_i\}_{i\in I}$ is family of lower(upper) semicontinuous function then $\sup f_i(\inf f_i)$ is lower(upper) semicontinuous.
```

```{proof}
Note

$$ \{x\in \Omega:\sup f_i(x)\le c\} =\bigcap_{i\in I} \{x\in \Omega:f_i(x)\le c\}$$

is closed.
```

```{lemma, , name=""}
$f:\Omega \to \R^*$ is

- **lower semicontinuous** iff for any net
  $$ x.\to x \implies \liminf f(x.) \ge f(x) $$
- **upper semicontinuous** iff for any net
  $$ x.\to x \implies \limsup f(x.) \le f(x) $$
  
```

```{proof}
Suppos $f$ is lower semicontinuous and $x.\to x$. For any $c<f(x)$, then $G=\{\omega\in \Omega:f(\omega)c\}$ is open and thus $x.$ eventually in, that is $x.c$ ecventually and thus $\liminf f(x.) \ge c$. This implies that $\liminf f(x.)\ge f(x)$.

Conversely, for any $c\in \R$, consider $F=\{\omega\in\Omega:f(\omega)\le c\}$. Then we show that $F$ is closed. Suppos $x.$ is nets in $F$ and converges to some $x\in \Omega$. Then $c\ge \lim\inf f(x.) \ge f(x)$ thus $x$ in $F$ and thus $F$ is closed.
```

Then we can gennerlizes Weierstrass' Theorem in corollary \@ref(cor:exvalue).

```{theorem, , name=""}
$f:\Omega \to \R^*$ on a compact set attains a minimum(maximum) value and set of minima(maxima) is compact if it's lower(upper) semicontinuous.
```

```{proof}
Supoose $X$ is compact and $f$ is lower semicontinous, then for every $c\in f(X)$, $F_c=\{x\in X:f(x)\le c\}$ is closed and $\{F_c:c\in f(X)\}$ has FIP clearly. Note $X$ is compact, $\ker \{F_c:c\in f(X)\}$ is nonempty by \@ref(thm:cptequiv). That is just the set of minimas and it's compact since it's closed.
```

## Comparing topologies

We list some useful properies when comparing topologies, some of them has been mentioned before and proof omitted.

```{lemma, weaker, name=""}
Suppose $\tau'$ and $\tau$ are two tologies on $\Omega$, then the following are equivalent.

1. $\tau'\subset \tau$  
2. Identity mapping $I:x\mapsto x$ from $(\Omega,\tau)$ to $(\Omega',\tau')$ is continous.
3. $\tau'$ closed set is closed in $\tau$.
4. $x.\overset{\tau}{\to} x\implies x. \overset{\tau'}{\to} x$
5. $\mathop{\text{Cl}}_{\tau}(A) \subset \mathop{\text{Cl}}_{\tau'}(A)$

```

```{lemma, , name=""}
Suppose $\tau'\subset \tau$, then

1. Every $\tau$ compact set is $\tau'$ compact.
2. Every $\tau'$ continous function is $\tau$ continous.
3. Every $\tau$ dense set is $\tau'$ dense.


```
## Weak topology

Suppose $\{(Y_i,\tau_i)\}_{i\in I}$ a family of topological space and ${ f_i:X\to Y_i }_{i\in I}$. Let $\mathscr{F}$ be the set of all the topologies s.t. $f_i$ is continuous for all $i$. We call $\cap \mathscr{F}$, i.e., the corest topology the **induced topology** or **weak topology** or **initial topology** on $X$ by $\{ f_i \}_{i\in I}$. The topology induced by $\{ f_i \}_{i\in I}$ is generated by 
$$ \mathcal{S}=\{f_i^{-1}(G_i):  G_i\in \tau_i \} $$

or

$$ \mathcal{S}=\{f_i^{-1}(G_i):  G_i\in \mathcal{S_i} \} $$

where $\mathcal{S_i}$ is a subbase for $\tau_i$.

```{lemma, , name=""}
A net $x.\to x$ in the weak topology iff $f_i(x.)\to f_i(x)$ for each $i$.
```

```{proof}
$\implies$ is immediately. Conversely, noting sets of the form $\bigcap_1^n f_{i}^{-1}(V_i)$ consist a neighborhood base.
```

```{theorem, , name=""}
$g$ is $(\tau',\tau)$ continuous iff $f_i\circ g$ continuous for each $f_i$. Where $\tau$ is $\tau(S)$ in above theorem.
```
```{proof}
$\implies$ is immediately. $\impliedby$, suppose $G\in \tau$,by above theorem, this implies
$$ G=\cup_I \cap_F X = \cup_I  \cap_F  f_i^{-1}(G_i)       $$
thus $g^{-1}(G)$ is open since $f\circ g^{-1}$ is continuous and thus $g^{-1}(G)= \cup_I  \cap_F g^{-1}f^{-1}(G)= \cup_I  \cap_F (f\circ g)^{-1}(G)$. 
```

If the family $\mathcal{F}$ consists of real function on $X$, the weak topology is denoted $\sigma(X,\mathcal{F})$. A subbase for $\sigma(X,\mathcal{F})$ consist of

$$ U(f,x,\epsilon)=f^{-1}(B(f(x),\epsilon))=\{y\in X: |f(y)-f(x)|<\epsilon\} $$

where $f\in \mathcal{F},x\in X, \epsilon>0$. $\mathcal{F}$ is said **total** if $\forall f\in \mathcal{F},f(x)=f(y)\implies x=y$. $\sigma(X,\mathcal{F})$ is Hausdorff iff $\mathcal{F}$ is total.

```{lemma, , name=""}
Let $A$ be a subset, then

$$ (A,\sigma(A,\mathcal{F}|_A))=(A,\sigma(X,\mathcal{F})|_A) $$
```

```{proof}
Nets converges in $(A,\sigma(X,\mathcal{F})|_A)$ also converges in $(X,\sigma(X,\mathcal{F}))$, that is $\forall f,f_i(x.)\to x.$ and thus the same as nets converges in $\sigma(A,\mathcal{F}|_A)$. That implies identical mapping is a homeoporphism since $x.\to x \iff I(x.)\to I(x)$.
```

The weak topology generated by $C(X)$ is also generated by $C_b(X)$ by noting for any $f\in C(X)$,

$$ g(y)=\min \{f(x)+\epsilon,\max \{f(x)-\epsilon,f(y)\}\} $$

is boundeb by $B(f(x),\epsilon)$ and $U(g,x,\epsilon)=U(f,x,\epsilon)$.

```{theorem, , name=""}
(X,\tau) is completely regular iff $\tau=\sigma(X,C(X))$
```
Suppose $\tau=\sigma(X,\mathcal{F})$ and is compelely regurlar, then we claim that $\mathcal{F}=C(X)$.


## Product topology

Let $((\Omega_i,\tau_i))_{i\in I}$ be family of topological spaces, let $\Omega=\prod_{i\in I} \Omega_i$ and $\pi_i$ be projection mappings from $\Omega$ to $\Omega_i$. The topology $\tau$ induced by $(\pi_i)_{i\in I}$ is called **product topology** on $\Omega$ and denoted by $\prod_{i\in I} \tau_i$. $(\Omega,\tau)$ is called **topological product**. A subbase of this topology is all the sets of the form $\prod_{i\in I} X_i$ where $X_i=\Omega_i$ for all $i$ but one is arbitary open set, or equally, sets of the form $\pi_{i}^{-1}(U_{i})$ where $U_{i}\in \tau_{i}$.

```{lemma, , name=""}

Suppose $G\in \prod \tau_i$, then $\pi_i(G)=\Omega_i$ except a finite set in $I$.

```

```{proof}

By definition, 
$$ G=\bigcup_I \bigcap_F(\prod_{i\in I} X_i) $$
where $X_i=\Omega_i$ for all $i$ but one. Note there is a finitely intersection, that is
$$ G=\bigcup_I (\prod_{i\in I} X_i)  $$
where $X_i=\Omega_i$ for all $i$ but finite exception.

```

Thus,$\{\left( x_{i}^\alpha \right)\}_{\{i \in I\}}$ in $X$ converges to some $\left( x_{i} \right)_{i\in I}$ iff its every components converges to the components respectly. A function is called **jointly continuous** if it's continous w.r.t the product topology. 


```{theorem, CGT, name="Closed Graph Theorem"}

Function $f:\left( X,\tau \right)\to \left(Y,\tau\right)$ where $Y$ is compact Hausdorff is continuous iff its graph $\mathop{\text{Gr}}f$ is closed.

```


```{proof}

$\implies$. For any net $\left( x.,y. \right)\to \left( x,y \right)$, we show that $(x,y)\in  \mathop{\text{Gr}}f$. Note $f(x.)=y.\to y$, also, $f(x.)\to f(x)$ by continuity. It follows by $f(x)=y$ since Hausdorff and we finished.

$\impliedby$. Since $Y$ is compact and Hausdorff, $f(x.)$ converges to precisely one point and denoted as $y$. As $\mathop{\text{Gr}}f$ is closed, $y=f(x)$ and hence $f$ is continuous.

```

Suppose $A_i$ is subset of each $i$, then
$$ \mathop{\text{Cl}}_{\tau}(\prod A_i)=\prod(\mathop{\text{Cl}}_{\tau_i}(A_i)) $$

Thus we have an alternative definition of semicontinuous:

$f:X\to \R^*$ is 

- lower semicontinuous iff its epigraph $\{(x,c):c\ge f(x)\}$ is closed.
- upper semicontinuous iff its hypograph $\{(x,c):c\le f(x)\}$ is closed.


```{theorem, tychonoff, name="Tychonoff Product Theorem"}
The product topology of a family of topologies $\tau=\prod_{i\in I} \tau_{i}$ is compact iff $\tau_{i}$ is compact for every $i\in I$.


```


```{proof}

$\implies$ is clearly as projection is continuous. 

$\impliedby$, suppose $\mathcal{U}$ is ultrafilter in $\tau$, then $\pi_{i}(\mathcal{U})$ is ultra base and thus coverges to some point, say $x_{i}$, then we claim that $\mathcal{U}\to x=(x_{i})_{i \in I}$. Suppose $V$ any neighborhood of $x$, there is

$$ a \in \bigcap_{i \in J} \pi^{-1}_{i}(X_{i}) \subset V $$

where $X_{i}$ is neighborhood of $x_{i}$ and thus belong to  $\pi_{i}(\mathcal{U})^\uparrow$, that implies there is $U\in \mathcal{U}$ s.t. $\pi_{i}(U) \subset X_{i}$, note $U \subset \pi_{i}^{-1}\pi_{i}(U)\subset \pi_{i}^{-1}(X_i)$, then $\pi_{i}^{-1}	(X_i) \in \mathcal{U}$ and thus $V \in \mathcal{U}$. It followed by $x$ is adherent to $\mathcal{U}$ and thus $\mathcal{U}\to x$ as $\mathcal{U}$ is ultra.
```

As consequence, we have


```{theorem, , name=""}

In the same notations, let $K_{i}$ be compact for each $i$, $G$ is open in  $\tau$ and including $\prod_{i \in I} K_{i}$, then there exist basic open set sandwich by them.

```


### Coinduced topology
In the same notations, let $K_{i}$ be compact for each $i$, $G$ is open in  $\tau$ and including $\prod_{i \in I} K_{i}$, then there exist basic open set sandwich by them.

Suppose $\{(\Omega_i,\mathcal{T_i})\}_{i\in I}$ a family of topological space and $\{f_i:(\Omega_i,\mathcal{T_i})\to (\Omega,\tau)\}_{i\in I}$. Let $A$ be the set of all the topologies s.t. $f_i$ is continuous for all $i$. We call the finest of $A$ **topology coinduced** on $\Omega$ by $\{(f_i)\}_{i\in I}$.


Let $R$ an equivalence relation on $\Omega$, $\eta:\Omega\to \Omega/R$ the canonical surjection. The coinduced topology on $\Omega/R$ by $\eta$ is denoted by $\tau/R$ and $(\Omega/R,\tau/R)$ is the quotient space w.r.t $R$.



