## Convergence

If $\mathcal{F}$ is collection of functions on $X$, $X$ can be seen as functions on $\mathcal{F}$ by $e_x(f)=f(x)$ for each $x \in  X$, such functions are called  **evaluation functional**. 

The product topology on $\R^X$ is also called **topology of pointwise convergence** on $X$ because a net $f.\to f$ iff $e_x(f.)\to e_x(f)\iff f.(x)\to f(x)$ for each $x \in X$.

 There also exist induced topology $\sigma\left( \mathcal{F},X \right)$ on $\mathcal{F}$, which is identical to the subspace  $\R^X |_{\mathcal{F}}$ endowed the product topology. Formally 

$$ \sigma(\mathcal{F},X)=\sigma(\R^X,X)|_{\mathcal{F}} $$

::: {.lemma  name=""}

If $\mathcal{F}$ is total, the function 

$$ x\mapsto e_x:(X,\sigma(X,\mathcal{F}))\to (\R^{\mathcal{F}},\sigma(\R^{\mathcal{F}},\mathcal{F})) $$

is injective and thus an embedding.

:::

::: {.proof}

It's remain to show the continuity.

$$ \begin{aligned}
	 x. \to x &\iff \forall  f \in \mathcal{F}, f(x.) \to f(x) 
	 \\&\iff \forall f \in \mathcal{F}, e_{f}(e_{x.})\to e_f(e_{x})
	 \\&\iff e_{x.}\to e_{x} 
\end{aligned} $$

:::

By Tychonoff theorem \@ref(thm:tychonoff), $\mathcal{F}$ is compact iff $\forall x \in X$, $\{f(x)\}_{f\in \mathcal{F}}$ it's closed and pointwise bounded by borel theorem. 

::: {.definition name=""}

A net $f.$ converges uniformly to $f\in \R^X$ iff $|f.(x)-f(x)|< \epsilon$ eventually for each $x \in X$ after some $f_{\alpha}$ for any $\epsilon$.

:::


::: {.theorem  name=""}

The uniform limit of a continuous net is continuous.

:::


::: {.proof}

Suppose $f.\to f$ uniformly, then for any $x\in X$, for any $\alpha>\alpha_0$
$$ 
|f_\alpha(x)-f(x)|<\epsilon
$$
as $f_\alpha$ is continuous, for any $x. \to x$, for any $\lambda>\lambda_0$
$$ 
|f_\alpha(x_\lambda)-f_\alpha(x)|<\epsilon
$$
also, there is 
$$ 
|f_\alpha(x_\lambda)-f(x_\lambda)|<\epsilon
$$
Hence, we have 
$$ 
|f(x_\lambda)-f(x)|<3\epsilon
$$

Thus, $f(x.)\to f$ and continuity follows.

:::


::: {.theorem #dini name="Dini's Theorem"}

If continuous real function net $f.$ on a compact set converges monotonically to $f$ pointwise, then the net converges to $f$ uniformly.

:::


::: {.proof}

Let $g.=f.-f$, we have $g.\to 0$, $|g.|$ is decreasing as monotone. Then it's sufficient to show that $g.\to g$ uniformly. Note $|g.(x)|<\epsilon$ eventually for any $x \in X$ after, say, $\alpha_x$. By continuity and compactness:

$$ X=\bigcup_{x \in X} |g_{\alpha_x}|^{-1}(B(0,\epsilon))=\bigcup_{x \in J} |g_{\alpha_x}|^{-1}(B(0,\epsilon)) $$

Then we may pick $\alpha_0 \ge \alpha_x$ for all $x\in J$, and for any $\alpha \ge \alpha_0$ and any $x\in X$, suppose $x\in |g_{\alpha_{x_j}}|^{-1}\left( B(0,\epsilon) \right)$
$$ 
\epsilon>|g_{\alpha_{x_j}}(x)|>|g_{\alpha}(x)|
$$
by monotone and thus $g. \to 0$ uniformly.

:::

## Locally compact spaces

::: {.definition #loccpt name=""}

A topological space is **locally compact** if every point has a compact neighborhood.

:::


::: {.theorem #loccptnb name="Compact neighborhood base"}

Suppose $(\Omega,\tau)$ is locally compact and Hausdorff, then every neighborhood of $x$ includes a compact neighborhood. Consequently, that imply the existence of a compact neighborhood base.

:::



::: {.proof}

Begin by open $G$ and compact $K$ neighborhood for $x$ s.t.  $A:=K-G \neq \emptyset$. For any $y\in A$, there is $U_y\cap W_y=\emptyset$ by Hausdorff, where $y\in U_y$ and $x \in W_y \subset K$. Note $A$ is also compact and then there exist:
$$ 
U=\bigcup_{i=1}^k U_{y_i} \supset A
$$
Respectively, consider $W=\bigcap_{i=1}^{k} W_{y_i}$, and we claim that $\overline{W}$ is compact and included in $G$. Compactness is clear as $\overline{V}\subset K$. By theorem \@ref(thm:cptiscl), $\overline{W}\cap U=\emptyset$. Consequently,
$$ 
\overline{V}\cap G^{c}=\overline{V}\cap W\cap G^c=\overline{V}\cap A\subset \overline{V}\cap U=\emptyset
$$
hence $\overline{V}\subset G$.	

::: 

::: {.corollary #cloptisloccpt name=""}

Suppose $G$ is open and $F$ is closed in a locally compact Hausdorff space, then $G \cap F$ is locally compact. That implies every closed and open set is locally compact. 

:::


::: {.proof}

Let $x \in G \cap F$, by theorem \@ref(thm:loccptnb), there exist $K_1$ s.t.
$$ 
x \in K_1^\circ \subset K_1 \subset U
$$
Let $N$ be open neighborhood of $x$, then there exist $K_2$:
$$ 
x \in K_2^\circ \subset K_2\subset N \cap K_1^\circ
$$
Then we claim that $F \cap K_2$ is compact as Hausdorff.

:::


::: {.corollary #loccptasnorm name=""}

If $K$ is compact in a locally compact Hausdorff space and $G$ is an open set including $K$, then there is an open $V$ with compact closure s.t.

$$ 
K\subset V\subset \overline{V}\subset G
$$

:::

::: {.proof}

For any $x \in K$, by theorem \@ref(thm:loccptnb), we have 
$$ 
x \in V_x \subset \overline{V_{x}}\subset G
$$
then note 
$$ 
K\subset \bigcup_{i=1}^{k} V_{x_i}=V
$$
we claim that $V$ is desired. Since 
$$ 
\overline{V}=\overline{\bigcup_{i=1}^{k}V_{x_i}}=\bigcup_{i=1}^{k}\overline{V_{x_i}}
$$
is compact and included in $G$.

:::


::: {.definition name=""}

A **Compactification** of a Hausdorff space $X$ is a compact Hausdorff space $\hat{X}$ s.t. $X$ is a homeomorphic to a dense subset of $\hat{X}$

:::

For short, we treat $X$ as an actual dense subset of $\hat{X}$ and $\tau$ a subspace of $\hat{\tau}$.


::: {.theorem #compactification name=""}

$X$ is locally compact iff $X$ is open of $\hat{X}$.

:::


::: {.proof}

$\impliedby$ comes from corollary \@ref(cor:cloptisloccpt).

$\implies$ Suppose $(\hat{X},\hat{\tau})$ is compactification of Hausdorff $(X,\tau)$. For any $x \in X$, we may pick $x \in  G \subset K$, where $G$ is open and $K$ is compact in $\tau$. Consider $W \in \hat{\tau}$ where $W \cap X=G$, we have 
$$ 
W=W \cap \hat{X}=W \cap \overline{X} \subset \overline{W \cap X}=\overline{G}\subset K\subset X
$$
that implies $x \in X^\circ\implies X^\circ=X$, i.e. $X$ is open.

:::




<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
