## Connection

::: {.definition  name=""}

Two subset $A$ and $B$ are said to be **separated** if

$$ 
A \cap \overline{B}=B\cap \overline{A}=\emptyset
$$

:::

Clearly, if disjoint $A$ and $B$ are both open or closed, they are separated.



::: {.definition  name=""}

Two nonempty separated subset $A$ and $B$ are called a **separation** if $A \cup B=X$. 

:::


::: {.lemma  name=""}

Separation are both clopen.

:::


::: {.proof}

Suppose $A$ and $B$ is a separation, then
$$ 
\overline{A}=\overline{A}\cap X=\overline{A}\cap (A \cup B)=(\overline{A}\cap A) \cup (\overline{A}\cap B)=\overline{A}\cap A=A
$$

thus $A$ and $B$ are closed, that implies $A$ and $B$ are open.

:::

::: {.definition  name=""}

Space $X$ is said to be **connected** if the only clopen set is $X$ and $\emptyset$. Not connected space is said to be disconnection. Subset $A$ is said to be $connected$ or $disconnected$ according to the connectedness of their subspace $(A,\tau_A)$

:::

Note separation are clopen, thus $X$ is disconnected iff there exist a separation in $X$.


::: {.theorem #connect-cl name=""}

Suppose $A$ is connected in $X$, then every set $B$ s.t. $A \subset B \subset \overline{A}$ is connected.

:::


::: {.proof}

Suppose $B$ is disconnected and separated by $X$ and $Y$, then

$$ 
A=(A\cap X)\cup (A\cap Y)
$$
also construct a separation, as $A$ is connected, we have, say $A\cap X=\emptyset$ and thus $A \subset Y$. It follows that

$$ 
X \subset B \subset \overline{A} \subset \overline{Y}
$$

whence contradict to $X \cap  \overline{Y}=\emptyset$.

:::


::: {.theorem #connect-union name=""}

Suppose $\{A_i\}_{i\in I}$ is a family of connected subsets, then $A=\bigcup_{i \in  I} A_i$ is connected if $\ker \{A_i\}_{i\in I} \neq \emptyset$.

:::


::: {.proof}

Suppose $A$ is disconnected and separated by $X$ and $Y$, then

$$ 
A_i=A_i\cap A=(A_i\cap X)\cup (A_i \cap Y) 
$$

also construct a separation, as $A_i$ is connected, we have $A_i\cap X=\emptyset$ or $A_i\cap Y=\emptyset$, suppose $I_X + I_Y=I$ and $A_i\cap X=\emptyset$ for $i\in I_X$ and $A_{i}\cap Y=\emptyset$ for $i\in I_Y$. Note $A_i\cap X=\emptyset \xRightarrow{} A_i\cap Y=A_i$ and thus
$$ 
\begin{aligned}
\emptyset&=X \cap Y\supset (X \cap \bigcap_{i \in  I_Y} A_i)\cap (Y\cap \bigcap_{i \in I_X}A_i)\\
&=
\left( \bigcap_{i \in  I_Y} A_i \right) \cap 
\left( \bigcap_{i \in  I_X} A_i \right)\\
&=\ker \{A_i\}_{i \in I}
\end{aligned}
$$

A contradiction.

:::


::: {.theorem #cont-connect name=""}

Suppose $f:X \xrightarrow{} Y$ is continuous, then $f$ bring connected set subset $A \subset X$ to connected subset of $Y$.

:::


::: {.proof}

Suppose $f(A)$ is disconnected and separated by two open set, say, $f(A)\cap U$ and $f(A) \cap V$, where $U,V$ are open in $Y$. That implies $f(A) \subset U\cup V$, note
$$ 
A \subset f^{-1}f(A) \subset f^{-1}(U\cup V)=f^{-1}(U)\cup f^{-1}(V)
$$

thus $A$ is separated by $A\cap f^{-1}(U)$ and $A\cap f^{-1}(V)$, say, $A\cap f^{-1}(U)=\emptyset$, then
$$ 
A \subset f^{-1}(V) \xRightarrow{} f(A)\subset V \xRightarrow{}f(A)\cap U=\emptyset
$$
A contradiction.

:::

::: {.theorem  name=""}

Suppose each of family $\{X_i\}_{i\in I}$ is nonempty, then their product topology $\prod_{i \in I}X_i$ is connected iff each $X_i$ is closed.

:::


::: {.proof}

$\xRightarrow{}$ follows from $\pi_i$ is continuous and theorem \@ref(thm:cont-connect)(uses each $X_i$ is nonempty).

$\xLeftarrow{}$ Firstly, we should prove that in finite case, i.e., when $I$ is finite. By induction, it suffices to show that $X_1\times X_2$ is connected. Pick fixed $z\in X_2$ we have the embedding $f(x):X_1\xrightarrow{}X_1\times X_2=(x,z)$ and thus $D=f(X_1)$ is connected as theorem \@ref(thm:cont-connect). Then for each $x\in X$, define embedding $g_{x}(y)=(x,y)$, let $D_{x}=g_x(X_2)\cup C$, it's connected as theorem \@ref(thm:connect-union), then $X_1\times X_2=\bigcup_{x \in X_1} D_x$ is connected for the same reason.

Now we are ready for the general case. Pick some $(z_i)_{i\in I}\in \prod_{i \in I} X_i$, for each finite collection $S_j \subset I$, let

$$ 
F_{S_j}=\bigcap_{i \notin S_j} \pi_i^{-1}(z_i) \subset \prod_{i \in I}X_i 
$$

Clearly $F_{S_j} \cong \prod_{i \in S_j} X_i$, so it follows that $F_{S_j}$ is connected and $(z_i)\in F_{S_j}$ for each $S_j$, so it follows that

$$ 
F=\bigcup_{j\in J} F_{S_j}
$$
is connected. Then it remains to show that $F$ is dense in $\prod_{i \in I} X_i$ as lemma \@ref(lem:connect-cl). Recall any nonempty basis element of the form $\bigcap_{i \in S_j} \pi_i^{-1}(U_i)$ for some $S_j$ and thus meet $F_{S_j}$($X \times \dots \times X\times U \times \dots \times U \times X\times  \dots \times  X$ and $z \times \dots \times z\times X \times \dots \times X \times z \times  \dots \times  z$), that implies $F$ must be dense.

:::


::: {.definition  name=""}

$A\subset X$ is said **path-connected** if every distinction singleton $a$ and $b$ has a **path** $f:[0,1]\xrightarrow{}A$ s.t. $f(a)=0$ and $f(b)=1$.

:::

::: {.lemma #path-connect name=""}

Path-connected implies connected.

:::


::: {.proof}

Pick any $a_0\in A$, for each other $b\in A$, there exit a path $f_b$, then $f_b(I)$ is connected. Then

$$ 
A=\bigcup_{b\in A} f_b(I)
$$

is connected as theorem \@ref(thm:connect-union).

:::

Path-connected is quite similar to connected.

::: {.theorem  name=""}

1. Image of path-connected spaces are path-connected.
2. Overlapping unions of path-connected spaces are path-connected.
3. Product is path-connected iff every factor is path-connected.

:::


::: {.proof}

We only prove part 3. $\xRightarrow{}$ is trivial. To achieve $\xLeftarrow{}$, for any pair $(x_i)$ and $(y_i)$, there exist path $f_i$ for each $i \in I$, and then we get a continuous path $f=(f_i)$ by the universal property.

:::

The overlapping union property for (path-)connectedness allows us to make the following definition.


::: {.definition  name=""}

Let $x\in X$, **connected component** of $x$ is defined as:
$$ 
C_x=\bigcup_{}\{C|C \text{ is connected and } x\in C\}
$$

Similarly, the **path-component** is

$$ 
PC_x=\bigcup_{} \{C|C \text{ is path-connected and } x\in C\}
$$

:::


::: {.example #Q-is-totally-discont name=""}

Suppose $\mathbb{Q}$ equipped with the subspace topology from $\mathbb{R}$. Then the only connected subsets are singletons, so $C_x=\{x\}$. Such a space is said **totally disconnected**

:::

In the light of connected component is maximum, each component $C_x$ is closed as $\overline{C_x}$ is connected.


::: {.definition  name=""}

Let $X$ be a space, it's **locally connected** if any neighborhood $U$ of any $x$ contains a connected neighborhood. And we define **locally path connected** in a similar way.

:::

::: {.theorem #loc-connected name=""}

Let $X$ be a space. TFAE:

1. $X$ is locally connected.
2. $X$ has a basis consisting of connected open sets.
3. For every open set $G \subset X$, any component $C\subset U$ is open in $X$.

:::


::: {.proof}

$1\xRightarrow{}3$. For any open $G\subset X$ and any $C\subset G$, for any $x\in C$, there exist connected neighborhood $x\in U \subset G$, as $C$ is component, we have $U\subset C$ and thus $C$ is open.

$3\xRightarrow{}1$. Let $G$ be a open neighborhood of $x$, then the component $C_x$ is the desired neighborhood.

$3\xLeftrightarrow{}2$. $3\xRightarrow{}2$ is clear, for the converse, note $2\xRightarrow{}1$ and thus implies $3$.
:::

The property of path-connected is even better.


::: {.theorem #loc-path-connected name=""}

Let $X$ be a space, TFAE:

1. $X$ is locally path-connected.
2. $X$ has a basis consisting of path-connected open sets.
3. For every open $G\subset X$, the path-component of $G$ are open in $X$.
4. For every open set $G\subset X$, every component of $G$ is path-connected and thus a path-component.

:::


::: {.proof}

We only show that $1\xLeftrightarrow{}4$. Suppose $X$ is locally path-connected, and let $P\subset C\subset G\subset X$, where $P,C,G$ are path-component, component and open set respectly. Then $P$ is open.
$$ 
$$


:::




<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>



