# Odds and ends

## Space of sequences

```{definition, seqspace, name=""}
For $1\le p \lt \infty$, $\ell_p$ is defined to be the set of all sequences $x.=(x_1,x_2,\cdots)$ for which $\|x\|_p\lt \infty$. Where 
$$ \|x\|_p=(\sum_1^\infty |x_i|^p)^{1/p} $$
is the **$\ell_p$ norm** of the sequences.

While $\ell_\infty$ is defined as the set of all $\sup \{|x_n|\}\le \infty$, such norm is called **$\ell_\infty$ norm**, **supremum norm** or **uniform norm**.
```

All of these spaces are vector space. And sequence $\{\ell_i\}_{i=1}^\infty$ is increasing.

The space of all convergent sequence is denoted $c$ and all sequences convergent to $0$ is denoted $c_0$. Finally, the collection of sequences with finite nonzero terms is $\varphi$. One can check that

$$ \varphi\subset \ell_p \subset c_0 \subset \ell_\infty \subset \R^n $$

## Spaces of functions

One can think $\R^n$ as 

$$ \{f:\{1,2,\cdots,n\}\to \R\}=\R^n=\R^{\{1,2,\cdots,n\}} $$

Replace $\{1,2,\cdots,n\}$ by an arbitrary $X$, then $\R^X$ is all functions from $X$ to $\R$.

For $1\le p \lt \infty$, $L_p(\mu)$ is defined to be the set of all $\mu$ measurable functions $f$ for which $\|f  \|_p< \infty$, where the **$L_p$ norm** is defined as 

$$ \|f\|_p=(\int_\Omega |f|^p)^{1/p} $$

And the **$L_\infty$ norm**, or **essential supremum** is defined as

$$ \|f\|_\infty=\operatorname{ess}\sup f=\sup \{t:\mu(\{x:|f(x)|\ge t\})0\}  $$

## Ordinals

Suppose $R$ is an order relation on $\Omega$, then $\Omega$ is said to be **inductively ordered** by $R$ if every totally ordered subset has an **supremum**.

**Zorn's Lemma** states that every inductively ordered set has a maximal element.

```{definition, wellord, name=""}
A set $X$ is **well ordered** by linear $\preceq$ if every nonempty subset has a least element. 
```

```{definition, initseg, name=""}
An **initial segement** of $(X,\preceq)$ is any set of the form $I(x)=\{y\in X:y\le x\}$. 
```

```{definition, ideal, name=""}
An **ideal** in a well ordered $X$ is a subset $A$ s.t. forall $a\in A$, $I(a)\subset A$.
```

```{theorem, WOP, name="Well Ordering Principle"}
Every nonempty set can be well ordered.
```

```{proof}
Let $X$ nonempty, and let

$$ \mathcal{X}=\{(A,\preceq_A) \text{ is well order}:A\subset X\} $$

all well ordered sets, and define $\preceq$ on $\mathcal{X}$ as $(B,\preceq_B) \preceq (A,\preceq_A)$ if $B$ is an ideal in $A$ and $\preceq_A$ extends $\preceq_B$. Suppose every chain $\mathcal{C}$ in $\mathcal{X}$, $(\cup \mathcal{C},\cup \{\prec_A:A\in \mathcal{C}\})$ clearly an upper bound of $\mathcal{C}$ and well ordered. By Zorn's lemma, there is a maximal element of $\mathcal{X}$ and it's actually $X$. 
```

Kind of remarkable and useful well ordered set is exist:

```{theorem, usefulorder, name=""}
There exist poset $(\Omega,\preceq )$ satisfy

1. $(\Omega,\preceq)$ is well ordered.
2. $\Omega$ has a greast element $\omega_1$
3. $I(x)$ is countable for $x<\omega_1$
4. $\{y\in \Omega:x\le y\le \omega_1\}$ is uncountable.
5. Every nonempty subset of $\Omega$ has a least upper bound.
6. A nonempty subset of $\Omega-\{\omega_1\}$ has greatst element iff it's countable. Every uncountable subset has least upper bound $\omega_1$.

```

```{proof}
Let $(X,\preceq)$ be uncountable well ordered set, and let $A$

$$ A=\{x\in X: I(x) \text{is uncountable}\} $$

w.l.o.g we may assume $A$ is nonempty. Then there is a first element and denoted by $\omega_1$. Then we show that $\Omega=I(\omega_1)$ enjoy all the properies.

1-4 is straightforward and 5 follows from all the upper bound is well ordered and thus least upper bound exist. For 6, suppose there is a countable $C\subset\Omega-\{\omega_1\}$, then $\bigcup_{i=1}^\infty I(x_i)$ is countable, so there is some $x<\omega_1 \notin \bigcup_{i=1}^\infty I(x_i)$, that is an upper bound. By 5, least upper bound is exist and belong to $C$. Conversely, if some subset $C$ has some least upper bound $b<\omega_1$, then $C\subset I(b)$ and must countable.
```

The elements of $\Omega$ are called **ordinals** and $\omega_1$ is called **first uncountable ordinal**. The elements of $\Omega_0=\Omega-\{\omega_1\}$ is **countable ordinals**. We treat $\N$ as a subset of $\Omega$. Then the first element of $\Omega-\N$ is **first infinite ordinal**.

```{theorem, intlace, name="Interlacing Lemma"}
Suppose sequence $\{x_n\}$ and $\{y_n\}$ in $\Omega_0$ with $x_n\le y_n \le x_{n+1}$. Then they share the same least upper bound.
```

```{proof}
Clearly since $x_n\le y_n \le x_{n+1}$.     
```

