## Product Structure

### Product Topology


::: {.proposition  name="weak topology"}

Suppose there exists a topological space $X$ and a family of topological space $\left\{Y_s\right\}_{s \in S}$, and a family of mappings $\left\{f_s\right\}_{s \in S}$ where $f_{i}:X\to Y_{i}$. In all the topologies on $X$ s.t. $f_s$ is a continuous function for each $s \in S$, there exists a weakest topology which generated by the base consisting of all sets of the form $\bigcap_{i=1} ^{k}f_{s_{i}}^{-1}(V_{i})$ where $s_1,\ldots,s_k\in S$ and $V_{i}$ is a open subset of $Y_{s_{i}}$ for $i=1,2,\ldots,k$.

:::

::: {.proof}

We only prove that the family which consists all the sets of the form $\bigcap_{i=1} ^{k}f_{s_{i}}^{-1}(V_{i})$ is actually a base.

-
    For any $x\in X$, we only need to find a open set $V_s$ containing $f_s(x)$ and notice that $f^{-1}_s(V)\owns x$.

-
    Suppose there exists a $x\in X$ s.t.
    $$ 
    x\in \left(\bigcap_{i=1} ^{k_1}f_{s_{i}}^{-1}(V_{i})\right)\cap \left(\bigcap_{i=1} ^{k_2}f_{s_{i}}^{-1}(V_{i})\right)
    $$
    Notice that $f(x)\in V_{i}$ for all $i$, just for each $V_{i}$, pick a $U_{i}\owns f(x)$ s.t. $U_{i}\subset V_{i}$ and notice that 
    $$ 
    x\in \left(\bigcap_{i=1} ^{k_1}f_{s_{i}}^{-1}(U_{i})\right)\cap \left(\bigcap_{i=1} ^{k_2}f_{s_{i}}^{-1}(U_{i})\right)
    $$
    and the right side is also a member of the family thus it is a base.

:::


Let $\left\{(X_{i},\tau_{i})\right\}$ be a family of topological spaces and let $X=\prod_{i\in I}^{} X_{i}$ denote its Cartesian product. A typical element $x\in X$ is also denoted as $(x_{i})_{i\in I}$ or $(x_{i})$. For each $i\in I$, the **projection** $P_{i}:X\to X_{i}$ is defined by:
$$ 
P_{i}(x)=x_{i}
$$


::: {.definition  name="product topology"}

The product topology on $X=\prod_{i\in I}^{} X_{i}$ is the weak topology on $X$ generated by the family of projections $\left\{P_{i}:i\in I\right\}$, i.e. $\tau$ is the weakest topology that makes $P_{i}$ continuous for each $i\in I$.

Product topology is also called Tychonoff topology.

:::

::: {.proposition  name=""}

The family of all sets $\prod_{i\in I}^{} V_{i}$ where $V_{i}$ is an open subset of $X_{i}$ and $V_{i}\neq X_{i}$ only for finitely many $i\in I$, is a base for Cartesian product $\prod_{i\in I}^{} X_{i}$.

Moreover, if for every $i\in I$ a base $\mathscr{B}_{i}$ for $X_{i}$ is fixed, then the subfamily consisting of those $\prod_{i\in I}^{} V_{i}$ with $V_{i}\in \mathscr{B}_{i}$ whenever $V_{i}\neq X_{i}$, is also a base.

:::

::: {.proof}

As the definition of the weak topology, $\bigcap_{i=1} ^{k}P_{i}^{-1}(V_{i})$ is open in product topology for $V_{i}\in \mathscr{B}_i$ and notice that it is a base of $\prod_{i\in I}^{} X_{i}$. Just need to observe that 
$$ 
P_{j}^{-1}(V_{j})=\prod_{i\in I}^{} V_{i} \mathop{\text{ where }}V_{i}=X_{i} \mathop{\text{ for }}i\neq j
$$
so $\prod_{i\in I}^{} V_{i}$ is open and $\bigcap_{i=1} ^{k}P_{i}^{-1}(V_{i})$ forms the style that $\prod_{i\in I}^{} V_{i}$ where $V_{i}\neq X_{i}$ for only finitely many $V_{i}$.

:::


::: {.remark  name=""}

The base described above is called the canonical base for Cartesian product.

:::

::: {.proposition  name=""}

If $\left\{X_s\right\}_{s \in S}$ is a family of topological space and $\left\{A_s\subset X_s\right\}_{s \in S}$ is a family of subspaces, then two topologies defined on $A=\prod_{s \in S}^{} A_s$, viz., the topology of the Cartesian product of subspaces $\left\{A_s\right\}_{s \in S}$ and the topology of subspace of $\prod_{s \in S}^{} X_s$, coincide.

:::

::: {.proof}

Consider the restrictions $P_s\mid _A:A\to A_s$, 

:::
























