# Vector space

## Basis of vector space

::: {.definition  name=""}

A **vector space** over $\mathbb{K}$ is a nonempty set $X$ with two operations: 
$$
\begin{aligned}
    + &: X\times X \to X\\
    \cdot &: \mathbb{K}\times X \to X
\end{aligned}
$$
and they are closed under them. There exists an element of $X$ denoted as $0$ s.t. $x+0=x$ for all $x\in X$, define $(-x)$ is a vector s.t. $x+(-x)=0$.

:::

Suppose $X$ is a vector space over $\mathbb{K}$, $A,B \subset X$, $\lambda \in \mathbb{K}$, then we denote
$$
\begin{aligned}
    \bm{x}+A&:=\{\bm{x+a}:\bm{a}\in A\}\\
A+B&:=\{\bm{a+b}:\bm{a}\in A,\bm{b}\in B\}\\
\lambda A &:= \{\lambda \bm{a}:\bm{a}\in A\}
\end{aligned}
$$

::: {.definition  name=""}

A **subspace** of a vector space $X$ over $\mathbb{K}$ is any subset of $X$ which is also a vector space over $\mathbb{K}$.

:::

Clearly, a subset $S \subset X$ is a subspace iff $S+S \subset S$ and $\lambda S \subset S$ for any $\lambda$.


::: {.definition  name=""}

A subspace $B$ is called **subspace spanned by a subset $A$** of $X$ consisting of all finite linear combinations of vectors of $A$, i.e., $x\in B$ of the form $x=\sum_{i\in I}^{} \alpha_{i}a_{i}$ where the set $I$ is finite and $\alpha_{i}\in \mathbb{K}$, $a_{i}\in A$, we said that $B=\text{span}A$. 

:::

Clearly, $\mathop{\text{span}}A$ is the intersection of all subspace contain $A$.


::: {.definition  name=""}

A subset $\{\bm{x_i}\}_{1}^{n}$ of a vector space $X$ is said **linearly independent** if the equation
$$
\sum_{i=1}^{n} \alpha_i \bm{x_i}=\bm{0}
$$
only has the trivial solution. Otherwise, the set is **linear dependent**. A subset $S \subset X$ is linearly independent if every finite subset is linearly independent.

:::

### Dimension

::: {.definition  name=""}

If $\{\bm{x_i}\}_{i=1}^{n}$ is linearly independent and $X=\mathop{\text{span}}\{\bm{x_i}\}_{i=1}^{n}$, then $X$ is said to have **dimension** $n$ and denote $\mathop{\text{dim}} X=n$ and $\{\bm{x_i}\}_{i=1}^{n}$ is a **basis** for the linear space. If $X$ does not have a finite basis, we say that it's infinite dimensional.

:::

::: {.theorem  name=""}

Let $X\neq \{0\}$ be a vector space.  
- There exists a Hamel base of $X$ 
- Let $E,F$ be two Hamel bases of $X$. Then $\text{card}E=\text{card}F$.

:::

Clearly, $\mathop{\text{dim}} \mathbb{R}^{n}=n$ and $\mathop{\text{dim}} \ell_p=\infty$.

### Convex sets and convex hull

::: {.definition  name=""}

Let $S$ be a subset of vector space $X$. We say that

- $S$ is **convex** if $\lambda \bm{x}+(1-\lambda)\bm{y} \in S$ whenever $\bm{x,y}\in S$ and $\lambda \in [0,1]$.
- $S$ is **balanced** if $\lambda \bm{x}\in S$ whenever $\bm{x}\in S$ and $\left| \lambda \right|\le 1$.
- $S$ is **absolutely convex** if $S$ is convex and balanced.

:::


::: {.remark}

$S$ is absolutely convex iff $\lambda \bm{x}+\mu \bm{y} \in S$ whenever $\bm{x,y} \in S$ and $\left| \lambda \right|+\left| \mu \right|\le 1$. Clearly, every subspace is absolutely convex.

:::


::: {.definition  name=""}

Let $S$ be a subset of $X$, the **convex hull** of $S$, denoted as $\mathop{\text{conv}} S$, is the intersection of all convex sets in $X$ contains $S$.

:::

::: {.proposition  name=""}

Let $S$ be a subset of $X$. Then
$$
\mathop{\text{conv}}S=\{ \text{convex combinations of } \bm{x_1},\dots,\bm{x_n}\in X \text{ for } n \in \mathbb{N}\}
$$

:::

### Quotient space of vector space

Let $S$ be a linear subspace of $X$ over $\mathbb{K}$. For all $\bm{x,y}\in X$, define
$$
\bm{x} \equiv \bm{y} \left( \mathop{\text{mod}} S \right) \iff \bm{x-y}\in S
$$
Clearly, $\equiv$ defines an equivalence relation on $X$.

For $\bm{x}\in X$, the **coset** of $\bm{x}$ $w.r.t.$ $S$ is
$$
[x]:= \{y \in X:\bm{x \equiv y}\}\left( \mathop{\text{mod}} S \right)=\bm{x}+S
$$
The **quotient space** $X / S$ consists of all equivalence classes $[x]$.

For $\bm{x,y}\in X$ and $\lambda \in \mathbb{K}$, define $+$ and $\cdot$ as:
$$
[\bm{x}]+[\bm{y}]=[\bm{x+y}] \text{ and } \lambda [\bm{x}]=[\lambda \bm{x}]
$$
then $X / S$ is a vector space. The dimension of such space is called **codimension** of $S$ and denote as $\mathop{\text{codim}} S$

### Direct Sums and Projections

::: {.definition  name=""}

Let $Y$ and $Z$ be two subspace of $X$ then $X$ is said to be the **direct sum** of $Y,Z$ if any vector $x\in X$ can be written as 
$$ 
X=Y+Z \text{ and } Y\cap Z=\{\bm{0}\}
$$
If so, we write $X=Y \oplus Z$ and say $Y$ is an **complement** of $Z$ and vice versa.

:::


::: {.proposition  name=""}

Suppose $X=M \oplus N$, then each $\bm{x}\in X$ has a unique representation of the form $\bm{x=m+n}$ for $\bm{m}\in M$ and $\bm{n}\in N$.

:::

Suppose $X=M \oplus N$, then $\mathop{\text{codim}} M=\mathop{\text{dim}} N$ by definition and $\mathop{\text{dim}} X=\mathop{\text{dim}} M+\mathop{\text{dim}} N$.


::: {.definition  name=""}

The operator $P:X\to X$ is called an **projection** if $P$ is linear($P(\alpha \bm{x}+\beta \bm{y})=\alpha P \bm{x}+\beta P \bm{y}$) and idempotent($P^2=P$).

:::


::: {.proposition  name=""}

Suppose $X=M \oplus N$, since we can uniquely write $\bm{x=m+n}$ for each $\bm{x}$, we can well defined $P:\bm{x}\mapsto \bm{m}$, then $P$ is a projection of $X$ onto $M$ along $N$. Moreover $M=P(X)$ and $N=(I-P)X=\ker P$.

:::


:::: {.proof}

Directly by using the unique decomposition $\bm{x=m+n}$.

::::

## Normed space

::: {.definition  name="norm"}

Let $X$ be a vector space over $\mathbb{K}$. A norm on $X$ is a mapping $\|\cdot \|:X\to \mathbb{R}$ with:

- $\|x\|\ge 0$ for all $x\in X$ and $\|x\|=0$ iff $x=0$
- $\|\alpha x\|=\|\alpha\|\|x\|$ for all $\alpha\in \mathbb{K},x\in X$ 
- $\|x+y\|\le \|x\|+\|y\|$ for all  $x,y\in X$

:::

We say two norm $\|\cdot\|$ and $\| \cdot\|_0$ are equivalent if there exists positive $\alpha$ and $\beta$ $s.t.$ for all $\bm{x} \in X$:
$$
\alpha \| \bm{x}\|\le \| \bm{x}\|_0 \le \beta \| \bm{x}\|
$$
and denote $\|\cdot\| \sim \|\cdot\|_0$, clearly $\sim$ is an equivalence relation on the norm space $\mathcal{N}(X)$.

We can show that if $\mathop{\text{dim}} X$ is finite, all norms are equivalent.

### Metric generated by norm

::: {.proposition  name="distance in normed vector space"}

Let $(X,\|\cdot\|)$ be a normed vector space, then the mapping $d:X\times X\to \mathbb{R}$ defined by $d(x,y)=\|x-y\|$ for all $x,y\in X$ is a **distance**(or metric) on $X$.

:::

::: {.proof}

First we need to show that $\big\lvert\|x\|-\|y\|\big\rvert\le \|x-y\|$.  
Assume that $\|x\|\ge \|y\|$, then consider $\|x\|=\|x-y+y\|\le \|x-y\|+\|y\|$, so $\|x\|-\|y\|\le \|x-y\|$, as they all non-negative, $\lvert\|x\|-\|y\|\rvert\le \|x-y\|$ holds.  

- $d(x,y)=\|x-y\|\ge 0$ 
- $d(x,y)=0\implies \|x-y\|=0\implies x=y$ 
- $d(x,y)=\|x-y\|=\|y-x\|=d(y,x)$ 
- $d(x,y)\le d(x,z)+d(y,z)$, note that  $\|x-z\|+\|z-y\|\ge \|(x-z)+(z-y)\|=\|x+y\|$, so for any $x,y,z\in X$, $d(x,y)\le d(x,z)+d(y,z)$  

:::

So we find that  $d(x,y)=\|x-y\|$ is truly a metric on $X$, so $(X,d)$ is a metric topological space. It is also called the **norm topology** of $X$.

Conversely, once we have a metric $d$, then $\| \bm{x}\|=d(\bm{x},\bm{0})$ also define a norm on $X$ if such $d$ is:

- **Translation Invariance** $d(\bm{x,y})=d(\bm{x+z,y+z})$
- **Absolute Homogeneity** $d(\lambda \bm{x}, \lambda \bm{y})=\left| \lambda \right| d(\bm{x,y})$

::: {.theorem  name=""}

Let $X$ be a finite-dimensional vector space over $\mathbb{K}$, and let $(e_i)_{i=1}^{n}$ denote a basis of $X$ :

- 
    For each $p \in [1,\infty]$, the mapping $\|\cdot \|_p$ defined by: 
    $$ 
    \begin{aligned}
        x&=\sum_{i=1}^{n} x_{i}e_{i}\in X\to \|x\|_p=\bigg(\sum_{i=1}^{n} \lvert x_{i} \rvert ^{p}\bigg)^{1 /p} \qquad &&\text{if } p \in [1,\infty) \\
        x&=\sum_{i=1}^{n} x_{i}e_{i}\in X\to \|x\|_{\infty}= \max_{1\le i\le n}\lvert x_{i} \rvert &&\text{if }p=\infty
    \end{aligned}
    $$
    is a norm on $X$. 
- For each $p \in [1,\infty]$, the space $(X,\|\cdot\|_{p})$ is separable.


:::

:::: {.proof}

::: {.theorem  name="Holder's and Minkowski's inequalities"}

- 
    Given a $p \in \mathbb{R}$ s.t. $p>1$, let the real number $q$ be defined by: 
    $$ 
    \frac{1}{p}+\frac{1}{q}=1 \qquad \text{hense }q>1
    $$
    and let $(x_{i})_{i=1}^{\infty}$ and $(y_{i})_{i=1}^{\infty}$ be two sequences of scalers satisfying 
    $$ 
    \sum_{i=1}^{\infty} \lvert x_{i} \rvert ^{p}\lt \infty \text{  and  } \sum_{i=1}^{\infty} \lvert y_{i} \rvert ^{q}\lt \infty
    $$
    Then the series $\sum_{i=1}^{\infty} \lvert x_{i}y_{i} \rvert$ converges and Holder's inequality holds:
    $$ 
    \sum_{i=1}^{\infty} \lvert x_{i}y_{i} \rvert\le \bigg(\sum_{i=1}^{\infty} \lvert x_{i} \rvert ^{p}\bigg) ^{1 /p} \bigg(\sum_{i=1}^{\infty} \lvert y_{i} \rvert ^{q}\bigg) ^{1/q}
    $$
- 
    Give a real number $p\ge 1$ s.t. 
    $$ 
    \sum_{i=1}^{\infty} \lvert x_{i} \rvert ^{p}\lt \infty \text{ and } \sum_{i=1}^{\infty} \lvert y_{i} \rvert ^{p}\lt \infty
    $$
    Then $\sum_{i=1}^{\infty} \lvert x_{i}+y_{i} \rvert ^{p}$ converges and Minkowski's inequality holds: 
    $$ 
    \bigg(\sum_{i=1}^{\infty} \lvert x_{i}+y_{i} \rvert ^{p}\bigg)^{1 /p}\le \bigg(\sum_{i=1}^{\infty} \lvert x_{i} \rvert ^{p}\bigg)^{1 /p}+\bigg(\sum_{i=1}^{\infty} \lvert y_{i} \rvert ^{p}\bigg) ^{1/p}
    $$
    

:::

::: {.proof}

1. 
    If $p>1$ and $\frac{1}{p}+\frac{1}{q}=1$, then 
    $$ 
    \alpha \beta\le \frac{\alpha ^{p}}{p}+\frac{\beta^{q}}{q}\qquad \text{for all $\alpha>0$, $\beta>0$}
    $$
    To see this, note that the convexity of exponential function implies that 
    $$ 
    e^{\theta r+(1-\theta)s}\le \theta e^{r}+(1-\theta)e^{s}
    $$
    for all $\theta\in (0,1)$ and $r,s \in \mathbb{R}$. Now let $\theta=\frac{1}{p},r=p\text{Log}\alpha,s=q\text{Log}\beta$, the first inequality is proved.  

2. 
    Let $\|x\|_{p}=(\sum_{i=1}^{\infty} \lvert x_{i} \rvert ^{p})^{1 /p}$ and $\|y\|_p=(\sum_{i=1}^{\infty} \lvert y_{i} \rvert ^{p})^{1 /p}$. Let $\alpha=\frac{\lvert x_{i} \rvert}{\|x\|_{p}}$ and $\beta=\frac{\lvert y_{i} \rvert}{\|y\|_p}$. Then as shown above: 
    $$ 
    \frac{\lvert x_{i}y_{i} \rvert}{\|x\|_p \|y\|_q}\le \frac{\lvert x_{i} \rvert ^{p}}{p(\|x\|_p)^{p}}+\frac{\lvert y_{i} \rvert ^{q}}{q(\|y\|_q)^{q}}
    $$
    for each $i\in \mathbb{N},i\ge 1$. Then take sum of above inequality: 
    $$ 
    \sum_{i=1}^{n} \bigg(\frac{\lvert x_{i}y_{i} \rvert}{\|x\|_{p} \|y\|_{q}}\bigg)\le \sum_{i=1}^{n} \bigg(\frac{\lvert x_{i} \rvert ^{p}}{p(\|x\|_{p})^{p}}+\frac{\lvert y_{i} \rvert ^{q}}{q(\|y\|_q)^{q}}\bigg)
    $$
    Note that the right side of above:
    $$ 
    \|x\|_p=\bigg(\sum_{i=1}^{\infty} \lvert x_{i} \rvert ^{p}\bigg)^{1 /p}\implies \|x\|_p ^{p}=\sum_{i=1}^{\infty} \lvert x_{i} \rvert ^{p}
    $$
    similar of $\|y\|_{q}$, so
    $$ 
    \frac{\sum_{i=1}^{n} \lvert x_{i} \rvert ^{p}}{p(\|x\|_p)^{p}}=\frac{\sum_{i=1}^{n} \lvert x_{i} \rvert ^{p}}{p(\sum_{i=1}^{\infty} \lvert x_{i} \rvert ^{p})}\le \frac{1}{p}
    $$
    and the same as $\|y\|_q$, so the right side is less than $\frac{1}{p}+\frac{1}{q}=1$, so 
    $$ 
    \sum_{i=1}^{n} \lvert x_{i}y_{i} \rvert\le \|x\|_p \|y\|_q
    $$
    holds for every $n\in \mathbb{N}$ and take the limit $n\to \infty$, the holder's inequality holds.  

3. 
    Note that $\frac{1}{p}+\frac{1}{q}=1\implies p+q=pq\implies p-1=\frac{p}{q}$.
    $$ 
    \begin{aligned}
        \sum_{i=1}^{n} (\lvert x_{i} \rvert+\lvert y_{i} \rvert)^{p}&=\sum_{i=1}^{n} \lvert x_{i} \rvert(\lvert x_{i} \rvert+\lvert y_{i} \rvert)^{p-1}+\sum_{i=1}^{n} \lvert y_{i} \rvert(\lvert x_{i} \rvert+\lvert y_{i} \rvert)^{p-1} 
        \\ &\le \bigg(\sum_{i=1}^{n} \lvert x_{i} \rvert^{p}\bigg)^{1 /p} \bigg(\sum_{i=1}^{n} (\lvert x_{i} \rvert+\lvert y_{i} \rvert)^{p}\bigg)^{1 /q}+\bigg(\sum_{i=1}^{n} \lvert y_{i} \rvert^{p}\bigg)^{1 /p} \bigg(\sum_{i=1}^{n} (\lvert x_{i} \rvert+\lvert y_{i} \rvert)^{p}\bigg)^{1/q} 
        \\ &=\bigg(\sum_{i=1}^{n} (\lvert x_{i} \rvert+\lvert y_{i} \rvert)^{p}\bigg)^{1 /q} \bigg(\bigg(\sum_{i=1}^{n} \lvert x_{i} \rvert^{p}\bigg)^{1 /p}+\bigg(\sum_{i=1}^{n} \lvert y_{i} \rvert^{p}\bigg)^{1/p}\bigg)
    \end{aligned}
    $$
    Note that 
    $$ 
    \bigg(\sum_{i=1}^{n} \lvert x_{i}+y_{i} \rvert^{p}\bigg)^{1 /p}\le \bigg(\sum_{i=1}^{n} (\lvert x_{i} \rvert+\lvert y_{i} \rvert)^{p}\bigg)^{1 /p}
    $$
    so the Minkowski's inequality holds.

:::


Now we prove that $\|x\|_p$ satisfies the triangle inequality.  
$$ 
\|x+y\|_p \le \|x\|_p+\|y\|_p
$$
As shown above, when we prove Minkowski's inequality, before letting $n\to \infty$, we find that
$$ 
\bigg(\sum_{i=1}^{n} \lvert x_{i}+y_{i} \rvert^{p}\bigg)^{1 /p}\le \bigg(\sum_{i=1}^{n} \lvert x_{i} \rvert^{p}\bigg)^{1 /p}+\bigg(\sum_{i=1}^{n} \lvert y_{i} \rvert^{p}\bigg)^{1 /p}
$$
which means $\|x+y\|_p \le \|x\|_p +\|y\|_p$ holds.

Then we prove that $\|x\|_\infty$ is a norm.  

- $\|x\|_\infty=\max_{1\le i\le n}\lvert x_{i} \rvert \ge 0$
- $\|\alpha x\|_\infty=\max_{1\le i\le n}\lvert \alpha x_{i} \rvert=\lvert \alpha \rvert\|x\|_\infty$ 
- 
    $$ 
    \begin{aligned}
        \|x+y\|_\infty &= \max_{1\le i\le n}\lvert x_{i}+y_{i} \rvert\le \max_{1\le i\le n}\lvert x_{i} \rvert+\max_{1\le i\le n}\lvert y_{i} \rvert
        \\ &=\|x\|_\infty+\|y\|_\infty
    \end{aligned}
    $$

::::

Note that when $p=2$, $\|x\|_2$ is the Euclidean distance between point $x\in \mathbb{R}^{n}$ and $0$, and the distance generated by $\|x\|_2$, $d(x,y)=\|x-y\|_2$ is the Euclidean distance between $x$ and $y$.

## Quotient Norm

We now want to introduce a norm on quotient space, suppose $M$is a closed subspace of $X$. For $\bm{x}\in X$, define
$$
\left\| [\bm{x}] \right\|:=\inf_{\bm{y} \in [\bm{x}]} \left\| \bm{y} \right\|
$$
Recall $\bm{y}\in [\bm{x}]$ iff $\bm{y=x+m}$ for some $\bm{m}\in M$ and hence
$$
\left\| [\bm{x}] \right\|=\inf_{\bm{m} \in M} \left\| \bm{x+m} \right\|=\inf_{\bm{m} \in M} \left\| \bm{x-m} \right\|=d(\bm{x},M)
$$
Then one can check that it define a norm on $X / M$ and such norm is called **quotient norm**. The mapping $Q_M:= \bm{x}\mapsto \bm{x}+M$ is called **quotient map**.



## $\ell^{p}$ space and $L^{p}$ space

::: {.theorem #thm-lp-separable name=""}

-   The normed vector space $\ell^{p}$ space is separable if $p \in [1,\infty)$ 
-   The normed vector space $\ell^{p}$ space is not separable if $p=\infty$

:::

::: {.proof}

Let $\mathbb{K}=\mathbb{R}$, and $p \in [1,\infty)$, let
$$ 
A=\bigcup_{n=1} ^{\infty}\{(y_{i})\in \ell^p ;y_{i}\in \mathbb{Q}\mathop{\text{ for }}i\le n,y_{i}=0\mathop{\text{ for }}i\ge n+1\}
$$
Then we show  $\overline{A}=\ell^p$, notice that $\ell^p$ is a metric space and we only need to show that for any $x\in \ell^p$ and any $\epsilon\gt 0$, there exists some $y\in A$ s.t. $\|x-y\|_{p}\le \epsilon$.

Give any $x=(x_{i})\in \ell^p$, there exists a $k\in \mathbb{N}$ s.t. $\sum_{i=k}^{\infty} \lvert x_{i} \rvert^{p}\le \epsilon^{p} /2$, and there exists some $y\in A$ which means $y_{i}\in \mathbb{Q}$ for each $i$ s.t. $\sum_{i=1}^{k-1} \lvert x_{i}-y_{i} \rvert^{p}\le \epsilon^{p} /2$, then for these $x,y\in \ell^p$, we find that $\|x-y\|_{p}\le \epsilon$.

Now give a proof of $\ell^\infty$ space is not separable.  
Give a set 
$$ 
B=\{(x_{i})\in \ell^\infty;x_{i}=0\mathop{\text{ or }}x_{i}=1,i\ge 1\}
$$
is an **uncountable set** since there is a one-to-one and onto mapping:
$$ 
(x_{i})\in B\to \sum_{i=1}^{\infty} \frac{1}{2^{i}}x_{i}
$$
It is one-to-one obviously and onto $[0,1]$ by the binary representation of a real number.  
Now suppose there is a $C \subset \ell^\infty$ s.t. $\overline{C}=\ell^\infty$. Then give any $x\in B$, there exists a $y(x)\in C$ s.t. $\|y(x)-x\|_{\infty}\lt 1 /2$ then the mapping $x\in B\to y(x)\in C$ is a injection  since if $x_1,x_2\in B$ with $x_1\neq x_2$, then $\|x_1-x_2\|_{\infty}=1$, now let $y(x_1)=y(x_2)=y$, we find that $\|x_1-x_2\|_{\infty}\le \|x_1-y\|_{\infty}+\|y-x_2\|_{\infty}$, then we get the contradiction. So if $x_1\neq x_2$, $y(x_1)\neq y(x_2)$, so this mapping must be one-to-one. It means  $\mathop{\text{card}} C \ge \mathop{\text{card}}B$ so $C$ is uncountable.

:::


::: {.definition  name="$L^{p}(\Omega)$"}

Let $\Omega$ is a open subset in $\mathbb{R}^{n}$ thus measurable. Remember that the $L^{1}(A)$ consists of all equivalence classes of real Lebesgue-measurable functions, i.e. those measurable functions $f:\Omega\to [-\infty,\infty]$ that satisfy:
$$ 
\int_\Omega \lvert f(x) \rvert dx \lt \infty
$$
Notice that a function $f:\Omega\to \overline{\mathbb{R}}$ is integrable iff $\int_\Omega \lvert f(x) \rvert dx \lt \infty$.

Now extend this definition. Let $p \in [1,\infty)$, we let $L^p(\Omega)$ denote the set formed by all equivalence classes of measurable functions $f:\Omega\to [-\infty,\infty]$ s.t. $f'=\lvert f \rvert^{p}\in L^1(\Omega)$ which means:
$$ 
\int_\Omega \lvert f(x) \rvert^{p}dx \lt  \infty \qquad \mathop{\text{for some }}p \in [1,\infty)
$$

:::

::: {.theorem  name="Holder and Minkowski's inequality for functions"}

-
    Holder:
    $$ 
    \begin{aligned}
        \frac{1}{p}+\frac{1}{q}&=1 \\
        \int_\Omega \lvert f(x) \rvert^{p}dx \lt  \infty &\mathop{\text{ and }}\int_\Omega \lvert g(x) \rvert^{q}dx \lt \infty \\
        \int_\Omega \lvert f(x)g(x) \rvert dx &\le \bigg(\int_\Omega \lvert f(x) \rvert^{p}dx\bigg)^{1 /p}\bigg(\int_\Omega\lvert g(x) \rvert^{p}dx\bigg)^{1 /q}
    \end{aligned}
    $$

-
    Minkowski:
    $$ 
    \begin{aligned}
        \int_\Omega \lvert f(x) \rvert^{p}dx \lt \infty &\mathop{\text{ and }}\int_\Omega\lvert g(x) \rvert^{p}dx \lt \infty \\
        \bigg(\int_\Omega \lvert f(x)+g(x) \rvert^{p}dx\bigg)^{1 /p}&\le \bigg(\int_\Omega \lvert f(x) \rvert^{p}dx\bigg)^{1/p}+\bigg(\int_\Omega\lvert g(x) \rvert^{p}dx\bigg)^{1 /p}
    \end{aligned}
    $$
    
:::

::: {.proof}

Replace the sum to integral from the sequence Holder and Minkowski's inequality.

:::

As we defined the space $L^p(\Omega)$ above, it is easy to verify that $L^p(\Omega)$ is a vector space and $\|\cdot \|_{p}:f\to \mathbb{R}$ defined by:
$$ 
\|f\|_{p}=\bigg(\int_\Omega \lvert f(x) \rvert^{p}dx\bigg)^{1 /p} \qquad p \in [1,\infty)
$$
Now we define the space $L^\infty(\Omega)$.

::: {.definition  name="$L^\infty(\Omega)$ space"}

-
    $L^\infty(\Omega)$ space denote the set of all measurable functions $f:\Omega\to [\infty,\infty]$ that satisfy:
    $$ 
    \inf\{C\ge 0;\lvert f \rvert\le C \mathop{\text{ a.e. in }}\Omega\}\lt \infty
    $$
    
-
    The norm $\|\cdot \|_{\infty}$ on $L^\infty(\Omega)$ is defined:
    $$ 
    \|f\|_{\infty}=\inf\{C\ge 0;\lvert f \rvert\le C \mathop{\text{ a.e. in }}\Omega\}
    $$

:::


::: {.definition  name="essential supremum"}

Give a measurable function $f:\Omega\to [-\infty,\infty]$, the extended real number
$$ 
\inf\{C\ge 0;\lvert f \rvert\le C \mathop{\text{ a.e. in }}\Omega\}\in [0,\infty]
$$
is called the **essential supremum** of $f$.

Notice that $L^\infty(\Omega)$ space consists of all equivalence class of measurable functions whose essential supremum is finite.

:::


::: {.theorem  name=""}

Let $\Omega$ is a open subset of $\mathbb{R}^{n}$, define the space
$$ 
\mathcal{C}_c(\Omega)=\{g\in \mathcal{C}(\Omega); \mathop{\text{ supp $g$ is compact in $\Omega$}}\}
$$
Then, for each $p \in [1,\infty)$, the subspace $\mathcal{C}_c(\Omega)$ is dense in $L^p(\Omega)$.

:::

::: {.proof}

To prove that $\mathcal{C}_c(\Omega)$ is a dense set, we need to show that for every $f\in L^p(\Omega)$, give any $\epsilon\gt 0$, we have some $g\in \mathcal{C}_c(\Omega)$ s.t. $\|f-g\|_{p}\le \epsilon$.

1.
    There exists a measurable simple function $s=s(f,\epsilon)$ s.t. 
    $$ 
    \mu (\{x\in \Omega;s(x)\neq 0\})\lt \infty \mathop{\text{ and }}\|f-s\|_{p}\le \epsilon /2
    $$
    to achieve this, assume that $f\ge 0$ then there exists a sequence of simple function with:
    $$ 
    0\le s_k\le f \mathop{\text{ for all }}k\ge 1 \mathop{\text{ and }}(s_k)\nearrow f \mathop{\text{ pointwise}}
    $$
    Notice that $f\in L^p(\Omega)$, which means $\int_\Omega \lvert f(x) \rvert^{p}dx\lt \infty$. As $s_k\le f$ holds for every $k\in \mathbb{N}$, $s_k\in L^p(\Omega)$. So $\mu (\{x\in \Omega;s_k(x)\neq 0\})\lt \infty$ as the definition of the integral over a simple function.  
    As $(s_k)\nearrow f$, notice that $\lvert (f-s_k) \rvert^{p}\le \lvert f \rvert^{p}$ and $\lvert f-s_k \rvert^{p}\to 0$ when $k\to \infty$, using Lebesgue's dominated convergence theorem:
    $$ 
    \int_\Omega \lim_{k\to \infty}\lvert f-s_k \rvert^{p}=\lim _{k\to \infty}\int_\Omega\lvert f-s_k \rvert^{p}=0
    $$
    so we can find some $k$ s.t. $\int_\Omega \lvert f-s_i \rvert^{p}\le (\epsilon /2)^{p}$ for all $i\ge k$, so there exists some $s=s(f,\epsilon)$ s.t. $\|f-s\|_{p}\le \epsilon /2$.

2.
    Let $s=s(f,\epsilon)$ be the measurable simple function constructed in step 1. Then there exists a function $g=g(s,\epsilon)=g(f,\epsilon)\in \mathcal{C}_c(\Omega)$ s.t. 
    $$ 
    \|s-g\|_{p}\le \epsilon /2
    $$
    Since $\mu (\{x\in \Omega;s(x)\neq 0\})\lt \infty$, Lusin's property implies that there exists a function $g\in \mathcal{C}_{c}(\Omega)$ that satisfies 
    $$ 
    \sup_{x\in \Omega}\lvert g(x) \rvert\le \|s\|_{\infty}
    $$
    $$ 
    \mu (\{x\in \Omega;g(x)\neq s(x)\})\le \bigg(\frac{\epsilon}{4\|s\|_{\infty}}\bigg)^{p}
    $$
    Then 
    $$ 
    \|s-g\|_{p}=\bigg(\int_A \lvert s-g \rvert^{p}\bigg)^{1 /p}
    $$
    Notice that $\lvert s-g \rvert\le 2\|s\|_{\infty}$ as $\sup\lvert g(x) \rvert\le \|s\|_{\infty}$, and $A$ denotes the set $\{x\in \Omega;g(x)\neq s(x)\}$, so the integral above is less than $2\|s\|_{\infty}\cdot \mu A\le \epsilon /2$.

As shown above, give $\epsilon\gt 0$ and $f\in L^p(\Omega)$ there is a $g(f,\epsilon)$ s.t. $\|f-g\|_{p}\le \|f-s_k\|_{p}+\|s_k-g\|_{p}\le \epsilon /2 +\epsilon/2=\epsilon$.

:::


::: {.theorem  name=""}

1.  $L^p(\Omega)$ is separable if $p \in [1,\infty)$ 
2.  $L^\infty(\Omega)$ is not separable.

:::

::: {.proof}

1.
    Let a $f\in L^p(\Omega)$ where $p \in [1,\infty)$ then there exists a $g=g(f,\epsilon)\in \mathcal{C}_{c}(\Omega)$ s.t. 
    $$ 
    \|f-g\|_{p}\le \epsilon /2
    $$
    Since $K=\mathop{\text{supp}}g$ is compact, there exists a bounded open set $U$ s.t. $K\subset U\subset \Omega$.
    As $U$ is bounded, $\overline{U}$ is bounded too, so $g$ is uniformly continuous on  $\overline{U}$, then there exists $\delta_0\gt 0$ s.t. 
    $$ 
    \lvert g(x)-g(y) \rvert\le \frac{\epsilon}{2(\mu (U))^{1 /p}} = \epsilon'
    $$
    for all $x,y\in \overline{U}$ s.t. $\|y-x\|_{\infty}\lt \delta_0$  
    As the compactness of $K$ and the property of distance function, there exists $\delta_1\gt 0$ s.t. 
    $$ 
    \{y\in \mathbb{R}^{n};\|y-x\|_{\infty}\lt \delta_1\} \subset U \mathop{\text{ for all }}x\in K
    $$
    Let $\delta\in \mathbb{Q}$ s.t. $0\lt \delta \le \min_{}\{\delta_0,\delta_1\}$.  
    Let $(B_{i})_{i\in I}$ denote the countable family formed by all open balls:
    $$ 
    \bigg\{y\in \mathbb{R}^{n};\|x-y\|_{\infty}\lt \frac{\delta}{2}\mathop{\text{ with }}x_{j}=p_{j}\delta\mathop{\text{ for some }}p_{j}\in \mathbb{Z},j\in [1,n]\bigg\}
    $$
    Now pick the subfamily $(B_{i})_{i\in I(K)}$ s.t. for any  $i\in I(K)$, $B_{i}\cap K\neq \varnothing$.
    Then for each $i\in I(K)$, notice that $\delta /2$ makes sure that $\mathop{\text{diam}}(B_{i}\cap K)\le \delta\le \delta_0$, so if $x\in K$, then $B_{i}\subset U$ and $\lvert g(y_1)-g(y_2) \rvert \le \epsilon'$ for every $y_1,y_2\in B_{i}$ since the property of uniform continuous. If $x\notin K$, then  as its minimum is $0$, we can also pick some $\alpha_{i}$ as blow:  
    we pick some $\alpha_{i}\in \mathbb{Q}$ s.t. 
    $$ 
    \lvert g(y)-\alpha_{i} \rvert\le \epsilon' \mathop{\text{ for all }}y\in B_{i}
    $$
    Now we can construct a simple function:
    $$ 
    h=\sum_{i\in I(K)}^{} \alpha_{i}\bm{\mathbf{1}}_{B_{i}}
    $$
    which satisfies that $\lvert h(x)-g(x) \rvert\le \epsilon'$ for almost all $x\in U$ s.t. 
    $$ 
    \|h-g\|_{p}=\bigg(\int_U \lvert h-g \rvert^{p}\bigg)^{1 /p}\le (\mu (U))^{1 /p}\cdot \frac{\epsilon}{2(\mu (U))^{1 /p}}=\frac{\epsilon}{2}
    $$
    Notice that $\|f-g\|_{p}+\|g-h\|_{p}\ge \|f-h\|_{p}$, so $\|f-h\|_{p}\le \epsilon$ and as $h$ is simple and $\alpha_{i}\in \mathbb{Q}$, so $h$ is countable as $I(K)$ is always a finite subset of a countable set and $\mathbb{Q}$ is a countable set. So $L^p(\Omega)$ is separable.


:::


## More about $L^p(\Omega)$ *

::: {.definition  name="Locally integrable"}

Let $\Omega$ be a open subset s.t. $\Omega\subset \mathbb{R}^{n}$.  
A function $f:\Omega\to [-\infty,\infty]$ is said to be locally integrable if $f$ is measurable and the restriction $f\mid _K$ of $f$ on any compact subset $K\subset \Omega$ belongs to $\mathcal{L}^{1}(K)$.  

As the usual method, we construct a quotient set 
$$ 
L^p_{loc}(\Omega)=\mathcal{L}^{p}_{loc}(\Omega)/\mathcal{R}
$$
where $\mathcal{R}$ is the a.e. equivalence.

:::

Note that in this chapter we change the notations of norm. For example, a $L^p(\Omega)$ norm of $f$ is noted as 
$$ 
\|f\|_{L^p(\Omega)}=\bigg(\int_\Omega \lvert f \rvert^{p}\bigg)^{1 /p}
$$
Usually we use the Lebesgue measure $\mu$ and if so we don't show it in the integral.

Notice that every $f\in L^p(\Omega),p \in [1,\infty]$ is locally integrable in $\Omega$ since for any compact $K\subset \Omega$ :
$$ 
\int_K \lvert f(x) \rvert \le \|f\|_{L^1(\Omega)}\lt \infty
$$
and as Holder's inequality:
$$ 
\begin{aligned}
    \int_K \lvert f \rvert &\le \bigg(\int_K\bigg)^{1 /q} \bigg(\int_K \lvert f \rvert^{p}\bigg)^{1 /p} \\
    &\le \bigg(\int_K\bigg)^{1 /q} \|f\|_{L^p(\Omega)} \\
    &\lt \infty
\end{aligned}
$$
with $\frac{1}{p}+\frac{1}{q}=1$.

::: {.definition  name="family of mollifiers"}

A **family of mollifies** in $\mathbb{R}^{n}$ is a family $(\omega_\epsilon)_{\epsilon\gt 0}$ of functions $\omega_\epsilon:\mathbb{R}^{n}\to \mathbb{R}$ of the form
$$ 
\omega_\epsilon(x)=\frac{1}{\epsilon^{n}}\omega\bigg(\frac{x}{\epsilon}\bigg), \qquad x\in \mathbb{R}^{n}
$$
where $\omega:\mathbb{R}^{n}\to \mathbb{R}$ is any functions with following properties:
$$ 
\begin{aligned}
    \omega\in \mathcal{C}^{\infty}(\mathbb{R}^{n}) ,\ \omega(x)\ge 0 &\mathop{\text{ for all }}x\in \mathbb{R}^{n} \\
    \mathop{\text{supp}}\omega\subset \overline{B_1(0)} & \mathop{\text{ and }}\int_{\mathbb{R}^{n}}\omega =1
\end{aligned}
$$
Hence for each $\epsilon\gt 0$,
$$ 
\begin{aligned}
    \omega_\epsilon\in \mathcal{C}^{\infty}(\mathbb{R}^{n}),\ \omega_\epsilon \ge 0 &\mathop{\text{ for all }}x\in \mathbb{R}^{n} \\
    \mathop{\text{supp}}\omega_\epsilon\subset \overline{B_\epsilon(0)} &\mathop{\text{ and }}\int_{\mathbb{R}^{n}}\omega_\epsilon=1
\end{aligned}
$$
:::

::: {.definition  name="regularizing family of $f$"}

Let $\Omega$ be a open subset of $\mathbb{R}^{n}$. Give a function $f\in L^1_{loc}(\Omega)$ and a family $\left( \omega_\epsilon \right)_{\epsilon\gt 0}$ of mollifiers, define the set $\Omega_\epsilon$ and $f_\epsilon:\Omega_\epsilon\to \mathbb{R}$ :

$$ 
\begin{aligned}
    \Omega_\epsilon &= \left\{ x\in \Omega; \mathop{\text{dist}}\left( x,\mathbb{R}^{n}-\Omega \right)\gt \epsilon \right\} \\
    f_\epsilon\left( x \right)&= \int_\Omega \omega_\epsilon\left( x-y \right)f\left( y \right)dy \qquad \mathop{\text{for all }}x\in \Omega_\epsilon
\end{aligned}
$$
Then the family $\left( f_\epsilon \right)_{\epsilon\gt 0}$ is called a regularizing family of $f$.

:::

Notice that $\mathop{\text{dist}}(x,\mathbb{R}^{n}-\Omega)$ is a continuous function thus $\Omega_\epsilon$ is a open set and for every $x\in \Omega_\epsilon$, the ball $\overline{B_{\epsilon}(x)}\subset \Omega$ which means $f_\epsilon(x)$ is well-defined on $\Omega$. Then
$$ 
\begin{aligned}
    f_\epsilon(x)&= \int_{B_{\epsilon}(x)}\omega_\epsilon(x-y)f(y)dy=\int_{B_{0}(\epsilon)}\omega(z)f(x-z)dz \\
    &= \frac{1}{\epsilon^{n}}\int_{B_{1}(x)}\omega\left(\frac{x-y}{\epsilon}\right)f(y)dy \\
\end{aligned}
$$


::: {.theorem  name=""}

1.  
    Let $\Omega$ be an open subset of $\mathbb{R}^{n}$, and let a function $f\in L^1_{loc}(\Omega)$ and a regularizing family $(f_\epsilon)_{\epsilon\gt 0}$ of $f$ is given. Then:
    $$ 
    f_\epsilon\in \mathcal{C}^{\infty}_{}(\Omega_\epsilon) \mathop{\text{ for all }}\epsilon \gt 0
    $$
    Moreover,
    $$ 
    \begin{aligned}
        \partial ^{\alpha}f_\epsilon(x)&= \int_\Omega \partial ^{\alpha}\omega_\epsilon(x-y)f(y)dy \\
        &= \int_{B_{\epsilon}(x)}\partial ^{\alpha}\omega_\epsilon(x-y)f(y)dy \\
    \end{aligned}
    $$
    at each $x\in \Omega_\epsilon$. For any multi-index $\alpha=(\alpha_1,\alpha_2,\ldots,\alpha_n)$ with $\left|\alpha\right|=\sum_{i=1}^{n} \alpha_{i}\ge 1$.

2.
     Assume in addition that $f\in \mathcal{C}^{m}_{}(\Omega)$ for some integer $m \ge 1$. Then, given any compact subset $K\subset \Omega$ there exists $\epsilon_0=\epsilon_0(K)\gt 0$ s.t. $K\subset \Omega_\epsilon$ for all $0\lt \epsilon\le \epsilon_0$, $f_\epsilon(x)$ is well-defined for all $x\in K$ and 
     $$ 
     \sup_{x\in K}\left|\partial ^{\alpha}f_\epsilon(x)-\partial ^{\alpha}f(x)\right|\to 0 \mathop{\text{ for all }}\left|\alpha\right|\le m
     $$
     as $\epsilon\to 0$.

:::

::: {.theorem  name=""}

Give an open subset $\Omega\subset \mathbb{R}^{n}$. For each $p \in [1,\infty)$, the space $\mathcal{C}^{\infty}_{c}(\Omega)=\mathcal{D}^{}_{}(\Omega)$ is dense in $L^p_{}(\Omega)$.

:::

::: {.theorem  name="regularization and approximation in $L^p_{}(\mathbb{R}^{n})$"}

Let a function $f\in L^p_{}(\mathbb{R}^{n})$, $p \in [1,\infty)$ be given, and let $(f_\epsilon)_{\epsilon\gt 0}$ be a regularizing family of $f$, then
$$ 
f_\epsilon\in \mathcal{C}^{\infty}_{}(\mathbb{R}^{n}) \mathop{\text{ for all }}\epsilon\gt 0
$$
and 
$$ 
\|f_\epsilon-f\|_{L^p_{}(\mathbb{R}^{n})}\to 0 \mathop{\text{ as $\epsilon\to 0$}}
$$


:::





















