
### Riesz Theorem

::: {.lemma #finite-dimensional-norm-inequality name=""}

Let $(X,\left\| \cdot \right\|)$ be a finite-dimensional normed space with basis $\{x_1,x_2,\dots,x_n\}$, then there exists $m>0$ $s.t.$ for any $(\alpha_i)_{i=1}^{n}\subset \mathbb{K}^{n}$ we have
$$
m \sum_{i=1}^{n} \left| \alpha_i \right|\le \left\| \sum_{i=1}^{n}\alpha_i x_i \right\|
$$


:::



::: {.theorem #thm-finite-dim name=""}

1.  Any two norms $\left\| \cdot \right\|$ and $\left\| \cdot \right\|_0$ in a finite-dimensional vector space are equivalent, i.e. the topology they induced are identical.
2.  Any finite-dimensional vector space is separable.
3.  A subset of a finite-dim normed vector space is compact iff it is closed and bounded.
4.  A finite-dim space normed vector space $X$ is complete and thus closed.

:::

::: {.proof}

1.
    Suppose $\{x_i\}_{i=1}^{n}$ be a basis for $X$ and $\left\| \cdot \right\|_0$ and $\left\| \cdot \right\|$ be any two norms on $X$. For any $x\in X$, we can represent as $x=\sum_{i=1}^{n} \alpha_i x_i$, by lemma \@ref(lem:finite-dimensional-norm-inequality), we have
    $$
    m \sum_{i=1}^{n} \left| \alpha_i \right| \le  \left\| \sum_{i=1}^{n} \alpha_ix_i \right\|=\left\| x \right\|
    $$
    and
    $$
    \left\| x \right\|_0 \le \sum_{i=1}^{n} \left| \alpha_i \right| \left\| x_i \right\|_0 \le M \sum_{i=1}^{n} \left| \alpha_i \right|
    $$
    where $M=\max \left\| x_i \right\|_0$, which relate $\left\| \cdot \right\|$ and $\left\| \cdot \right\|_0$ in a direction and the other direction follows analogously. This completes the proof.

2.
    According to theorem \@ref(thm:thm-lp-separable), and 1, we find that the topology induced by $\|\|_{p}$ is equivalent to any other norm in a finite-dim space. Then we prove the separability.

3.
    Let $K$ be a closed and bounded set in $(X,\|\|_{})$. Suppose in $(X,\|\|_{1})$, then according to \@ref(thm:thm-heine-borel), compact in $(X,\|\|_{1})$ means closed and bounded, as $(1)$ proved above, the topology induced by any norm is equivalent, so $K$ is compact in $(X,\|\|_{})$. The other side is the property of metric spaces.
    
4.
    Let $Y\subset X$ be a subspace of $X$ and let a sequence (since metric space) converges to a point in $X$ i.e. $(y_n)\to y\in X$ for each $n$, $y_n\in Y$, now we need to prove that $y\in Y$.  
    Notice that for all $k\in \mathbb{N}_+$, $y_k=\sum_{i=1}^{n} y_{k,i}e_{i}$ where $(e_{i})_{i=1}^{n}$ is the basis of $Y$. Then $(y_n)\to y$ means that $(y_{i,n})_{n=1}^{\infty}$ is a Cauchy sequence for there exists a $C$ s.t. 
    $$ 
    \sum_{i=1}^{n} \left|y_{i,k}-y_{i,\ell}\right|=\|y_k-y_{\ell}\|_{1}\le C\|y_k-y_\ell\|_{}
    $$
    for all $k,\ell\ge 1$. Notice that $(X,\|\|_{})$ is a metric space and $(y_n)\to y\in X$, so $(y_n)$ is Cauchy which means $C\|y_k-y_\ell\|_{}$ can be arbitrarily small which implies that $(y_{i,n})_{n=1}^{\infty}$ is Cauchy in $\mathbb{K}$ and as the completeness of $\mathbb{K}$, $(y_{i,n})\to y_{i}\in \mathbb{K}$ as $n\to \infty$. Let $y=\sum_{i=1}^{n} y_{i}e_{i}$.  
    Now prove that $(y_n)\to y$. Notice that there exists a $C_1$ s.t. 
    $$ 
    \|y_k-y\|_{}\le C_1\|y_k-y\|_{1}=C_1 \sum_{i=1}^{n} \left|y_{i,k}-y_{i}\right|
    $$
    Since $(y_{i,n})\to y_{i}$ for each $i$, $\|y_k-y\|_{}$ can also be arbitrarily small thus convergent.  
    So all the sequence in $Y$ convergence in $Y$ means $Y=\overline{Y}$ thus closed.

:::


::: {.lemma #riesz-lemma name="Riesz's Lemma"}

Let $F$ be a closed property subspace of normed space $(X,\left\| \cdot \right\|)$. Then for each $\epsilon \in (0,1)$, there is $z \in S(0,1)$ $s.t.$ $\left\| y-z \right\| > 1-\epsilon$ for any $y \in F$.

:::


:::: {.proof}

Choose $x \in F^c$ and let $d=d(x,F)$, as $F$ is closed, $d>0$ and we can find some $m \in F$ $s.t.$ $d(x,m)<d(1+\epsilon)$. Take $z=-\frac{m-x}{d(x,m)} \in S(0,1)$, for any $y\in F$, we have
$$
\begin{aligned}
    \left\| y-z \right\|&=\left\| y+\frac{m-x}{d(x,m)} \right\|= \frac{\left\| d(x,m)y+m-x \right\|}{d(x,m)}
    \\
    & \ge \frac{d}{d(x,m)} > \frac{d}{d(1+\epsilon)}=\frac{1}{1+\epsilon} > 1-\epsilon
\end{aligned}
$$
::::

::: {.theorem #thm-riesz name="F.Riesz Theorem"}

A normed vector space $(x,\left\| \cdot \right\|)$ is finite-dim iff the unit sphere of $X$, $S(0,1)$ is compact.

:::

::: {.proof}

-
    Assume that $K$ is compact. Then there exists a finite number of points $x_{i}\in X$ s.t. $K\subset \bigcup_{i=1} ^{n}B_{1 /2}(x_{i})$.

    Then we need to show that $Y=\mathop{\text{span}}(x_{i})_{i=1}^{n}$ is coincide with $X$ and it is enough to show that 
    $$ 
    \inf_{y\in Y}\|x-y\|_{}=0
    $$
    for all $x\in X$ as $Y$ is finite-dim and $\overline{Y}=Y$.

    Let $x\in X$ and $y\in Y$ be given, then let 
    $$ 
    x'=\frac{x}{\|x-y\|_{}} \mathop{\text{ and }}y'=\frac{y}{\|x-y\|_{}}
    $$
    Notice that $x'-y'\in K$ thus in some $B_{1 /2}(x_{i_0})$. So
    $$ 
    \|x-y\|_{}(\|(x'-y')-x_{i_0}\|_{})\le \frac{1}{2}\|x-y\|_{}
    $$
    Now let $y_1=\|x-y\|_{}(y'+x_{i_0})$, then $\|x-y_1\|_{}\le \frac{1}{2}\|x-y\|_{}$. Then let $y=y_1$, and by induction, we find
    $$ 
    \|x-y_n\|_{}\le \frac{1}{2^{n}}\|x-y\|_{}
    $$
    Notice that $\|x-y\|_{}\lt \infty$, so there exists a sequence $(y_n)\to x$ for all $y_n\in Y$ and as $Y=\overline{Y}$, $x\in Y$, so $X=Y=\mathop{\text{span}}(x_{i})_{i=1}^{n}$ thus finite-dim.

-
    For the converse, we notice that $K$ is closed and bounded, then compact since \@ref(thm:thm-finite-dim)(3).

:::

### Schauder Bases

::: {.definition  name=""}

Let $X$ be a TVS, a set $\{x_n\}$ is called as **compete** if
$$
X=\overline{\mathop{\text{span}}(\left\{ x_n \right\})}
$$

:::

::: {.theorem  name=""}

A normed linear space $(X,\left\| \cdot \right\|)$ is separable iff it contains a countable complete set.

:::

::: {.definition  name=""}

A sequence $(b_n)$ in a Banach space $(X, \left\| \cdot \right\|)$ is called a Schauder basis if for any $x \in X$, there exists unique sequence $(\alpha_n)$ $s.t.$
$$
\lim_{n \to \infty} \left\| x-\sum_{i=1}^{n} \alpha_i b_i \right\|=0
$$
and write $x=\sum_{i=1}^{\infty}\alpha_ib_i$.

:::


::: {.proposition  name=""}

If a Banach space has a Schauder basis, it's separable.

:::













