# Linear Operators and Functionals

## General properties


::: {.definition  name="linear operator"}

A mapping $A:X\to Y$ is a linear operator from $X$ into $Y$, or a linear functional if $Y=\mathbb{K}$ where $\mathbb{K}=\mathbb{R} \mathop{\text{ or }}\mathbb{C}$ and

-   $A(x+y)=A(x)+A(y)$ for all $x,y\in X$ 
-   $A(\alpha x)=\alpha A(x)$ where $x\in X$ and $\alpha\in \mathbb{K}$ 

Moreover, if $\mathbb{K}=\mathbb{C}$, then a mapping $A:X\to Y$ is semilinear if:

-   $A(x+y)=A(x)+A(y)$ 
-   $A(\alpha x)=\overline{\alpha}A(x)$ where $\overline{\alpha}$ denotes the complex conjugate of $\alpha$.

:::

We shall denote by $\mathcal{L}(X,Y)$ the set of all linear operators from $X$ to $Y$. When $X=Y$, we use $\mathcal{L}(X)$ for short. Clearly, $\mathcal{L}$ is a vector space.

::: {.definition  name="kernel and image"}

The kernel of $A$ defined by:
$$ 
\ker A=\left\{x\in X:Ax=0\right\}
$$
The image of $A$ defined by:
$$ 
\mathop{\text{ran}}A=\left\{y\in Y:y=Ax \mathop{\text{ for some }}x\in X\right\}
$$
Notice that $\ker A$ is a subspace of $X$ and $\mathop{\text{ran}}A$ is a subspace of $Y$.

:::

A linear operator $A:X\to Y$ is injective iff $\ker A=\left\{0\right\}$ and surjective if $\mathop{\text{ran}}A=Y$. If $A:X\to Y$ is injective, there exists a map $A^{-1}:\mathop{\text{ran}}A \to X$, called the **inverse** of $A$.


::: {.proposition  name=""}

Suppose $A \in \mathcal{L}(X,Y)$ is invertible, then

1.  $A^{-1}$ is invertible and $(A^{-1})^{-1}=A$.
2.  $AA^{-1}=I_Y$ and $A^{-1}A=I$.
3.  $A^{-1}$ is a linear operator.

:::


::: {.proposition  name=""}

Let $X$ be a linear space, then

1.  For any $f\in \mathcal{F}(X,\mathbb{K})$, $\ker f$ is a hyperplane in $X$, $i.e., \mathop{\text{codim}} \ker f=1$.
2.  If nonzero $f,g \in \mathcal{F}(X,\mathbb{K})$, then $f=a g$ for some $a\in \mathbb{K}$.
3.  For any hyperplane $H\subset X$, there exists a $f\neq 0 \in \mathcal{F}(X,\mathbb{K})$ $s.t.$ $\ker f=H$.

:::


::: {.definition  name="eigenvalue"}

Let $X$ be a vector space over $\mathbb{K}$ and let $A:X\to Y$ be a linear operator. Then a scalar $\lambda\in \mathbb{K}$ is a eigenvalue of $A$ if there exists a vector $p \in X$ s.t. 
$$ 
Ap=\lambda p \mathop{\text{ and }}p\neq 0
$$
and such $p$ is called the eigenvector of $A$, corresponding to the eigenvalue $\lambda$.


:::

For a particular eigenvalue  $\lambda$, note that the subset $\left\{p \in X:Ap=\lambda p\right\}\subset X$ is a subspace, which is called eigenspace corresponding to $\lambda$.

## Bound operators

The most important class of linear operators is that of bounded linear operators.

::: {.definition  name=""}

Let $X$ and $Y$ be normed space, $A\in \mathcal{L}(X,Y)$ is called **bounded** if $\exists M>0\ s.t.\ \forall x \in X$,
$$
\left\| Ax \right\|\le M \left\| x \right\|
$$

:::



::: {.definition  name="continuity of operator"}

When $X,Y$ are normed vector space which equipped their norm topology, then a mapping $A:X\to Y$ is called continuous linear operator if it is both continuous between their norm topology and keep linearity. Explicitly, $A$ is continuous at $x_0$ if we can let $\left\| Ax-Ax_0 \right\|$ arbitrary small by bounded $\left\| x-x_0 \right\|$.

:::

::: {.theorem  name="norm of $\mathcal{B}^{}_{}(X;Y)$"}

1.
    The mapping defined by:
    $$ 
    \|\cdot \|_{}:A\in \mathcal{B}(X;Y)\to \|A\|_{}=\sup_{x\neq 0}\frac{\|Ax\|_{}}{\|x\|_{}}
    $$
    is a norm of $\mathcal{B}^{}_{}(X;Y)$ which is called the sup-norm.

2.
    The norm of any $A\in \mathcal{B}^{}_{}(X;Y)$ may be equivalently defined as 
    $$ 
    \begin{aligned}
        \|A\|_{}&= \sup_{\|x\|_{}\le 1}\|Ax\|_{}=\sup_{\|x\|_{}\lt 1}\|Ax\|_{}=\sup_{\|x\|_{}=1}\|Ax\|_{} \\
        &= \inf\left\{C\gt 0:\|Ax\|_{}\le C\|x\|_{}\mathop{\text{ for all }}x\in X\right\} \\
    \end{aligned}
    $$
    where the last norm is called the inf-norm.


:::


::: {.proposition  name=""}


From $1$, we can get $\|Ax\|_{}\le \|A\|_{}\|x\|_{}$ for every $x\in X$, and if $X$ is finite-dim, there exists $0\neq x_0\in X$ s.t. 
$$ 
\|A\|_{}\|x_0\|_{}=\|Ax_0\|_{}
$$
    

:::


::: {.proof}


Note that if $X$ is finite-dim, then the unit sphere $\left\{x\in X:\|x\|_{}=1\right\}$ is compact. And the mapping $x\in X\mapsto y\in Y=Ax\mapsto \|Ax\|_{}$ is the composition of two continuous functions thus continuous. Then there exists some $x=x_0\in \left\{x\in X:\|x\|_{}=1\right\}$ s.t. this continuous function attains its supremum over $\mathbb{K}$ i.e. $\|Ax_0\|_{}=\sup\|Ax\|_{},\|x\|_{}=1$ then $\|A\|_{}=\|A\|_{}\|x_0\|_{}=\|Ax_0\|_{}$.

:::

Let $Z$ be a normed vector space and let $A\in \mathcal{B}^{}_{}(X;Y)$ and $B\in \mathcal{B}^{}_{}(Y;Z)$, then $BA=B\circ A\in \mathcal{B}^{}_{}(X;Z)$ and 
$$ 
\|BA\|_{}\le \|A\|_{}\|B\|_{}
$$
holds by noting $\forall x\in X$:
$$
\left\| (BA)x \right\|=\left\| B(Ax) \right\|\le \left\| B \right\|\left\| Ax \right\|\le \left\| B \right\|\left\| A \right\|\left\| x \right\|
$$

Particularly, if $A\in \mathcal{B}(X)$, then
$$ 
\|A^{n}\|_{}\le \|A\|_{}^{n}\mathop{\text{ for any }}n\in \mathbb{N}_+
$$

If $A\in \mathcal{B}(X)$, then any eigenvalue $\lambda$ of $A$ satisfies $\left|\lambda\right|\le \|A\|_{}$.

::: {.theorem #operator-bounded-continuous  name=""}

Let $X,Y$ be normed vector spaces, and $A:X\to Y$ be linear operator, then the following properties are equivalent:

1.  $A$ is continuous on $X$.
2.  $A$ is continuous at $0\in X$.
3.  There exists a $C\gt 0$ s.t. 
    $$ 
    \|Ax\|_{}\le C\|x\|_{} \mathop{\text{ for all }}x\in X
    $$
4.  $A$ carry bounded subset of $X$ to bounded subset of $Y$.

:::

::: {.proof}

-   $1\implies 2$ : Obvious.
-   
    $2\implies 3$ : Consider the closed unit ball $B_{1}[0]\subset Y$, then there exists a $C\gt 0$ s.t. 
    $$
    A^{-1}\left(B_{1}[0]\right)=B_{1 /C}[0]\subset X
    $$ 
    so for any $x\in X$, 
    $$ 
    \left|\left|A \left(\frac{x}{C\|x\|_{}}\right)\right|\right|\le 1
    $$
    thus $\|Ax\|_{}\le C\|x\|_{}$ for any $x\in X$.

-   $3\implies 4$ : Notice that every bounded set $B\subset X$ is contained in a ball $B_{r(B)}[0]$ and so for every $x\in B_{r(B)}[0]$, $\|Ax\|_{}\le C\|x\|_{}\le C\cdot r(B)$ thus bounded in $Y$.
-   
    $4\implies 1$ : Note that the image of ball $B_{1}[0]\subset X$ is bounded in $Y$. In other words, there exists $M\ge 0$ s.t. $\|x\|_{}\le 1\implies \|Ax\|_{}\le M$. Now give an $x_0\in X$ and a $\epsilon\gt 0$, let $\delta=\epsilon /M$, then $\|x-x_0\|_{}\le \delta$ implies that $\frac{1}{\delta}(x-x_0)\in B_{1}[0]$ so
    $$ 
    \frac{1}{\delta}\|A(x-x_0)\|_{}=\left|\left|A\left(\frac{x-x_0}{\delta}\right)\right|\right|\le M
    $$
    so $\|Ax-Ax_0\|_{}\le \delta\cdot M=\epsilon$ which means the continuity.

:::

::: {.remark  name=""}

The above theorem shows that in normed vector spaces, continuous linear operator is equal to the linear bounded operator. So continuous linear operator is also called bounded linear operator.

:::

::: {.corollary  name=""}

Let $X,Y$ be two normed vector spaces, and let $A:X\to Y$ be a linear operator, then the properties are equivalent:

-   The linear operator $A$ is injective and inverse mapping $A^{-1}:\mathop{\text{ran}}A\to X$ is a continuous linear operator.
-   
    There exists a constant $C\gt 0$ s.t.
    $$ 
    \|x\|_{}\le C\|Ax\|_{} \mathop{\text{ for all }}x\in X
    $$

:::

::: {.proof}

Note that $\left\| x \right\|\le C \left\| Ax \right\|$ implies $\ker A=\left\{ 0 \right\}$ and thus it's equivalent to $\left| A^{-1}Ax \right|\le C \left\| Ax \right\|$, note $\mathop{\text{dom}}A^{-1}=\mathop{\text{ran}}A$, we have $A^{-1}$ is continuous by \@ref(thm:operator-bounded-continuous).

:::



Let $X\subset Y$ be a subspace of $Y$, then $X\hookrightarrow Y$ denotes the canonical injection from $X$ into $Y$. So according to  \@ref(lem:lem-norm-equal), we observe that:
$$ 
\|x\|_{Y}\le C\|x\|_{X}
$$

::: {.theorem  name=""}

Suppose $A \in \mathcal{B}(X,Y)$, we have

- $A$ is uniformly continuous.
- If $\mathop{\text{dim}} X<\infty$, $\mathcal{L}(X,Y)=\mathcal{B}(X,Y)$.

:::

::: {.proof}

Notice that if $A$ is continuous, then there exists a $C\ge 0$ s.t. $\|Ax\|_{}\le C\|x\|_{}$ for every $x\in X$. So for any $x_1,x_2\in X$, 
$$ 
\|A(x_1-x_2)\|=\|Ax_1-Ax_2\|_{}\le C\|x_1-x_2\|_{}
$$
so $A$ is Lipschitz continuous on $X$.

Define $\left\| x \right\|_0=\left\| x \right\|+\left\| Ax \right\|$, which is a norm equivalent to $\left\| \cdot \right\|$ as $X$ is finite-dim. Then we have
$$
\left\| Ax \right\|\le \left\| x \right\|_0\le \beta \left\| x \right\|
$$
for some $\beta$.


:::

Clearly, A sequence $(A_{i})_{i \in \mathbb{N}^*}\subset \mathcal{B}(X,Y)$ is uniformly convergent to $A$ if
$$
\lim_{n \to \infty}\left\| A_n-A \right\|=0
$$
Clearly, $A\in \mathcal{B}(X,Y)$. However, for a weaker case, that is, $(A_n)\to A$ pointwise:
$$
\lim_{n \to \infty}\left\| A_nx-Ax \right\|=0, \forall x\in X
$$
$A$ can be not in $\mathcal{B}(X,Y)$.


::: {.theorem  name=""}

$\mathcal{B}(X,Y)$ is Banach if so is $Y$.

:::


:::: {.proof}

Note that $\left\| A_nx-A_{n+r}x \right\|\le \left\| A_n-A_{n+r} \right\|\left\| x \right\|<\epsilon \left\| x \right\|$ and $(A_nx)$ is convergent in $Y$, so we can find a limit $A$ by setting $Ax=\lim_{n \to \infty}A_nx$.

::::


## Functionals


::: {.definition  name=""}

Let $X$ be a linear space over $\mathbb{K}$, if $f \in \mathcal{F}(X,\mathbb{K})$, $f$ is called a **linear functional**. We shall denote $X^{*}=\mathcal{B}(X,\mathbb{K})$ and call $X^{*}$ the **dual** of $X$. 

:::

As $\mathbb{K}$ is Banach, $X^{*}$ is Banach.


::: {.definition  name=""}

If there is a bijective $A \in \mathcal{L}(X,Y)$, we say $X$ and $Y$ are **isomorphic** to each other and denoted by $X \simeq Y$. Furthermore, if $A$ is an **isometry**, $i.e.$, $\left\| Ax \right\|=\left\| x \right\|$ for all $x\in X$, then $A$ is an **isometric isomorphism** and $X$ and $Y$ are said to be **isometric isomorphic** and write $X \cong Y$.

:::

Two normed linear spaces which are isometrically isomorphic can be regarded as identical, the isometry
merely amounting to a relabelling of the elements.


::: {.proposition  name=""}



:::







$$
\left\{ X>C \right\}=\emptyset
$$







<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
