# Continuous Function and Continuous Function Space

## Continuous Function

::: {.definition  name="oscillation"}

If $f:\left(X,d\right)\to \left(Y,\rho\right)$ is an arbitrary mapping, then the oscillation of $f$ on a ball $B\left(x_0\right)$ is defined by:
$$ 
\mathop{\text{osc}}(f,B_r(x_0))=\sup\left\{\rho(f(x),f(y)):x,y\in B_r(x_0)\right\}
$$
Notice that the oscillation is non-decreasing corresponding to $r$ on each $x_0$.

:::

::: {.proposition  name=""}

A function $f:X\to Y$ is continuous at $x_0$ iff 
$$ 
\lim _{r\to 0}\mathop{\text{osc}}(f,B_r(x_0))=0
$$

:::

::: {.theorem  name=""}

Let $f:X\to Y$ be an arbitrary function. Then the set of points at which $f$ is continuous is a $G_\delta$ set.

:::

::: {.proof}

Let 
$$ 
G_{i}=\left\{x\in X:\inf_{r\gt 0}\mathop{\text{osc}}(f,B_r(x))\lt \frac{1}{i}\right\}
$$
so the set that $f$ is continuous is given by:
$$ 
A=\bigcap_{i=1} ^{\infty}G_{i}
$$
Now we need to prove that $G_{i}$ is open. Observe that $x\in G_{i}$ there exists $r\gt 0$ s.t. $\mathop{\text{osc}}(f,B_r(x_0))\lt 1 /i$. Give $y\in B_r(x)$, there exists $t\gt 0$ s.t. $B_t(y)\subset B_{r}(x)$, so
$$ 
\mathop{\text{osc}}(f,B_{y}(t))\le \mathop{\text{osc}}(f,B_{r}(x))\le 1 /i
$$
which means each point $y\in B_{r}(x)$ is an element of $G_{i}$, that is $B_{r}(x)\subset G_{i}$, as the arbitrary picking of $x$, $G_{i}$ is thus a open set.

:::

::: {.theorem  name=""}

Let $f$ be an arbitrary function defined on $[0,1]$ and let 
$$ 
E=\left\{x\in [0,1]:\mathop{\text{ $f$ is continuous at}}x\right\}
$$
Then $E$ cannot be the set of rational numbers in $[0,1]$.

:::

::: {.proof}

Observe that if $E$ is the set of rational numbers, then the set of rational numbers in  $[0,1]$ is a $G_\delta$ set which implies that the irrational numbers in $[0,1]$ is a $F_\sigma$ set.  
Notice that the rational numbers are the countable union of closed set (singletons). And since the rational numbers are dense in $[0,1]$, so if the irrational number set is $F_\sigma$, then every closed set in this family cannot have any interiors which means the whole $[0,1]$ is a $F_\sigma$ set with a family of nowhere dense set, which is contrary with the Baire category theorem.

:::


::: {.theorem  name=""}

A continuous functions carries a compact subset into a compact subset.

:::

::: {.proof}
 
Let $X,Y$ be two topological space and $f:X\to Y$ is continuous, now we prove that if $K\subset X$ is compact, then $f(K)\subset Y$ is compact too.  
Notice that $f\mid _K$ is surjective, so $f(f^{-1}(U))=U$. Then consider a open cover $\mathcal{F}$ of $f(K)$, then the set $\mathcal{E}=\left\{f^{-1}(U):U\in \mathcal{F}\right\}$ is a open cover of $K$, then there exists a finite open subcover $\left\{V_1,\ldots,V_n:V_{i}\in \mathcal{E}\right\}$ s.t. $\bigcup_{i=1} ^{n}V_{i}\supset K$ where $V_{i},i=1,\ldots,n$ is $f^{-1}(U_{i})$ for some $U_{i}\in \mathcal{F}$, so there exists some $i$ s.t. $\bigcup_{i=1} ^{n}f^{-1}(U_{i})\supset K$, then 
$$ 
f \left(\bigcup_{i=1} ^{n}f^{-1}(U_{i})\right)=\bigcup_{i=1} ^{n}f\left(f^{-1}(U_{i})\right)=\bigcup_{i=1} ^{n}U_{i}
$$
Notice that
$$ 
f\left(\bigcup_{i=1} ^{n}f^{-1}(U_{i})\right)\supset f(K)
$$
so $f(K)\subset \bigcup_{i=1} ^{n}U_{i}$.

:::

::: {.definition #u-continuity name="uniformly continuous"}

A function $f:(X,d)\to (Y,\rho)$ is said to be uniformly continuous on $X$ if for each $\epsilon\gt 0$, there exists $\delta\gt 0$ s.t. when $d(x,y)\le \delta$, $\rho(f(x),f(y))\le \epsilon$ for all $x,y\in X$.

An equivalent formulation of uniform continuity can be stated in oscillation. For each $r\gt 0$, let 
$$ 
\omega_f(r)=\sup_{x\in X}\mathop{\text{osc}}\left(f,B_{r}(x)\right)
$$
The function $\omega_f$ is called the modulus of continuity of $f$. Observe that $f$ is uniformly continuous if
$$ 
\lim _{r\to 0}\omega_f(r)=0
$$

:::

::: {.proof}

Give a $\epsilon\gt 0$, there exists a $\delta\gt 0$, when $r\le \delta$, $\omega_f(r)\le \epsilon$. Then
$$ 
\sup_{x\in X}\mathop{\text{osc}}(f,B_{r}(x))\le \epsilon
$$
so when $d(x,y)\le r\le \delta$, $\sup_{x\in X}\rho(f(x),f(y))\le \epsilon$ which means uniform continuity.

:::

::: {.theorem  name=""}

Let $f:X\to Y$ be a continuous mapping. If $X$ is compact, then $f$ is uniformly continuous on $X$.

:::

::: {.proof}

From \@ref(def:u-continuity), we notice that if $\lim _{r\to 0}\omega_f(r)=0$, then $f$ is uniformly continuous.  
Choose $\epsilon\gt 0$, the collection
$$ 
\mathcal{F}=\left\{f^{-1}(B_{\epsilon /2}(y))):y\in Y\right\}
$$
is a open cover of $X$, then there exists a Lebesgue number $\delta\gt 0$ s.t. $B_{\delta}(x)\subset f^{-1}(B_{\epsilon /2}(y))$ for all $x\in X$ follows from \@ref(lem:lebesgue-number).  
So $f(B_{\delta}(x))\subset B_{\epsilon /2}(y)$ for some $y\in Y$ which means $\omega_f(\delta)\le \epsilon$ for arbitrary $\epsilon$, so $f$ is uniformly continuous.

:::



::: {.theorem  name=""}

Let $K$ be a compact topological space and let $(Y,\|\cdot\|_{Y})$ be a normed vector space. Then $\mathcal{C}(K;Y)$ is a vector space with the norm $\|\cdot \|:\mathcal{C}(K;Y)\to \mathbb{R}$ :
$$ 
\|f\|_{\mathcal{C}}=\sup_{x\in K}\|f(x)\|_{Y}
$$
for each $f\in \mathcal{C}(K;Y)$. It is called the **sup-norm** on $\mathcal{C}(K;Y)$.

:::

::: {.proof}

Notice that $(Y,\|\cdot\|_{})$ is a metric space and a compact subset in a metric space is bounded and closed.  
-   $\sup\|f(x)\|_Y \lt \infty$ and $\sup\|f(x)\|_Y \ge 0$ 
-   $\sup\|\alpha f(x)\|_Y=\lvert \alpha \rvert \sup \|f(x)\|_Y$
-   $\sup\|f+g\|_Y \le\sup\|f\|_Y+\sup\|g\|_Y$

:::


::: {.definition  name="converge uniformly"}

A sequence $(f_n)_{n=1}^{\infty}$ of functions $f_n\in \mathcal{C}(K;Y)$ is said to **converge uniformly** if $\lim _{n\to \infty}\|f_n-f\|_{\mathcal{C}}=0$. It means
$$ 
\lim _{n\to \infty}\bigg(\sup_{x\in K}\|f_n(x)-f(x)\|_Y\bigg)=0
$$

:::

::: {.theorem  name=""}

Let $X$ be any set and let $(Y,\|\cdot\|_{Y})$ be a normed vector space. Then the set $\mathcal{B}(X;Y)$ of all bounded mappings $f:X\to Y$ i.e. $f(X)\subset Y$ is a bounded subset in $Y$ is a vector space and the function $\|\cdot \|_{\mathcal{B}}:\mathcal{B}(X;Y)\to \mathbb{R}$ defined by:
$$ 
\|f\|_{\mathcal{B}}=\sup_{x\in X}\|f(x)\|_{Y}
$$
is a norm on $\mathcal{B}(X;Y)$.

:::

::: {.proof}

Notice that a bounded function $f$ over $\mathbb{K}$, for any $\alpha\in \mathbb{K}$, $\alpha f$ is still bounded and for $f,g\in \mathcal{B}(X;Y)$, $f+g$ is still bounded.

It is easy to show that $\|f\|_{\mathcal{B}}$ is truly a norm on $\mathcal{B}(X;Y)$.

:::

::: {.definition  name="local uniform convergence"}

Let $X$ be a topological space and $Y$ be a normed vector space. Then a sequence $(f_n)_{n=1}^{\infty}$ of mappings $f_n:X\to Y$ is said to converge locally uniformly to a mapping $f:X\to Y$ as $n\to \infty$ if given any $x_0\in X$ there exists a neighborhood $V(x_0)$ of $x_0$ s.t. 
$$ 
\lim _{n\to \infty}\bigg(\sup_{x\in V(x_0)}\|f_n(x)-f(x)\|_{Y}\bigg)=0
$$

:::

Notice that local uniform convergence and uniform convergence implies the pointwise convergence.


::: {.theorem  name=""}

Let $X$ is a topological space and $Y$ be a normed vector space, let $(f_n)_{n=1}^{\infty}$ be a sequence of continuous mapping from $X$ to $Y$ that converges locally uniformly to a $f:X\to Y$, then $f$ is continuous on  $X$.

Moreover, if $f_n$ continuous at $x_0$ and they locally uniformly convergence to $f$ then $f$ is continuous at $x_0$.

:::

::: {.proof}

Assume that $f$ is continuous at $x_0$ which means give $\epsilon\gt 0$, there exists a neighborhood  $V(x_0)\in \mathcal{N}_{x_0}$ s.t. for every $x\in V(x_0)$, $\|f(x_0)-f(x)\|_{Y}\le \epsilon$.

Now suppose that $\epsilon\gt 0$ is given. As $(f_n)\to f$ locally uniformly. Then we can choose a $k\in \mathbb{N}$ s.t. for any $i\ge k$, we can find a neighborhood $V(x_0)$ s.t. for any $x\in V(x_0)$, 
$$
\sup_{x\in V(x_0)}\|f_i(x)-f(x)\|_{Y}\le \epsilon /3
$$
and as all $f_n:n\in \mathbb{N}$ is continuous at $x_0$, so we can find a neighborhood of $x_0$, $U(x_0)\in \mathcal{N_{x_0}}$ s.t. for any $x\in U(x_0)$, 
$$ 
\sup_{x\in U(x_0)}\|f_{i}(x)-f_{i}(x_0)\|_{Y}\le \epsilon /3
$$
Then we consider the set $W(x_0)=U(x_0)\cap V(x_0)\in \mathcal{N}_{x_0}$, for any $x\in W(x_0)$ :
$$ 
\begin{aligned}
    \|f(x)-f(x_0)\|_{Y}&\le \|f(x)-f_{i}(x)\|_{Y}+\|f_{i}(x)-f_{i}(x_0)\|_{Y}+\|f_{i}(x_0)-f(x_0)\|_{Y} \\
    &\le \epsilon /3 + \epsilon /3 +\epsilon /3 \\ 
    &= \epsilon
\end{aligned}
$$
so if $(f_n)\to f$ locally uniformly, and $f_n$ is continuous at $x_0$ for every $n$ then $f$ is continuous at $x_0$. Moreover, if $f_n$ is continuous at every $x\in X$ i.e. continuous at $X$, then $f$ is continuous at $X$.

:::

::: {.definition  name="equicontinuous"}

A family $\mathcal{F}$ of functions

:::
























