# Real Analysis {-}

# Measurability

## Algebra of sets

 
::: {.definition  name="algebra"}

A non-empty family of subsets $\mathscr{A}$ is called the algebra of sets $X$ if 

-   $A,B\in \mathscr{A}\implies A\cup B\in \mathscr{A}$
-   $A\in \mathscr{A}\implies A^{c}=X-A\in \mathscr{A}$

:::

::: {.definition  name="$\sigma$-Algebra"}

A family is called $\sigma$-Algebra if it is an algebra and

-   $(A_n)_{n=1}^{\infty}\subset \mathscr{A}\implies \bigcup_{n=1} ^{\infty}A_n\in \mathscr{A}$

:::

::: {.theorem  name=""}

If  $\mathscr{C}$ is a nonempty collection of subsets of $X$ then $\sigma(\mathscr{C})=\mathscr{A}$ which is the smallest $\sigma$-Algebra containing $\mathscr{C}$ satisfies:

-   If $A\in \mathscr{A}$, then $A^{c}\in \mathscr{A}$.
-   $\mathscr{A}$ is closed under countable intersections.
-   $\mathscr{A}$ is closed under countable disjoint unions.

:::

::: {.definition  name="ring"}

A nonempty family $\mathscr{R}$ of subsets of $X$ is a ring if:

-   $A,B\in \mathscr{R}\implies A\cup B\in \mathscr{R}$ 
-   $A,B\in \mathscr{R}\implies A-B\in \mathscr{R}$

Notice that $A-(A-B)=A\cap B$, so $A,B\in \mathscr{R}\implies A\cap B\in \mathscr{R}$.

:::

::: {.definition  name="semiring"}

A semiring  $\mathscr{S}$ is a non-empty family of subsets of $X$ satisfying:

-   $\varnothing\in \mathscr{S}$ 
-   $A,B\in \mathscr{S}\implies A\cap B\in \mathscr{S}$ 
-   If $A,B\in \mathscr{S}$, then there exists pairwise disjoint sets $C_1,\ldots,C_n\in \mathscr{S}$ s.t. $A-B=\bigcup_{i=1} ^{n}C_{i}$

:::

::: {.theorem  name=""}

If $\mathscr{S_1,S_2}$ are semirings, then $\mathscr{S_1\times S_2}$ is also semiring where $\times$ denotes the Cartesian product.

:::

::: {.proof}

-   Let  $\varnothing\times \varnothing=\varnothing$ without any doubt.
-   Let $A,C\in \mathscr{S_1}$ and $B,D\in \mathscr{S_2}$ then $A\times B,C\times D\in \mathscr{S_1\times S_2}$. Notice that $(A\times B)\cap (C\times D)=(A\cap C)\times (B\cap D)$ where $A\cap C\in \mathscr{S_1},B\cap D\in \mathscr{S_2}$, so $(A\cap C)\times (B\cap D)\in \mathscr{S_1\times S_2}$.
-
    Let $A,C\in \mathscr{S_1}$ and $B,D\in \mathscr{S_2}$.  
    $$ 
    \begin{aligned}
        (A\times B)-(C\times D)&= (A-C)\times B\cup A\times (B-D) \\
    \end{aligned}
    $$

:::

### Dynkin's Lemma


::: {.definition  name="$\lambda$-system"}

A $\lambda$-system or Dynkin system is a nonempty family $\mathscr{A}$ s.t. 

-   $X\in \mathscr{A}$ 
-   $A,B\in \mathscr{A},B\subset A\implies A-B\in \mathscr{A}$ 
-   $(A_n)\subset \mathscr{A},(A_n)\nearrow A\implies A\in \mathscr{A}$

:::

::: {.theorem  name=""}

A nonempty family of subsets of $X$ is a  $\sigma$-Algebra iff it is both a $\pi$-system and a $\lambda$-system.

:::

::: {.theorem  name="Dynkin's Lemma"}

If $\mathscr{A}$ is a $\lambda$-system and a nonempty family $\mathscr{F\subset A}$ is closed under finite intersection, then $\sigma(\mathscr{F})\subset \mathscr{A}$.

In other words, if $\mathscr{F}$ is a $\pi$-system, then $\sigma(\mathscr{F})$ is the smallest $\lambda$-system containing $\mathscr{F}$.

:::

### Borel $\sigma$-Algebra

::: {.definition  name="borel set"}

The Borel $\sigma$-Algebra of a topological space $(X,\tau_{})$, is $\sigma(\tau)$. The set in $\sigma(\tau)$ is called the Borel sets.

:::

::: {.corollary  name=""}

1.  The Borel $\sigma$-Algebra is the smallest $\lambda$-system containing the open sets. It is also the smallest $\lambda$-system containing all the closed sets.
2.  The Borel $\sigma$-Algebra of a topological space is the smallest family of sets containing all the open sets and all the closed sets that is the closed under countable intersections and countable disjoint unions.
3.  The Borel $\sigma$-Algebra of a metrizable space is the smallest family of sets that include the open (closed) sets and is closed under countable intersections and countable disjoint unions.

:::

::: {.remark  name=""}

For the difference between $(2)$ and $(3)$, just notice that in a metrizable space, every closed set is $G_\delta$ and every open set is $F_\sigma$.

:::

### Product Structure


::: {.definition  name="product $\sigma$-Algebra"}

Let $\mathcal{F}_i$ be a $\sigma$-Algebra of $X_{i}$, $i=1,\ldots,n$. Then the product $\sigma$-Algebra denoting as $\mathcal{F}_1\otimes \cdots\otimes \mathcal{F}_n$ is the $\sigma$-Algebra generated by the product semiring $\prod_{i=1}^{n} \mathcal{F}_i$.

:::

::: {.theorem  name=""}

For any two topological space $X$ and $Y$:

1.  $\mathscr{B}_X\otimes \mathscr{B}_Y\subset \mathscr{B}_{X\times Y}$ 
2.  If $X,Y$ are second countable, then $\mathscr{B}_X\otimes \mathscr{B}_Y=\mathscr{B}_{X\times Y}$.

:::

::: {.proof}

For each $A\subset X$, let
$$ 
\mathcal{F}(A)=\left\{B\subset Y:A\times B\in \mathscr{B}_{X\times Y}\right\}
$$
Then $\mathcal{F}(A)$ satisfies:

1.  $\varnothing\in \mathcal{F}(A)$ for $A\times \varnothing=\varnothing\in \mathscr{B}_{X\times Y}$.
2.  If $B,C\in \mathcal{F}(A)$ then $B-C\in \mathcal{F}(A)$. Notice that if $B,C\in \mathcal{F}(A)$, then $A\times (B-C)=(A\times B)-(A\times C)$, so $A\times (B-C)\in \mathscr{B}_{X\times Y}$ as the property of $\sigma$-Algebra.
3.  $\mathcal{F}(A)$ is closed under countable unions. To see this, notice that if $(B_n)_{n=1}^{\infty}\subset \mathcal{F}(A)$, then $A\times (\bigcup_{n=1} ^{\infty}B_n)=\bigcup_{n=1} ^{\infty}(A\times B_n)\in \mathscr{B}_{X\times Y}$.

From above properties, we find that $\mathcal{F}(A)$ is a $\sigma$-ring. If $Y\in \mathcal{F}(A)$, then $\mathcal{F}(A)$ is a $\sigma$-Algebra.

Then note that for any open subset $G\in \tau_X$, $U\in \mathcal{F}(G)$ for every $U\in \tau_X$. To see this, just recall the base of product topology of finite Cartesian product of sets which has the form $\prod_{i=1}^{n} V_{i}$ where $V_{i}\subset X_{i}$ is the open subsets. Notice that $Y\in \tau_Y$ so $Y\in \mathcal{F}(G)$ s.t. $\mathcal{F}(G)$ is a $\sigma$-Algebra and $\tau_Y\subset \mathcal{F}(G)$ thus $\mathscr{B}_Y\subset \mathcal{F}(G)$ when $G$ is open.

Now let 
$$ 
\mathscr{A}=\left\{A\subset X:\mathscr{B}_Y\subset \mathcal{F}(A)\right\}
$$
As we discussed above, $\tau_X\subset \mathscr{A}$.

Also note that $\mathscr{A}$ is closed under complementation. To see this, let $A\in \mathscr{A},B\in \mathscr{B}_Y$, then $A\times B\in \mathscr{B}_{X\times Y}$, as $X\in \tau_X$, then $X\times B\in \mathscr{B}_{X\times Y}$. Therefore, $A^{c}\times B=(X-A)\times B=(X\times B)-(A\times B)=(X\times B)\cap (A\times B)^{c}\in \mathscr{B}_{X\times Y}$. As the arbitrary picking of $B\in \mathscr{B}_Y$ we find that $\mathcal{F}(A^{c})\supset \mathscr{B}$ thus $A^{c}\in \mathscr{A}$.

Finally, if $(A_n)_{n=1}^{\infty}\subset \mathscr{A}$ and $B\in \mathscr{B}_Y$, we have $A_n\times B\in \mathscr{B}_{X\in Y}$ for each $n$. As
$$ 
\bigcup_{n=1} ^{\infty}(A_n\times B)=\left(\bigcup_{n=1} ^{\infty}A_n\right)\times B
$$
and $(A_n\times B)_{n=1}^{\infty}$ is a sequence in $\mathscr{B}_{X\times Y}$, so the left side is still belong to $\mathscr{B}_{X\times Y}$, so as the arbitrary picking of $B\in \mathscr{B}_Y$, $\bigcup_{n=1} ^{\infty}A_n\in \mathscr{A}$ since $\mathscr{B}\subset \mathcal{F}(\bigcup_{n=1} ^{\infty}A_n)$.

The above steps show that $\mathscr{A}$ is a $\sigma$-Algebra containing $\tau_X$ which means $\mathscr{B}_X\subset \mathscr{A}$.

So if $A\in \mathscr{B}_X$, then $A\in \mathscr{A}$ and as the property of $\mathscr{A}$, if there exists $B\in \mathscr{B}_Y$, then $A\times B\in \mathscr{B}_{X\times Y}$ which means $\mathscr{B}_X\otimes \mathscr{B}_Y\subset \mathscr{B}_{X\times Y}$.

Note that if $X,Y$ are second countable space, then $X\times Y$ is. Every open subset of $X\times Y$ is the countable union of the form $U\times V$ where $U\in \tau_X,V\in \tau_Y$. So $\mathscr{B}_{X\times Y}=\sigma\left\{U\times V:U\in \tau_X,V\in \tau_Y\right\}\subset \sigma(\mathscr{B}_X\times \mathscr{B}_Y)=\mathscr{B}_X\otimes \mathscr{B}_Y$, so $\mathscr{B}_X\otimes \mathscr{B}_Y\supset \mathscr{B}_{X\times Y}$.

:::

::: {.theorem  name=""}

Let $(X,\mathcal{F})$ be a measurable space and $Y$ be a second countable Hausdorff space. If $f:X\to Y$ is $(\mathcal{F},\mathscr{B}_Y)$-measurable, then $\mathop{\text{Gr}}f\in \mathcal{F}\otimes \mathscr{B}_Y$.

:::

::: {.proof}

Let $\left\{U_{i}\right\}_{i=1}^{\infty}$ be a countable base of $Y$, then $f(x)\neq y$ iff there exists some $U_{i}$ s.t. $f(x)\in U_{i}$ and $y\notin U_{i}$. Thus
$$ 
(\mathop{\text{Gr}}f)^{c}=\bigcup_{i=1} ^{\infty}f^{-1}(U_{i})\times (U_{i})^{c}
$$
So $\mathop{\text{Gr}}f$ is $\mathcal{F}\otimes \mathscr{B}_Y$-measurable.

:::

::: {.definition  name="measurable section"}

If $A\subset X\times Y$, then we define $x$-section $A^{x}$ and $y$-section $A^{y}$ as:
$$ 
A^{x}=\left\{y\in Y:(x,y)\in A\right\}\mathop{\text{ and }}A^{y}=\left\{x\in X:(x,y)\in A\right\}
$$
Let $(X,\mathcal{F}_X),(Y,\mathcal{F}_Y)$ be measurable spaces, then a subset $A\subset X\times Y$ has measurable sections if $A^{x}\in \mathcal{F}_Y$ for each $x\in X$ and $A^{y}\in \mathcal{F}_X$ for each $y\in Y$.

:::

::: {.proposition  name=""}

Every $A\in \mathcal{F}_X\otimes \mathcal{F}_Y$ has measurable sections.

:::

::: {.proof}

Consider the family $\mathscr{A}$ of subsets of $X\times Y$ :
$$ 
\mathscr{A}=\left\{A\subset X\times Y:A^{x}\in \mathcal{F}_Y \mathop{\text{ and }}A^{y}\in \mathcal{F}_X\right\}
$$
for each $x\in X$ and $y\in Y$. Then we show that $\mathscr{A}$ is a $\sigma$-Algebra.

-   $\varnothing ^{x}=\varnothing ^{y}=\varnothing$ 
-   $(X\times Y)^{x}=Y,(X\times Y)^{y}=X$ 
-   For each family of subsets $\left\{A_{i}\right\}_{i\in I}\subset X\times Y$, $(\bigcup_{i \in  I} A_{i})^{x}=\bigcup_{i \in  I} (A_{i})^{x}$ and $(\bigcap_{i \in  I} A_{i})^{x}=\bigcap_{i \in  I} (A_{i})^{x}$, similar as $y$.

So if $\mathcal{F}_X$ is a $\sigma$-Algebra of $X$, then $\left\{A\subset X\times Y:A^{y}\in \mathcal{F}_X \mathop{\text{ for all }}y\in Y\right\}$ is also a  $\sigma$-Algebra and denote it as $\mathscr{A}_y$, similar as $\mathscr{A}_x$. Notice that the intersection of $\sigma$-Algebra is also a $\sigma$-Algebra. So $\mathscr{A}=\mathscr{A}_x\cap \mathscr{A}_y$ is a $\sigma$-Algebra.

Observe that for every measurable rectangles,
$$ 
(A\times B)^{x}=\begin{cases}
    B &\mathop{\text{if }}x\in A \\
    \varnothing &\mathop{\text{if }}x\notin A
\end{cases} 
$$
similar as $y$, so every measurable rectangles $A\times B\in \mathscr{A}$, thus $\mathcal{F}_X\otimes \mathcal{F}_Y=\sigma(\mathcal{F}_X\times \mathcal{F}_Y)\subset \mathscr{A}$, so if $A\in \mathcal{F}_X\otimes \mathcal{F}_Y$, $A$ has measurable sections.

:::

::: {.definition  name=""}

Let $(X,\mathcal{F}_X)$, $(Y,\mathcal{F}_Y)$ and $(Z,\mathcal{F}_Z)$ be measurable spaces. We say a function $f:X\times Y\to Z$ is:

1.  jointly measurable if it is $(\mathcal{F}_X\otimes \mathcal{F}_Y,\mathcal{F}_Z)$-measurable.
2.  measurable in $x$ if $f^{y}:(X,\mathcal{F}_X)\to (Z,\mathcal{F}_Z)$ is measurable for each $y\in Y$. Similarly, measurable in $y$ means $f^{x}:(Y,\mathcal{F}_Y)\to (Z,\mathcal{F}_Z)$ is measurable for each $x\in X$.
3.  separately measurable if it is both measurable in $x$ and measurable in  $y$.

:::

::: {.theorem  name=""}

Let $(X,\mathcal{F}_X),(Y,\mathcal{F}_Y),(Z,\mathcal{F}_Z)$ be measurable spaces, then every jointly measurable $f:X\times Y\to Z$ is separately measurable.

:::

::: {.proof}

Give a $y\in Y$, notice that for each $A\in \mathcal{F}_Z$,
$$ 
\begin{aligned}
    (f^{y})^{-1}(A)&=\left\{x\in X:f^{y}(x)=f(x,y)\in A\right\} \\
    &= (f^{-1}(A))^{y} 
\end{aligned}
$$
Note that $f$ is jointly measurable that implies $f^{-1}(A)\in \mathcal{F}_X\otimes \mathcal{F}_Y$, recall that $f^{-1}(A)\in \mathcal{F}_X\otimes \mathcal{F}_Y\implies f^{-1}(A)$ has measurable sections. Thus $(f^{-1}(A))^{y}\in \mathcal{F}_X$. As the arbitrary picking of $y\in Y$, and similar as $x$'s situation. So it leads to separately measurable.

:::

::: {.proposition  name=""}

Let $(X,\mathcal{F}),(X_1,\mathcal{F}_1),(X_2,\mathcal{F}_2)$ be measurable spaces, and let $f_1:X\to X_1$ and $f_2:X\to X_2$. Define $f:X\to X_1\times X_2$ by:
$$ 
f(x)=(f_1(x),f_2(x))
$$
Then $f$ is $(\mathcal{F},\mathcal{F}_1\otimes \mathcal{F}_2)$-measurable iff $f_1$ is $(\mathcal{F},\mathcal{F}_1)$-measurable and $f_2$ is $(\mathcal{F},\mathcal{F}_2)$-measurable.

:::

::: {.proof}

Notice that 
$$ 
f^{-1}(A\times B)=f_1^{-1}(A)\cap f_2^{-1}(B)
$$

:::





















